import type { Author, Localized } from './types';

/** Build a localized text bundle. French/Chinese fall back to English when omitted. */
function loc(English: string, French?: string, Chinese?: string): Localized {
  return { English, French, Chinese };
}

/** Resolve a localized value for the given language, falling back to English. */
export function localize(text: Localized | undefined, lang: string): string {
  if (!text) return '';
  return (text as Record<string, string>)[lang] ?? text.English;
}

export const AUTHORS: Author[] = [
  {
    id: 'garcia-marquez',
    nameKey: 'Gabriel García Márquez',
    name: 'Gabriel García Márquez',
    localizedName: loc('Gabriel García Márquez', undefined, '加西亚·马尔克斯'),
    wiki: loc('https://en.wikipedia.org/wiki/Gabriel_Garc%C3%ADa_M%C3%A1rquez', 'https://fr.wikipedia.org/wiki/Gabriel_Garc%C3%ADa_M%C3%A1rquez', 'https://zh.wikipedia.org/wiki/%E5%8A%A0%E5%A4%AB%E5%88%97%E5%B0%94%C2%B7%E5%8A%A0%E8%A5%BF%E4%BA%9A%C2%B7%E9%A9%AC%E5%B0%94%E5%85%8B%E6%96%AF'),
    born: 1927,
    died: 2014,
    nationality: loc('Colombian', 'Colombien', '哥伦比亚'),
    blurb: loc(
      'Born in a small Caribbean town, García Márquez spent decades wandering between Bogotá, Paris, Mexico City, and Barcelona before the solitude of his childhood crystallised into the mythical world of Macondo.',
      'Né dans une petite ville des Caraïbes, García Márquez a erré pendant des décennies entre Bogotá, Paris, Mexico et Barcelone avant que la solitude de son enfance ne se cristallise dans le monde mythique de Macondo.',
      '加西亚·马尔克斯生于加勒比海边的小镇，曾辗转于波哥大、巴黎、墨西哥城与巴塞罗那数十年，最终将童年的孤独凝结成马孔多那片神话般的世界。',
    ),
    bookIds: ['hundredyears', 'cholera'],
    events: [
      { year: 1927, place: 'Aracataca', country: 'Colombia', lng: -74.1909, lat: 10.5942, type: 'birth', note: loc('Born in the coastal town that became Macondo', 'Né dans la ville côtière qui devint Macondo', '生于后来化身为马孔多的海滨小镇') },
      { year: 1948, yearEnd: 1954, place: 'Bogotá / Barranquilla', country: 'Colombia', lng: -74.0721, lat: 4.7110, type: 'lived', note: loc('Law student, then journalist — El Espectador', 'Étudiant en droit, puis journaliste — El Espectador', '先攻读法律，后成为《观察家报》记者') },
      { year: 1955, yearEnd: 1957, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'traveled', note: loc('Stranded with almost no money after Colombia severed ties with France', 'Bloqué presque sans argent après la rupture des relations entre la Colombie et la France', '哥伦比亚与法国断交后，他几乎身无分文地滞留巴黎') },
      { year: 1957, yearEnd: 1961, place: 'Caracas', country: 'Venezuela', lng: -66.9036, lat: 10.4806, type: 'lived', note: loc('Journalist; witnessed the fall of Marcos Pérez Jiménez', 'Journaliste ; témoin de la chute de Marcos Pérez Jiménez', '任记者，亲历马科斯·佩雷斯·希门尼斯政权的垮台') },
      { year: 1961, yearEnd: 1967, place: 'Mexico City', country: 'Mexico', lng: -99.1332, lat: 19.4326, type: 'wrote', bookId: 'hundredyears', note: loc('Wrote One Hundred Years of Solitude here in 18 months (1965–1966)', 'Y écrivit Cent Ans de solitude en 18 mois (1965–1966)', '在此用十八个月写就《百年孤独》（1965—1966）') },
      { year: 1967, yearEnd: 1975, place: 'Barcelona', country: 'Spain', lng: 2.1734, lat: 41.3851, type: 'lived', note: loc('Part of the Latin American literary boom; befriended Mario Vargas Llosa', 'Au cœur du boom littéraire latino-américain ; se lia d\'amitié avec Mario Vargas Llosa', '置身拉美文学“爆炸”浪潮，与马里奥·巴尔加斯·略萨结为好友') },
      { year: 1975, yearEnd: 2014, place: 'Mexico City', country: 'Mexico', lng: -99.1332, lat: 19.4326, type: 'lived', note: loc('Final home; received Nobel Prize for Literature in 1982', 'Dernière demeure ; reçut le prix Nobel de littérature en 1982', '最后的居所，1982年获诺贝尔文学奖') },
      { year: 2014, place: 'Mexico City', country: 'Mexico', lng: -99.1332, lat: 19.4326, type: 'died', note: loc('Died of pneumonia, aged 87', 'Mort d\'une pneumonie, à 87 ans', '因肺炎逝世，享年87岁') },
    ],
  },
  {
    id: 'victor-hugo',
    nameKey: 'Victor Hugo',
    name: 'Victor Hugo',
    localizedName: loc('Victor Hugo', undefined, '维克多·雨果'),
    wiki: loc('https://en.wikipedia.org/wiki/Victor_Hugo', 'https://fr.wikipedia.org/wiki/Victor_Hugo', 'https://zh.wikipedia.org/wiki/%E7%BB%B4%E5%85%8B%E5%A4%9A%C2%B7%E9%9B%A8%E6%9E%9C'),
    born: 1802,
    died: 1885,
    nationality: loc('French', 'Français', '法国'),
    blurb: loc(
      'Hugo spent most of his life in Paris but was twice exiled — first to Brussels, then to the Channel Islands — where he wrote Les Misérables. His return to France was treated as a national event.',
      'Hugo passa la majeure partie de sa vie à Paris, mais fut exilé deux fois — d\'abord à Bruxelles, puis dans les îles Anglo-Normandes — où il écrivit Les Misérables. Son retour en France fut vécu comme un événement national.',
      '雨果一生大半在巴黎度过，却两度流亡——先至布鲁塞尔，再到海峡群岛，并在那里写下《悲惨世界》。他重返法国时被视为举国大事。',
    ),
    bookIds: ['notredame', 'lesmis'],
    events: [
      { year: 1802, place: 'Besançon', country: 'France', lng: 6.0241, lat: 47.2378, type: 'birth', note: loc('Born in Franche-Comté; father was a general in Napoleon\'s army', 'Né en Franche-Comté ; son père était général dans l\'armée de Napoléon', '生于弗朗什-孔泰，父亲是拿破仑麾下的将军') },
      { year: 1815, yearEnd: 1851, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'lived', note: loc('Rose from poet-child to towering literary and political figure', 'Passa d\'enfant poète à figure majeure de la littérature et de la politique', '从少年诗人成长为文学与政治的巨擘') },
      { year: 1831, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'wrote', bookId: 'notredame', note: loc('Published The Hunchback of Notre-Dame', 'Publia Notre-Dame de Paris', '出版《巴黎圣母院》') },
      { year: 1851, place: 'Brussels', country: 'Belgium', lng: 4.3517, lat: 50.8503, type: 'traveled', note: loc('Fled after Louis-Napoleon\'s coup d\'état', 'S\'enfuit après le coup d\'État de Louis-Napoléon', '路易·拿破仑发动政变后出逃') },
      { year: 1852, place: 'Jersey', country: 'Channel Islands', lng: -2.1207, lat: 49.2144, type: 'lived', note: loc('Exiled from Belgium; began dictating Les Misérables', 'Exilé de Belgique ; commença à dicter Les Misérables', '被逐出比利时，开始口授《悲惨世界》') },
      { year: 1855, yearEnd: 1870, place: 'Guernsey', country: 'Channel Islands', lng: -2.5350, lat: 49.4660, type: 'wrote', bookId: 'lesmis', note: loc('Hauteville House — completed Les Misérables (published 1862)', 'Hauteville House — acheva Les Misérables (publié en 1862)', '在高城居完成《悲惨世界》（1862年出版）') },
      { year: 1870, yearEnd: 1885, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'lived', note: loc('Returned after the fall of Napoleon III; became a senator', 'Revint après la chute de Napoléon III ; devint sénateur', '拿破仑三世垮台后回国，出任参议员') },
      { year: 1885, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'died', note: loc('State funeral; two million people lined the streets', 'Funérailles nationales ; deux millions de personnes dans les rues', '国葬之日，二百万民众夹道送别') },
    ],
  },
  {
    id: 'george-orwell',
    nameKey: 'George Orwell',
    name: 'George Orwell',
    localizedName: loc('George Orwell', undefined, '乔治·奥威尔'),
    wiki: loc('https://en.wikipedia.org/wiki/George_Orwell', 'https://fr.wikipedia.org/wiki/George_Orwell', 'https://zh.wikipedia.org/wiki/%E4%B9%94%E6%B2%BB%C2%B7%E5%A5%A5%E5%A8%81%E5%B0%94'),
    born: 1903,
    died: 1950,
    nationality: loc('British', 'Britannique', '英国'),
    blurb: loc(
      'Eric Blair — who wrote as George Orwell — was born in India, policed Burma, lived in poverty in Paris, fought in Spain, and retreated to a remote Scottish island to write Nineteen Eighty-Four. His life was as restless as his prose.',
      'Eric Blair — qui écrivait sous le nom de George Orwell — naquit en Inde, fut policier en Birmanie, vécut dans la misère à Paris, combattit en Espagne et se retira sur une île écossaise isolée pour écrire 1984. Sa vie fut aussi agitée que sa prose.',
      '埃里克·布莱尔——以乔治·奥威尔之名写作——生于印度，曾在缅甸当警察，在巴黎贫困度日，赴西班牙参战，最后隐居苏格兰偏远海岛写下《一九八四》。他的一生与他的文字一样不得安宁。',
    ),
    bookIds: ['nineteen84', 'homagetocatalonia'],
    events: [
      { year: 1903, place: 'Motihari', country: 'India', lng: 84.9120, lat: 26.6584, type: 'birth', note: loc('Born in British India (now Bihar, near the Nepal border)', 'Né dans l\'Inde britannique (aujourd\'hui le Bihar, près de la frontière népalaise)', '生于英属印度（今比哈尔邦，邻近尼泊尔边境）') },
      { year: 1911, yearEnd: 1922, place: 'Henley / Eton', country: 'UK', lng: -1.0740, lat: 51.5085, type: 'lived', note: loc('Schooling in England; won a scholarship to Eton College', 'Scolarité en Angleterre ; obtint une bourse pour le collège d\'Eton', '在英格兰求学，获奖学金入读伊顿公学') },
      { year: 1922, yearEnd: 1927, place: 'Mandalay', country: 'Myanmar', lng: 96.0891, lat: 21.9588, type: 'lived', note: loc('Served as an Imperial Police officer in Burma; resigned in disgust at colonialism', 'Officier de la police impériale en Birmanie ; démissionna par dégoût du colonialisme', '在缅甸任帝国警官，因厌恶殖民统治而辞职') },
      { year: 1928, yearEnd: 1929, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'lived', note: loc('Plunged deliberately into poverty; washed dishes; material for Down and Out in Paris and London', 'Se plongea volontairement dans la misère ; plongeur de vaisselle ; matière de Dans la dèche à Paris et à Londres', '主动投身贫困，靠洗碗为生，成为《巴黎伦敦落魄记》的素材') },
      { year: 1936, yearEnd: 1937, place: 'Barcelona', country: 'Spain', lng: 2.1734, lat: 41.3851, type: 'traveled', bookId: 'homagetocatalonia', note: loc('Fought with POUM militia in the Spanish Civil War; wounded in the throat — the experience became Homage to Catalonia', 'Combattit dans la milice du POUM pendant la guerre civile espagnole ; blessé à la gorge — l\'expérience est devenue Hommage à la Catalogne', '在西班牙内战中随马统工党民兵作战，喉部中弹负伤——这段经历成为《向加泰罗尼亚致敬》') },
      { year: 1938, place: 'Marrakech', country: 'Morocco', lng: -7.9811, lat: 31.6295, type: 'traveled', note: loc('Convalesced from tuberculosis; wrote A Moroccan Journal', 'Convalescence après une tuberculose ; écrivit un Journal marocain', '为养肺结核而疗养，写下《摩洛哥日记》') },
      { year: 1944, yearEnd: 1946, place: 'London', country: 'UK', lng: -0.1276, lat: 51.5074, type: 'wrote', note: loc('Wrote Animal Farm; worked at Tribune; wife Eileen died 1945', 'Écrivit La Ferme des animaux ; travailla au Tribune ; sa femme Eileen mourut en 1945', '写就《动物农场》，供职于《论坛报》，妻子艾琳于1945年去世') },
      { year: 1947, yearEnd: 1949, place: 'Jura', country: 'UK', lng: -5.8000, lat: 55.9500, type: 'wrote', bookId: 'nineteen84', note: loc('Remote farmhouse on the Isle of Jura — wrote Nineteen Eighty-Four in worsening health', 'Ferme isolée sur l\'île de Jura — écrivit 1984 alors que sa santé déclinait', '在朱拉岛偏僻的农舍里，于每况愈下的病体中写下《一九八四》') },
      { year: 1950, place: 'London', country: 'UK', lng: -0.1276, lat: 51.5074, type: 'died', note: loc('Died of tuberculosis in University College Hospital, aged 46', 'Mort de la tuberculose au University College Hospital, à 46 ans', '因肺结核病逝于大学学院医院，享年46岁') },
    ],
  },
  {
    id: 'jg-ballard',
    nameKey: 'J.G. Ballard',
    name: 'J.G. Ballard',
    localizedName: loc('J.G. Ballard', undefined, 'J·G·巴拉德'),
    wiki: loc('https://en.wikipedia.org/wiki/J._G._Ballard', 'https://fr.wikipedia.org/wiki/J._G._Ballard', 'https://zh.wikipedia.org/wiki/J%C2%B7G%C2%B7%E5%B7%B4%E6%8B%89%E5%BE%B7'),
    born: 1930,
    died: 2009,
    nationality: loc('British', 'Britannique', '英国'),
    blurb: loc(
      "Ballard was born in Shanghai's International Settlement, interned by the Japanese as a child, and spent the rest of his life in suburban England — yet the trauma of his Shanghai years never left his fiction.",
      'Ballard naquit dans la concession internationale de Shanghai, fut interné par les Japonais enfant et passa le reste de sa vie dans la banlieue anglaise — pourtant le traumatisme de ses années shanghaïennes ne quitta jamais son œuvre.',
      '巴拉德生于上海公共租界，幼年被日军关押，余生定居英格兰郊区——然而上海岁月的创伤始终萦绕在他的小说之中。',
    ),
    bookIds: ['empiresun'],
    events: [
      { year: 1930, place: 'Shanghai', country: 'China', lng: 121.4737, lat: 31.2304, type: 'birth', note: loc('Born in the International Settlement; privileged expatriate childhood', 'Né dans la concession internationale ; enfance privilégiée d\'expatrié', '生于公共租界，度过优渥的侨民童年') },
      { year: 1943, yearEnd: 1945, place: 'Lunghua Camp, Shanghai', country: 'China', lng: 121.4800, lat: 31.1500, type: 'lived', note: loc('Interned in Lunghua Civilian Assembly Centre by Japan — the basis for Empire of the Sun', 'Interné au centre civil de Lunghua par le Japon — source de L\'Empire du soleil', '被日军关押于龙华平民集中营——《太阳帝国》的原型') },
      { year: 1946, place: 'Cambridge', country: 'UK', lng: 0.1218, lat: 52.2053, type: 'traveled', note: loc('Sent to England; felt like an alien in his own country', 'Envoyé en Angleterre ; se sentit étranger dans son propre pays', '被送往英格兰，却在自己的祖国感到格格不入') },
      { year: 1949, yearEnd: 1951, place: 'Cambridge', country: 'UK', lng: 0.1218, lat: 52.2053, type: 'lived', note: loc('Read medicine at King\'s College; left before graduating', 'Étudia la médecine à King\'s College ; partit avant d\'obtenir son diplôme', '在国王学院攻读医学，未毕业便离开') },
      { year: 1960, yearEnd: 2009, place: 'Shepperton', country: 'UK', lng: -0.5110, lat: 51.3950, type: 'lived', note: loc('Spent almost 50 years in the same semi-detached house in Shepperton, Surrey', 'Passa près de 50 ans dans la même maison jumelée à Shepperton, dans le Surrey', '在萨里郡谢珀顿同一栋半独立住宅中住了近五十年') },
      { year: 1984, place: 'Shepperton', country: 'UK', lng: -0.5110, lat: 51.3950, type: 'wrote', bookId: 'empiresun', note: loc('Published Empire of the Sun; shortlisted for the Booker Prize', 'Publia L\'Empire du soleil ; finaliste du Booker Prize', '出版《太阳帝国》，入围布克奖短名单') },
      { year: 2009, place: 'Shepperton', country: 'UK', lng: -0.5110, lat: 51.3950, type: 'died', note: loc('Died of prostate cancer, aged 78', 'Mort d\'un cancer de la prostate, à 78 ans', '因前列腺癌逝世，享年78岁') },
    ],
  },
  {
    id: 'khaled-hosseini',
    nameKey: 'Khaled Hosseini',
    name: 'Khaled Hosseini',
    localizedName: loc('Khaled Hosseini', undefined, '卡勒德·胡赛尼'),
    wiki: loc('https://en.wikipedia.org/wiki/Khaled_Hosseini', 'https://fr.wikipedia.org/wiki/Khaled_Hosseini', 'https://zh.wikipedia.org/wiki/%E5%8D%A1%E5%8B%92%E5%BE%B7%C2%B7%E8%83%A1%E8%B5%9B%E5%B0%BC'),
    born: 1965,
    nationality: loc('Afghan-American', 'Afghano-américain', '阿富汗裔美国'),
    blurb: loc(
      'Hosseini grew up in Kabul, lived in Tehran and Paris as the son of a diplomat, and fled to California after the Soviet invasion. His novels are acts of memory — returning to Afghanistan on the page when he could no longer do so in person.',
      'Hosseini grandit à Kaboul, vécut à Téhéran et à Paris comme fils de diplomate, puis fuit en Californie après l\'invasion soviétique. Ses romans sont des actes de mémoire — un retour en Afghanistan sur la page, là où il ne pouvait plus le faire en personne.',
      '胡赛尼在喀布尔长大，作为外交官之子曾旅居德黑兰与巴黎，苏联入侵后逃往加利福尼亚。他的小说是记忆之举——当他再也无法亲身回到阿富汗，便在纸页上重返故土。',
    ),
    bookIds: ['kiterunner', 'thousandsuns'],
    events: [
      { year: 1965, place: 'Kabul', country: 'Afghanistan', lng: 69.1760, lat: 34.5260, type: 'birth', note: loc('Born into a middle-class family in Kabul', 'Né dans une famille de la classe moyenne à Kaboul', '生于喀布尔一个中产家庭') },
      { year: 1970, yearEnd: 1973, place: 'Tehran', country: 'Iran', lng: 51.3890, lat: 35.6892, type: 'lived', note: loc('Father posted to Iranian capital as a diplomat', 'Père en poste diplomatique dans la capitale iranienne', '父亲作为外交官派驻伊朗首都') },
      { year: 1976, yearEnd: 1980, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'lived', note: loc('Father posted to Paris; family applied for asylum after Soviet invasion of Afghanistan (1979)', 'Père en poste à Paris ; la famille demanda l\'asile après l\'invasion soviétique de l\'Afghanistan (1979)', '父亲调驻巴黎；苏联入侵阿富汗（1979年）后，全家申请政治庇护') },
      { year: 1980, yearEnd: 2001, place: 'San Jose', country: 'USA', lng: -121.8863, lat: 37.3382, type: 'lived', note: loc('Settled in California; worked as a physician while writing secretly', 'S\'installa en Californie ; exerça comme médecin tout en écrivant en secret', '定居加州，一边行医一边悄悄写作') },
      { year: 2003, place: 'San Jose', country: 'USA', lng: -121.8863, lat: 37.3382, type: 'wrote', bookId: 'kiterunner', note: loc('Published The Kite Runner — his debut novel became a global phenomenon', 'Publia Les Cerfs-volants de Kaboul — son premier roman devint un phénomène mondial', '出版《追风筝的人》，这部处女作风靡全球') },
      { year: 2007, place: 'San Jose', country: 'USA', lng: -121.8863, lat: 37.3382, type: 'wrote', bookId: 'thousandsuns', note: loc('Published A Thousand Splendid Suns', 'Publia Mille soleils splendides', '出版《灿烂千阳》') },
    ],
  },
  {
    id: 'kazuo-ishiguro',
    nameKey: 'Kazuo Ishiguro',
    name: 'Kazuo Ishiguro',
    localizedName: loc('Kazuo Ishiguro', undefined, '石黑一雄'),
    wiki: loc('https://en.wikipedia.org/wiki/Kazuo_Ishiguro', 'https://fr.wikipedia.org/wiki/Kazuo_Ishiguro', 'https://zh.wikipedia.org/wiki/%E7%9F%B3%E9%BB%91%E4%B8%80%E9%9B%84'),
    born: 1954,
    nationality: loc('British-Japanese', 'Anglo-japonais', '日裔英国'),
    blurb: loc(
      'Born in Nagasaki and raised in England from age five, Ishiguro writes from a position of dual displacement — Japanese by origin yet quintessentially English in sensibility, exploring memory, loss, and what people choose not to remember.',
      'Né à Nagasaki et élevé en Angleterre dès l\'âge de cinq ans, Ishiguro écrit depuis un double déracinement — japonais d\'origine mais profondément anglais de sensibilité, explorant la mémoire, la perte et ce que l\'on choisit d\'oublier.',
      '石黑一雄生于长崎，五岁起在英格兰长大，从双重的疏离中写作——血缘上是日本人，气质却彻底英国化，他笔下探究记忆、失落，以及人们选择不去记起的事。',
    ),
    bookIds: ['remainsday'],
    events: [
      { year: 1954, place: 'Nagasaki', country: 'Japan', lng: 129.8737, lat: 32.7503, type: 'birth', note: loc('Born two years after the atomic bombing; father was an oceanographer', 'Né deux ans après le bombardement atomique ; son père était océanographe', '生于原子弹轰炸两年之后，父亲是海洋学家') },
      { year: 1960, yearEnd: 1978, place: 'Guildford', country: 'UK', lng: -0.5680, lat: 51.2362, type: 'lived', note: loc('Family moved when his father took a job with the British government; grew up in Surrey', 'La famille déménagea lorsque son père prit un poste au gouvernement britannique ; grandit dans le Surrey', '父亲受聘于英国政府后举家迁居，他在萨里郡长大') },
      { year: 1978, yearEnd: 1980, place: 'Edinburgh', country: 'UK', lng: -3.1883, lat: 55.9533, type: 'lived', note: loc('Worked as a grouse beater on the Balmoral estate; later studied at University of East Anglia', 'Rabatteur de grouse sur le domaine de Balmoral ; étudia ensuite à l\'université d\'East Anglia', '曾在巴尔莫勒尔庄园当松鸡驱赶员，后入读东英吉利大学') },
      { year: 1980, yearEnd: 1986, place: 'Norwich', country: 'UK', lng: 1.2929, lat: 52.6309, type: 'wrote', note: loc('MA in Creative Writing at UEA under Malcolm Bradbury; published A Pale View of Hills (1982)', 'Master de création littéraire à l\'UEA sous Malcolm Bradbury ; publia Lumière pâle sur les collines (1982)', '在东英吉利大学师从马尔科姆·布拉德伯里攻读创意写作硕士，出版《远山淡影》（1982）') },
      { year: 1987, yearEnd: 1989, place: 'London', country: 'UK', lng: -0.1276, lat: 51.5074, type: 'wrote', bookId: 'remainsday', note: loc('Wrote The Remains of the Day, which won the Booker Prize in 1989', 'Écrivit Les Vestiges du jour, qui remporta le Booker Prize en 1989', '写就《长日将尽》，于1989年荣获布克奖') },
      { year: 1989, place: 'London', country: 'UK', lng: -0.1276, lat: 51.5074, type: 'lived', note: loc('Settled in London; awarded Nobel Prize for Literature in 2017', 'S\'installa à Londres ; reçut le prix Nobel de littérature en 2017', '定居伦敦，2017年获诺贝尔文学奖') },
    ],
  },
  {
    id: 'f-scott-fitzgerald',
    nameKey: 'F. Scott Fitzgerald',
    name: 'F. Scott Fitzgerald',
    localizedName: loc('F. Scott Fitzgerald', undefined, 'F·斯科特·菲茨杰拉德'),
    wiki: loc('https://en.wikipedia.org/wiki/F._Scott_Fitzgerald', 'https://fr.wikipedia.org/wiki/F._Scott_Fitzgerald', 'https://zh.wikipedia.org/wiki/F%C2%B7%E6%96%AF%E7%A7%91%E7%89%B9%C2%B7%E8%8F%B2%E8%8C%A8%E6%9D%B0%E6%8B%89%E5%BE%B7'),
    born: 1896,
    died: 1940,
    nationality: loc('American', 'Américain', '美国'),
    blurb: loc(
      'Fitzgerald charted the arc of the Jazz Age with glittering precision — from the parties of Long Island Sound to the cafés of the Left Bank and the fatal glamour of the French Riviera — before the party ended for him in Hollywood.',
      'Fitzgerald traça l\'arc de l\'âge du jazz avec une précision étincelante — des fêtes du Long Island Sound aux cafés de la Rive gauche et au glamour fatal de la Côte d\'Azur — avant que la fête ne s\'achève pour lui à Hollywood.',
      '菲茨杰拉德以璀璨的笔触描摹爵士时代的轨迹——从长岛海湾的派对，到左岸的咖啡馆，再到法国里维埃拉那致命的浮华——直到这场盛宴最终在好莱坞为他落幕。',
    ),
    bookIds: ['gatsby'],
    events: [
      { year: 1896, place: 'Saint Paul, MN', country: 'USA', lng: -93.0900, lat: 44.9537, type: 'birth', note: loc('Born in Saint Paul, Minnesota', 'Né à Saint Paul, dans le Minnesota', '生于明尼苏达州圣保罗') },
      { year: 1913, yearEnd: 1917, place: 'Princeton, NJ', country: 'USA', lng: -74.6514, lat: 40.3573, type: 'lived', note: loc('Princeton University; left without graduating to join the Army in WWI', 'Université de Princeton ; partit sans diplôme pour s\'engager dans l\'armée durant la Première Guerre mondiale', '就读普林斯顿大学，未毕业即从军参加一战') },
      { year: 1920, yearEnd: 1924, place: 'New York', country: 'USA', lng: -73.9857, lat: 40.7484, type: 'lived', note: loc('This Side of Paradise made him famous overnight; married Zelda; the Jazz Age began', 'L\'Envers du paradis le rendit célèbre du jour au lendemain ; épousa Zelda ; l\'âge du jazz commença', '《人间天堂》令他一夜成名，迎娶泽尔达，爵士时代由此开启') },
      { year: 1924, yearEnd: 1926, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'wrote', bookId: 'gatsby', note: loc('Part of the Lost Generation on the Left Bank; wrote The Great Gatsby (published 1925)', 'Membre de la Génération perdue sur la Rive gauche ; écrivit Gatsby le Magnifique (publié en 1925)', '身处左岸“迷惘的一代”，写下《了不起的盖茨比》（1925年出版）') },
      { year: 1924, yearEnd: 1930, place: 'Côte d\'Azur', country: 'France', lng: 7.2661, lat: 43.7102, type: 'lived', note: loc('Summers on the French Riviera; Tender is the Night is set here; Zelda\'s breakdown began', 'Étés sur la Côte d\'Azur ; Tendre est la nuit s\'y déroule ; le déclin de Zelda commença', '在法国里维埃拉度过夏日，《夜色温柔》以此为背景，泽尔达的精神崩溃也始于此') },
      { year: 1937, yearEnd: 1940, place: 'Hollywood', country: 'USA', lng: -118.2437, lat: 34.0522, type: 'lived', note: loc('Worked as a screenwriter; working on The Last Tycoon when he died', 'Travailla comme scénariste ; rédigeait Le Dernier Nabab à sa mort', '担任编剧，离世时正在创作《最后的大亨》') },
      { year: 1940, place: 'Hollywood', country: 'USA', lng: -118.2437, lat: 34.0522, type: 'died', note: loc('Died of a heart attack, aged 44', 'Mort d\'une crise cardiaque, à 44 ans', '因心脏病发作逝世，享年44岁') },
    ],
  },
  {
    id: 'ba-jin',
    nameKey: '巴金 Ba Jin',
    name: 'Ba Jin',
    localizedName: loc('Ba Jin', 'Ba Jin', '巴金'),
    wiki: loc('https://en.wikipedia.org/wiki/Ba_Jin', 'https://fr.wikipedia.org/wiki/Ba_Jin', 'https://zh.wikipedia.org/wiki/%E5%B7%B4%E9%87%91'),
    born: 1904,
    died: 2005,
    nationality: loc('Chinese', 'Chinois', '中国'),
    blurb: loc(
      'Ba Jin took his pen name from Bakunin and Kropotkin, two anarchist thinkers who shaped his youth in Chengdu. He spent years in Paris before returning to Shanghai to write the Turbulent Torrent trilogy. Fifty years later, the Cultural Revolution sent him to a labour camp while his wife died of untreated cancer. His five-volume Reflections became modern China\'s most searching act of self-examination.',
      'Ba Jin tira son nom de plume de Bakounine et Kropotkine, deux penseurs anarchistes qui forgèrent sa jeunesse à Chengdu. Il passa des années à Paris avant de rentrer à Shanghai pour écrire la trilogie du Torrent tumultueux. Cinquante ans plus tard, la Révolution culturelle l\'envoya dans un camp de travail tandis que sa femme mourait d\'un cancer non traité. Ses Réflexions en cinq volumes devinrent l\'auto-examen le plus profond de la Chine moderne.',
      '巴金的笔名取自巴枯宁与克鲁泡特金，这两位无政府主义者塑造了他在成都的青年理想。他旅居巴黎后回到上海，写下"激流三部曲"。五十年后，文化大革命将他投入劳改，妻子萧珊因无法得到救治含冤离世。他的五卷本《随想录》成为现代中国最深刻的自我审视。',
    ),
    bookIds: ['family', 'chun', 'qiu', 'coldnight'],
    events: [
      { year: 1904, place: 'Chengdu', country: 'China', lng: 104.0668, lat: 30.5828, type: 'birth', note: loc('Born Li Yaotang into a large, wealthy family of declining officials; witnessed his family\'s decay from the inside', 'Né Li Yaotang dans une grande famille de fonctionnaires aisés en déclin ; témoin de l\'intérieur de la décomposition familiale', '本名李尧棠，生于成都一没落官宦大家族，亲历大家族从内部走向崩解') },
      { year: 1927, yearEnd: 1929, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'lived', note: loc('Studied in Paris; inspired by anarchist thought; wrote his debut novel Destruction (灭亡) in a cheap hotel room', 'Étudia à Paris ; inspiré par la pensée anarchiste ; écrivit son premier roman La Destruction (灭亡) dans une chambre d\'hôtel bon marché', '旅居巴黎求学，深受无政府主义思潮影响，在简陋的旅馆房间里写下处女作《灭亡》') },
      { year: 1929, yearEnd: 1937, place: 'Shanghai', country: 'China', lng: 121.4737, lat: 31.2304, type: 'wrote', bookId: 'family', note: loc('Returned to China; settled in Shanghai\'s literary world; wrote the Turbulent Torrent trilogy — Family (1933), Spring (1938), and Autumn (1940)', 'Rentra en Chine ; s\'installa dans le monde littéraire de Shanghai ; écrivit la trilogie du Torrent tumultueux — Famille (1933), Printemps (1938) et Automne (1940)', '回国后定居上海文坛，写下"激流三部曲"——《家》（1933）、《春》（1938）、《秋》（1940）') },
      { year: 1938, yearEnd: 1946, place: 'Chongqing', country: 'China', lng: 106.5516, lat: 29.5630, type: 'wrote', bookId: 'coldnight', note: loc('Fled the Japanese invasion; moved between Guangzhou, Guilin, and Chongqing; wrote Cold Nights (寒夜, 1947) — his most artistically mature novel', 'Fuit l\'invasion japonaise ; se déplaça entre Canton, Guilin et Chongqing ; écrivit Nuits froides (寒夜, 1947) — son roman le plus abouti artistiquement', '辗转广州、桂林、重庆等地避日军入侵，写下艺术上最为成熟的《寒夜》（1947）') },
      { year: 1949, yearEnd: 1976, place: 'Shanghai', country: 'China', lng: 121.4737, lat: 31.2304, type: 'lived', note: loc('Welcomed the new PRC; then lost everything in the Cultural Revolution — sent to a cadre school for labour, banned from writing; his wife Xiao Shan died of cancer in 1972, denied treatment', 'Accueillit la nouvelle République populaire ; puis tout perdit pendant la Révolution culturelle — envoyé dans une école de cadres pour travailler, interdit d\'écrire ; sa femme Xiao Shan mourut d\'un cancer en 1972, les soins lui ayant été refusés', '欢迎新中国成立，却在文化大革命中失去一切——被下放劳改，被禁止写作；妻子萧珊于1972年因得不到治疗而含冤病逝') },
      { year: 1978, yearEnd: 2004, place: 'Shanghai', country: 'China', lng: 121.4737, lat: 31.2304, type: 'wrote', note: loc('Rehabilitated; wrote the five-volume Reflections (随想录, 1978–1986) — the most unflinching reckoning with the Cultural Revolution by any Chinese writer', 'Réhabilité ; écrivit les cinq volumes des Réflexions (随想录, 1978–1986) — le bilan le plus implacable de la Révolution culturelle par un écrivain chinois', '获平反后写下五卷本《随想录》（1978—1986），是迄今最无畏地清算文化大革命的中国作家作品') },
      { year: 2005, place: 'Shanghai', country: 'China', lng: 121.4737, lat: 31.2304, type: 'died', note: loc('Died in Shanghai, aged 101 — the last major voice of the May Fourth generation', 'Décédé à Shanghai, à 101 ans — dernière grande voix de la génération du Mouvement du 4 mai', '逝于上海，享年101岁——五四一代的最后一位文学巨匠') },
    ],
  },
  {
    id: 'albert-camus',
    nameKey: 'Albert Camus',
    name: 'Albert Camus',
    localizedName: loc('Albert Camus', 'Albert Camus', '阿尔贝·加缪'),
    wiki: loc('https://en.wikipedia.org/wiki/Albert_Camus', 'https://fr.wikipedia.org/wiki/Albert_Camus', 'https://zh.wikipedia.org/wiki/%E9%98%BF%E5%B0%94%E8%B4%9D%C2%B7%E5%8A%A0%E7%BC%AA'),
    born: 1913,
    died: 1960,
    nationality: loc('French-Algerian', 'Franco-algérien', '法属阿尔及利亚裔法国'),
    blurb: loc(
      'Born into poverty in colonial Algeria, Camus grew up without his father and with a mother who could not read. The Algerian sun and the philosophy of the absurd shaped his entire work — before a car accident on a French road silenced him at 46, Nobel Prize in his pocket.',
      'Né dans la pauvreté de l\'Algérie coloniale, Camus grandit sans père et avec une mère analphabète. Le soleil algérien et la philosophie de l\'absurde ont façonné toute son œuvre — avant qu\'un accident de voiture sur une route française ne le réduise au silence à 46 ans, avec le prix Nobel en poche.',
      '加缪生于法属阿尔及利亚的贫苦家庭，父亲早逝，母亲目不识丁。阿尔及利亚的烈日与荒诞哲学塑造了他的全部作品——1957年获诺贝尔文学奖，三年后在法国公路上的一场车祸中，年仅46岁，永远沉默。',
    ),
    bookIds: ['stranger', 'plague'],
    events: [
      { year: 1913, place: 'Mondovi', country: 'Algeria', lng: 7.7500, lat: 36.6833, type: 'birth', note: loc('Born in a small farm settlement; father killed at the Battle of the Marne before Camus turned one', 'Né dans un petit hameau agricole ; père tué à la bataille de la Marne avant que Camus ait un an', '生于一处农庄聚落，父亲在他未满周岁时即战死于马恩河战役') },
      { year: 1913, yearEnd: 1940, place: 'Algiers', country: 'Algeria', lng: 3.0588, lat: 36.7538, type: 'lived', note: loc('Grew up in the Belcourt working-class district; won a scholarship; studied philosophy at the University of Algiers; contracted tuberculosis; worked as journalist at Alger républicain', 'Grandit dans le quartier ouvrier de Belcourt ; obtint une bourse ; étudia la philosophie à l\'université d\'Alger ; contracta la tuberculose ; journaliste à Alger républicain', '成长于贝尔古尔工人区，靠奖学金求学，在阿尔及尔大学攻读哲学，染上肺结核，后任职《共和阿尔及利亚人报》记者') },
      { year: 1940, yearEnd: 1960, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'lived', note: loc('Moved to Paris; joined the Resistance; edited the clandestine newspaper Combat; received the Nobel Prize for Literature in 1957', 'S\'installa à Paris ; rejoignit la Résistance ; dirigea le journal clandestin Combat ; reçut le prix Nobel de littérature en 1957', '移居巴黎，加入抵抗运动，主编地下报纸《战斗报》，1957年获诺贝尔文学奖') },
      { year: 1942, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'wrote', bookId: 'stranger', note: loc('Published L\'Étranger — founding text of the philosophy of the absurd', 'Publia L\'Étranger — texte fondateur de la philosophie de l\'absurde', '出版《局外人》——荒诞哲学的奠基之作') },
      { year: 1947, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'wrote', bookId: 'plague', note: loc('Published La Peste — an allegory of the Occupation and of human solidarity under catastrophe', 'Publia La Peste — allégorie de l\'Occupation et de la solidarité humaine face à la catastrophe', '出版《鼠疫》——以瘟疫为喻，书写占领时期与灾难中的人类共同体') },
      { year: 1960, place: 'Villeblevin', country: 'France', lng: 3.3000, lat: 48.2667, type: 'died', note: loc('Killed in a car accident near Sens; an unused train ticket was found in his coat pocket', 'Tué dans un accident de voiture près de Sens ; un billet de train inutilisé fut retrouvé dans sa poche', '在塞纳省附近遭遇车祸罹难，衣袋中有一张未使用的火车票') },
    ],
  },
  {
    id: 'milan-kundera',
    nameKey: 'Milan Kundera',
    name: 'Milan Kundera',
    localizedName: loc('Milan Kundera', 'Milan Kundera', '米兰·昆德拉'),
    wiki: loc('https://en.wikipedia.org/wiki/Milan_Kundera', 'https://fr.wikipedia.org/wiki/Milan_Kundera', 'https://zh.wikipedia.org/wiki/%E7%B1%B3%E5%85%B0%C2%B7%E6%98%86%E5%BE%B7%E6%8B%89'),
    born: 1929,
    died: 2023,
    nationality: loc('Czech-French', 'Tchéco-français', '捷克裔法国'),
    blurb: loc(
      'Kundera spent his first 46 years in Czechoslovakia — rising from novelist to dissident after the 1968 Soviet invasion destroyed his career. The remaining 48 years were Parisian exile, writing first in Czech, then in French, a language he adopted as his own.',
      'Kundera passa ses 46 premières années en Tchécoslovaquie — passant de romancier à dissident après que l\'invasion soviétique de 1968 eut brisé sa carrière. Les 48 années suivantes furent un exil parisien, écrivant d\'abord en tchèque, puis en français, une langue qu\'il adopta comme sienne.',
      '昆德拉在捷克斯洛伐克度过了人生前四十六年——从小说家到异见者，1968年苏联入侵后职业生涯骤然中断。此后四十八年，他在巴黎流亡，先以捷克语，后以法语写作，将这门语言当作自己的语言。',
    ),
    bookIds: ['lightnessbeing'],
    events: [
      { year: 1929, place: 'Brno', country: 'Czech Republic', lng: 16.6068, lat: 49.1951, type: 'birth', note: loc('Born into a musical family; his father was a pianist and student of Leoš Janáček', 'Né dans une famille de musiciens ; son père était pianiste et élève de Leoš Janáček', '生于音乐世家，父亲是钢琴家，曾师从莱奥什·雅纳切克') },
      { year: 1948, yearEnd: 1968, place: 'Prague', country: 'Czech Republic', lng: 14.4020, lat: 50.0880, type: 'lived', note: loc('Studied film at FAMU; joined the Communist Party (later disillusioned); published The Joke (1967); supported the Prague Spring reforms under Dubček', 'Étudia le cinéma à la FAMU ; adhéra au Parti communiste (avant de se désillussionner) ; publia La Plaisanterie (1967) ; soutint les réformes du Printemps de Prague sous Dubček', '就读布拉格电影学院，加入共产党（后幻灭）；出版《玩笑》（1967），支持杜布切克领导的布拉格之春改革') },
      { year: 1968, yearEnd: 1975, place: 'Prague', country: 'Czech Republic', lng: 14.4020, lat: 50.0880, type: 'lived', note: loc('Soviet tanks rolled in; Kundera was expelled from the Party, banned from publishing, and his books were removed from all libraries — seven years of internal silence', 'Les chars soviétiques envahirent Prague ; Kundera fut exclu du Parti, interdit de publication, et ses livres retirés de toutes les bibliothèques — sept ans de silence intérieur', '苏联坦克入侵，昆德拉被开除党籍，遭禁止出版，著作从所有图书馆下架——七年的内部沉默') },
      { year: 1975, yearEnd: 1978, place: 'Rennes', country: 'France', lng: -1.6778, lat: 48.1173, type: 'lived', note: loc('Emigrated to France; taught comparative literature at the University of Rennes; Czech citizenship revoked in 1979', 'Émigra en France ; enseigna la littérature comparée à l\'université de Rennes ; citoyenneté tchèque révoquée en 1979', '移居法国，在雷恩大学执教比较文学；1979年捷克国籍被吊销') },
      { year: 1978, yearEnd: 2023, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'wrote', bookId: 'lightnessbeing', note: loc('Settled in Paris; granted French citizenship (1981); wrote The Unbearable Lightness of Being in Czech (published 1984); later switched to writing in French', 'S\'installa à Paris ; naturalisé français (1981) ; écrivit L\'Insoutenable Légèreté de l\'être en tchèque (publié en 1984) ; écrivit ensuite en français', '定居巴黎，1981年取得法国国籍；以捷克语写成《不能承受的生命之轻》（1984年出版），后转以法语写作') },
      { year: 2023, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'died', note: loc('Died in Paris, aged 94', 'Décédé à Paris, à 94 ans', '在巴黎辞世，享年94岁') },
    ],
  },
  {
    id: 'lao-she',
    nameKey: '老舍 Lao She',
    name: 'Lao She',
    localizedName: loc('Lao She', 'Lao She', '老舍'),
    wiki: loc('https://en.wikipedia.org/wiki/Lao_She', 'https://fr.wikipedia.org/wiki/Lao_She', 'https://zh.wikipedia.org/wiki/%E8%80%81%E8%88%8D'),
    born: 1899,
    died: 1966,
    nationality: loc('Chinese', 'Chinois', '中国'),
    blurb: loc(
      'Born Shu Qingchun in Beijing, Lao She became the most beloved chronicler of the city\'s hutong life. He spent years teaching at SOAS in London and touring America before returning to the People\'s Republic — only to take his own life at Taiping Lake during the Cultural Revolution.',
      'Né Shu Qingchun à Pékin, Lao She devint le chroniqueur le plus aimé de la vie des hutong. Il passa des années à enseigner à la SOAS de Londres et à parcourir l\'Amérique avant de rentrer en République populaire — avant de mettre fin à ses jours au lac Taiping pendant la Révolution culturelle.',
      '老舍，本名舒庆春，生于北京，是胡同市井生活最深情的记录者。他曾在伦敦大学亚非学院执教，后游历美国，归国后受文化大革命影响，于北京太平湖投湖自尽。',
    ),
    bookIds: ['rickshaw', 'teahouse'],
    events: [
      { year: 1899, place: 'Beijing', country: 'China', lng: 116.3974, lat: 39.9087, type: 'birth', note: loc('Born Shu Qingchun in the Zhenghuangqi Banner district; father died defending Beijing during the Boxer Uprising', 'Né Shu Qingchun dans le district Zhenghuangqi ; son père mourut en défendant Pékin lors du soulèvement des Boxers', '本名舒庆春，生于正黄旗，父亲在义和团运动中战死卫京') },
      { year: 1924, yearEnd: 1929, place: 'London', country: 'UK', lng: -0.1276, lat: 51.5074, type: 'lived', note: loc('Lectured in Chinese at SOAS (University of London); wrote his first three novels while living in Bloomsbury', 'Enseigna le chinois à la SOAS (Université de Londres) ; écrivit ses trois premiers romans en vivant à Bloomsbury', '在伦敦大学亚非学院教授中文，旅居布卢姆斯伯里期间完成最初三部小说') },
      { year: 1930, yearEnd: 1937, place: 'Jinan', country: 'China', lng: 117.1197, lat: 36.6512, type: 'wrote', bookId: 'rickshaw', note: loc('Taught at Qilu University and Shandong University; wrote Rickshaw Boy (骆驼祥子, 1937)', 'Enseigna à l\'université Qilu et à l\'université du Shandong ; écrivit Le Pousse-pousse (骆驼祥子, 1937)', '执教于齐鲁大学与山东大学，1937年完成《骆驼祥子》') },
      { year: 1938, yearEnd: 1945, place: 'Chongqing', country: 'China', lng: 106.5516, lat: 29.5630, type: 'lived', note: loc('Fled the Japanese invasion to the wartime capital; led the All-China Resistance Association of Writers and Artists', 'Fuit l\'invasion japonaise vers la capitale de guerre ; dirigea l\'Association nationale des écrivains et artistes pour la résistance', '避日军入侵撤至陪都重庆，主持全国文艺界抗敌协会工作') },
      { year: 1946, yearEnd: 1949, place: 'New York', country: 'USA', lng: -73.9857, lat: 40.7484, type: 'lived', note: loc('Invited to the United States as a cultural envoy; translated his works into English; was preparing to stay when the PRC was founded', 'Invité aux États-Unis comme envoyé culturel ; traduisit ses œuvres en anglais ; se préparait à rester quand la République populaire fut fondée', '受邀赴美担任文化使者，亲自将作品译成英文；中华人民共和国成立时，他正准备留居美国') },
      { year: 1949, yearEnd: 1966, place: 'Beijing', country: 'China', lng: 116.3974, lat: 39.9087, type: 'wrote', bookId: 'teahouse', note: loc('Returned to the newly founded PRC; acclaimed as a national writer; wrote Teahouse (茶馆, 1957), his masterpiece mapping Beijing\'s decline across three eras', 'Rentra dans la toute nouvelle République populaire, acclamé comme écrivain national ; écrivit La Maison de thé (茶馆, 1957), chef-d\'œuvre cartographiant le déclin de Pékin sur trois époques', '回到新成立的中华人民共和国，以著名作家之身受到礼遇；写下《茶馆》（1957），以三个时代的更迭呈现北京的沧桑兴衰') },
      { year: 1966, place: 'Beijing', country: 'China', lng: 116.3974, lat: 39.9087, type: 'died', note: loc('Died during the Cultural Revolution; found drowned in Taiping Lake the following morning', 'Décédé pendant la Révolution culturelle ; retrouvé noyé dans le lac Taiping le lendemain matin', '受文化大革命影响，老舍于北京太平湖投湖自尽') },
    ],
  },
  {
    id: 'eileen-chang',
    nameKey: '张爱玲 Eileen Chang',
    name: 'Eileen Chang',
    localizedName: loc('Eileen Chang', 'Eileen Chang', '张爱玲'),
    wiki: loc('https://en.wikipedia.org/wiki/Eileen_Chang', 'https://fr.wikipedia.org/wiki/Eileen_Chang', 'https://zh.wikipedia.org/wiki/%E5%BC%A0%E7%88%B1%E7%8E%B2'),
    born: 1920,
    died: 1995,
    nationality: loc('Chinese-American', 'Sino-américaine', '中国'),
    blurb: loc(
      'Shanghai\'s most brilliant chronicler of love, money, and decline, Eileen Chang wrote her best work in her twenties under Japanese occupation. She fled Communist China for Hong Kong, then America — growing ever more reclusive until she was found alone in her Los Angeles apartment, a week after her death.',
      'Chroniqueuse la plus brillante de Shanghai pour l\'amour, l\'argent et le déclin, Eileen Chang écrivit ses meilleures œuvres dans la vingtaine sous l\'occupation japonaise. Elle fuit la Chine communiste pour Hong Kong, puis l\'Amérique — de plus en plus recluse jusqu\'à ce qu\'on la retrouve seule dans son appartement de Los Angeles, une semaine après sa mort.',
      '张爱玲是上海最才华横溢的爱情、金钱与没落书写者，她最好的作品写于二十多岁的日占岁月。她先逃至香港，再流亡美国，愈来愈遁世独居，最终在洛杉矶公寓中孤寂离世，一周后才被人发现。',
    ),
    bookIds: ['fallencity'],
    events: [
      { year: 1920, place: 'Shanghai', country: 'China', lng: 121.4737, lat: 31.2304, type: 'birth', note: loc('Born Zhang Ying into a prominent family descended from Qing officials; grandfather was Li Hongzhang\'s son-in-law', 'Née Zhang Ying dans une famille éminente descendant de fonctionnaires Qing ; grand-père, gendre de Li Hongzhang', '本名张煐，生于簪缨之家，祖父是李鸿章的女婿') },
      { year: 1939, yearEnd: 1941, place: 'Hong Kong', country: 'China', lng: 114.1694, lat: 22.3193, type: 'lived', note: loc('Studied at the University of Hong Kong; had to flee back to Shanghai after Japan attacked the city in December 1941', 'Étudia à l\'université de Hong Kong ; dut regagner Shanghai après l\'attaque japonaise de la ville en décembre 1941', '就读香港大学；1941年12月日军攻港，被迫返回上海') },
      { year: 1942, yearEnd: 1952, place: 'Shanghai', country: 'China', lng: 121.4737, lat: 31.2304, type: 'wrote', bookId: 'fallencity', note: loc('Most prolific period: wrote Love in a Fallen City (1943), The Golden Cangue (1943), and Half a Lifelong Romance under Japanese occupation and civil war', 'Période la plus prolifique : écrivit L\'Amour dans la ville déchue (1943), La Cangue d\'or (1943) et Mi-vie sous l\'occupation japonaise et la guerre civile', '创作最高峰：日占与内战期间写下《倾城之恋》（1943）、《金锁记》（1943）与《半生缘》') },
      { year: 1952, yearEnd: 1955, place: 'Hong Kong', country: 'China', lng: 114.1694, lat: 22.3193, type: 'lived', note: loc('Left Shanghai after the Communist takeover; worked as a translator for the US Information Service in Hong Kong', 'Quitta Shanghai après la prise de pouvoir communiste ; travailla comme traductrice pour l\'USIS à Hong Kong', '共产党执政后离开上海，在香港为美国新闻处从事翻译') },
      { year: 1955, yearEnd: 1972, place: 'New York', country: 'USA', lng: -73.9857, lat: 40.7484, type: 'lived', note: loc('Emigrated to the United States; attended the MacDowell Colony; lived in New York and later worked at the Center for Chinese Studies at UC Berkeley', 'Émigra aux États-Unis ; séjourna à la MacDowell Colony ; vécut à New York puis travailla au Centre d\'études chinoises de UC Berkeley', '移居美国，入住麦克道尔文艺营；旅居纽约，后在加州大学伯克利分校中国研究中心任职') },
      { year: 1972, yearEnd: 1995, place: 'Los Angeles', country: 'USA', lng: -118.2437, lat: 34.0522, type: 'died', note: loc('Settled in West Hollywood; grew increasingly reclusive, moving frequently to avoid neighbours; found dead alone in her Westwood apartment a week after passing, aged 74', 'S\'installa à West Hollywood ; devint de plus en plus recluse, déménageant souvent pour éviter les voisins ; retrouvée morte seule dans son appartement de Westwood une semaine après son décès, à 74 ans', '定居西好莱坞，日益遁世，频繁搬家以避开邻居；74岁时在西木区公寓中孤独离世，一周后方被人发现') },
    ],
  },
  {
    id: 'lu-xun',
    nameKey: '鲁迅 Lu Xun',
    name: 'Lu Xun',
    localizedName: loc('Lu Xun', 'Lu Xun', '鲁迅'),
    wiki: loc('https://en.wikipedia.org/wiki/Lu_Xun', 'https://fr.wikipedia.org/wiki/Lu_Xun', 'https://zh.wikipedia.org/wiki/%E9%B2%81%E8%BF%85'),
    born: 1881,
    died: 1936,
    nationality: loc('Chinese', 'Chinois', '中国'),
    blurb: loc(
      'Born Zhou Shuren in Shaoxing, Lu Xun trained as a doctor in Japan before abandoning medicine for the pen — convinced that literature could heal China\'s "spiritual sickness" more than medicine ever could. His short stories and essays made him the conscience of modern Chinese literature.',
      'Né Zhou Shuren à Shaoxing, Lu Xun étudia la médecine au Japon avant d\'abandonner la science pour la plume — convaincu que la littérature pouvait guérir la "maladie spirituelle" de la Chine mieux que la médecine. Ses nouvelles et essais en firent la conscience de la littérature chinoise moderne.',
      '鲁迅，原名周树人，生于绍兴。他赴日学医，却在目睹同胞麻木之后弃医从文，深信文学比医术更能疗救民族的"精神痼疾"。其小说与杂文使他成为中国现代文学的良知。',
    ),
    bookIds: ['ahq', 'callarms', 'madman', 'panghuang', 'wildgrass', 'dawnblossoms', 'oldtales'],
    events: [
      { year: 1881, place: 'Shaoxing', country: 'China', lng: 120.5810, lat: 30.0023, type: 'birth', note: loc('Born Zhou Shuren into a scholarly family in Shaoxing, Zhejiang', 'Né Zhou Shuren dans une famille lettrée à Shaoxing, Zhejiang', '生于绍兴书香门第，本名周树人') },
      { year: 1902, yearEnd: 1906, place: 'Sendai', country: 'Japan', lng: 140.8694, lat: 38.2682, type: 'lived', note: loc('Studied medicine at Sendai Medical School; a newsreel of Chinese passively watching a compatriot\'s execution turned him to literature', 'Étudia la médecine à l\'école de médecine de Sendai ; un film d\'actualité montrant des Chinois assister passivement à l\'exécution d\'un compatriote le tourna vers la littérature', '就读仙台医学专门学校；因目睹中国人麻木旁观同胞被处决的幻灯片，决心弃医从文') },
      { year: 1906, yearEnd: 1909, place: 'Tokyo', country: 'Japan', lng: 139.6917, lat: 35.6895, type: 'lived', note: loc('Remained in Tokyo translating European literature and planning literary journals', 'Resta à Tokyo pour traduire la littérature européenne et planifier des revues littéraires', '留居东京，翻译欧洲文学，筹划文学杂志') },
      { year: 1909, yearEnd: 1911, place: 'Hangzhou', country: 'China', lng: 120.1551, lat: 30.2741, type: 'lived', note: loc('Returned to China; taught at Hangzhou and Shaoxing schools', 'Rentra en Chine ; enseigna dans des écoles à Hangzhou et Shaoxing', '回国执教于杭州、绍兴各学校') },
      { year: 1912, yearEnd: 1926, place: 'Beijing', country: 'China', lng: 116.3974, lat: 39.9087, type: 'wrote', bookId: 'callarms', note: loc('Worked at the Ministry of Education; lectured at Peking University; wrote Diary of a Madman (1918), Nahan (1923), and most of his key fiction', 'Travailla au ministère de l\'Éducation ; enseigna à l\'université de Pékin ; écrivit Journal d\'un fou (1918), Cri d\'appel (1923) et la plupart de ses œuvres majeures', '任职教育部，执教北京大学；写下《狂人日记》（1918）、《呐喊》（1923）等重要作品') },
      { year: 1926, place: 'Xiamen', country: 'China', lng: 118.0894, lat: 24.4798, type: 'lived', note: loc('Briefly taught at Xiamen University after political tensions forced him from Beijing', 'Enseigna brièvement à l\'université de Xiamen après que des tensions politiques l\'eurent contraint à quitter Pékin', '因政治压力离京，短暂执教于厦门大学') },
      { year: 1927, place: 'Guangzhou', country: 'China', lng: 113.2644, lat: 23.1291, type: 'lived', note: loc('Taught at Sun Yat-sen University; witnessed the April 12 massacre and grew disillusioned with the Nationalist Party', 'Enseigna à l\'université Sun Yat-sen ; fut témoin du massacre du 12 avril et se désillusionna vis-à-vis du Parti nationaliste', '执教中山大学；亲历四一二大屠杀，对国民党彻底失望') },
      { year: 1927, yearEnd: 1936, place: 'Shanghai', country: 'China', lng: 121.4737, lat: 31.2304, type: 'wrote', bookId: 'oldtales', note: loc('Final years in Shanghai under semi-clandestine conditions; led the League of Left-Wing Writers; completed his last major works', 'Dernières années à Shanghai dans des conditions semi-clandestines ; dirigea la Ligue des écrivains de gauche ; acheva ses dernières grandes œuvres', '在上海以半隐匿方式度过晚年，领导左翼作家联盟，完成最后重要著作') },
      { year: 1936, place: 'Shanghai', country: 'China', lng: 121.4737, lat: 31.2304, type: 'died', note: loc('Died of tuberculosis, aged 55', 'Mort de la tuberculose, à 55 ans', '因肺结核逝世，享年55岁') },
    ],
  },
  {
    id: 'james-baldwin',
    nameKey: 'James Baldwin',
    name: 'James Baldwin',
    localizedName: loc('James Baldwin', undefined, '詹姆斯·鲍德温'),
    wiki: loc('https://en.wikipedia.org/wiki/James_Baldwin', 'https://fr.wikipedia.org/wiki/James_Baldwin', 'https://zh.wikipedia.org/wiki/%E8%A9%B9%E5%A7%86%E6%96%AF%C2%B7%E9%AE%91%E5%BE%B3%E6%B8%A9'),
    born: 1924,
    died: 1987,
    nationality: loc('American', 'Américain', '美国'),
    blurb: loc(
      'Baldwin left Harlem at 24 with $40 in his pocket and a one-way ticket to Paris, escaping both racism and the weight of his preacher stepfather. He spent the rest of his life crossing the Atlantic — Paris, Istanbul, Provence — writing his way toward a truth that America wasn\'t ready to hear.',
      'Baldwin quitta Harlem à 24 ans avec 40 dollars en poche et un billet simple pour Paris, fuyant à la fois le racisme et l\'emprise de son beau-père pasteur. Il passa le reste de sa vie à traverser l\'Atlantique — Paris, Istanbul, Provence — écrivant une vérité que l\'Amérique n\'était pas prête à entendre.',
      '鲍德温24岁时揣着40美元离开哈莱姆，只买了一张前往巴黎的单程票，逃离种族主义与布道者继父的阴影。此后他的一生在大西洋两岸间穿行——巴黎、伊斯坦布尔、普罗旺斯——用写作逼近一个美国尚未准备好接受的真相。',
    ),
    bookIds: ['giovannisroom'],
    events: [
      { year: 1924, place: 'Harlem', country: 'USA', lng: -73.9442, lat: 40.8116, type: 'birth', note: loc('Born in Harlem Hospital, the eldest of nine children; raised by his mother and stepfather, a storefront preacher', 'Né au Harlem Hospital, aîné de neuf enfants ; élevé par sa mère et son beau-père, un pasteur de rue', '生于哈莱姆医院，家中九兄妹中的长子，由母亲和在街头布道的继父抚养长大') },
      { year: 1944, yearEnd: 1948, place: 'Greenwich Village', country: 'USA', lng: -74.0030, lat: 40.7335, type: 'lived', note: loc('Moved to the Village; met Richard Wright, who helped him win a fellowship; began his first novel', 'S\'installa au Village ; rencontra Richard Wright, qui l\'aida à obtenir une bourse ; commença son premier roman', '移居格林尼治村；结识理查德·赖特，获其帮助赢得奖学金；开始创作第一部小说') },
      { year: 1948, yearEnd: 1956, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'lived', note: loc('Arrived with $40; settled in Saint-Germain-des-Prés; finished Go Tell It on the Mountain (1953) and Giovanni\'s Room (1956)', 'Arriva avec 40 dollars ; s\'installa à Saint-Germain-des-Prés ; acheva La Conversion (1953) et La Chambre de Giovanni (1956)', '身携40美元抵达，定居圣日耳曼德普雷；完成《向苍天呼吁》（1953）与《乔万尼的房间》（1956）') },
      { year: 1956, yearEnd: 1963, place: 'New York', country: 'USA', lng: -73.9857, lat: 40.7484, type: 'lived', note: loc('Shuttled between New York and the American South; became a central voice of the Civil Rights Movement', 'Naviguait entre New York et le Sud américain ; devint une voix centrale du mouvement des droits civiques', '往返于纽约与美国南方，成为民权运动的核心声音') },
      { year: 1961, yearEnd: 1965, place: 'Istanbul', country: 'Turkey', lng: 28.9784, lat: 41.0082, type: 'wrote', bookId: 'giovannisroom', note: loc('Made extended visits to Istanbul, staying with actor Engin Cezzar; wrote Another Country (1962) partly here', 'Effectua de longs séjours à Istanbul chez l\'acteur Engin Cezzar ; écrivit en partie Une autre terre (1962) ici', '多次长居伊斯坦布尔，下榻于演员恩金·杰扎尔家；部分创作了《另一个国家》（1962）') },
      { year: 1969, yearEnd: 1987, place: 'Saint-Paul-de-Vence', country: 'France', lng: 7.1205, lat: 43.6967, type: 'died', note: loc('Settled in a farmhouse in Provence; hosted Beauford Delaney, Nina Simone, and Maya Angelou; died of stomach cancer, aged 63', 'S\'installa dans une ferme en Provence ; accueillit Beauford Delaney, Nina Simone et Maya Angelou ; mort d\'un cancer de l\'estomac, à 63 ans', '定居普罗旺斯一座农舍，曾款待鲍福德·迪莱尼、妮娜·西蒙与马娅·安杰卢；因胃癌逝世，享年63岁') },
    ],
  },
  {
    id: 'fyodor-dostoevsky',
    nameKey: 'Fyodor Dostoevsky',
    name: 'Fyodor Dostoevsky',
    localizedName: loc('Fyodor Dostoevsky', 'Fiodor Dostoïevski', '费奥多尔·陀思妥耶夫斯基'),
    wiki: loc('https://en.wikipedia.org/wiki/Fyodor_Dostoevsky', 'https://fr.wikipedia.org/wiki/Fiodor_Dosto%C3%AFevski', 'https://zh.wikipedia.org/wiki/%E8%B4%B9%E5%A5%A5%E5%A4%9A%E5%B0%94%C2%B7%E9%99%80%E6%80%9D%E5%A6%A5%E8%80%B6%E5%A4%AB%E6%96%AF%E5%9F%BA'),
    born: 1821,
    died: 1881,
    nationality: loc('Russian', 'Russe', '俄国'),
    blurb: loc(
      'Dostoevsky was led to a mock execution in a St Petersburg square at 28, reprieved at the last moment, then sent to a Siberian prison camp for four years. The experience destroyed his health and gave him everything he needed to write.',
      'Dostoïevski fut conduit à une exécution simulée sur une place de Saint-Pétersbourg à 28 ans, gracié au dernier moment, puis envoyé dans un camp sibérien pendant quatre ans. L\'expérience détruisit sa santé et lui donna tout ce dont il avait besoin pour écrire.',
      '陀思妥耶夫斯基28岁时被押赴彼得堡广场上演"枪决"，最后一刻才获赦免，随即被流放西伯利亚服苦役四年。这段经历毁了他的健康，却给了他写作所需的全部素材。',
    ),
    bookIds: ['crimepunishment', 'brothersk'],
    events: [
      { year: 1821, place: 'Moscow', country: 'Russia', lng: 37.6173, lat: 55.7558, type: 'birth', note: loc('Born in the grounds of a charity hospital where his father was a doctor', 'Né dans l\'enceinte d\'un hôpital de bienfaisance où son père était médecin', '生于其父行医的慈善医院院内') },
      { year: 1838, yearEnd: 1844, place: 'St. Petersburg', country: 'Russia', lng: 30.3351, lat: 59.9343, type: 'lived', note: loc('Military Engineering Academy; abandoned an army career for literature after his father\'s death', 'École du génie militaire ; abandonna une carrière militaire pour la littérature après la mort de son père', '就读军事工程学院；父亲死后放弃军旅，转而追求文学') },
      { year: 1849, place: 'St. Petersburg', country: 'Russia', lng: 30.3351, lat: 59.9343, type: 'lived', note: loc('Arrested for reading a banned letter aloud at the Petrashevsky Circle; sentenced to death, reprieved seconds before execution', 'Arrêté pour avoir lu à voix haute une lettre interdite au cercle Petrashevski ; condamné à mort, gracié à quelques secondes de l\'exécution', '因在彼得拉舍夫斯基小组朗读禁书信件被捕，被判死刑，行刑前数秒获赦') },
      { year: 1850, yearEnd: 1854, place: 'Omsk', country: 'Russia', lng: 73.3686, lat: 54.9885, type: 'lived', note: loc('Four years of hard labour in a Siberian prison camp; the experience became the basis for Notes from the Dead House', 'Quatre ans de travaux forcés dans un camp sibérien ; l\'expérience devint la base des Souvenirs de la maison des morts', '西伯利亚服苦役四年，这段经历成为《死屋手记》的素材') },
      { year: 1854, yearEnd: 1859, place: 'Semipalatinsk', country: 'Kazakhstan', lng: 80.2275, lat: 50.4110, type: 'lived', note: loc('Compulsory military service in Kazakhstan; first marriage; began writing again', 'Service militaire obligatoire au Kazakhstan ; premier mariage ; reprit l\'écriture', '在哈萨克斯坦服役，初婚，重新提笔写作') },
      { year: 1862, yearEnd: 1871, place: 'Bad Homburg', country: 'Germany', lng: 8.6184, lat: 50.2269, type: 'traveled', note: loc('Several trips to Europe — Germany, London, Paris, Florence — gripped by a gambling addiction that left him perpetually in debt', 'Plusieurs voyages en Europe — Allemagne, Londres, Paris, Florence — en proie à une addiction au jeu qui le laissait perpétuellement endetté', '数次游历欧洲——德国、伦敦、巴黎、佛罗伦萨——赌瘾缠身，债台高筑') },
      { year: 1866, yearEnd: 1881, place: 'St. Petersburg', country: 'Russia', lng: 30.3351, lat: 59.9343, type: 'wrote', bookId: 'crimepunishment', note: loc('Settled finally in St Petersburg; dictated Crime and Punishment (1866) and The Brothers Karamazov (1880) — his last and greatest novel', 'S\'installa définitivement à Saint-Pétersbourg ; dicta Crime et Châtiment (1866) et Les Frères Karamazov (1880) — son dernier et plus grand roman', '最终定居彼得堡，口授完成《罪与罚》（1866）与《卡拉马佐夫兄弟》（1880）——其最后也是最伟大的小说') },
      { year: 1881, place: 'St. Petersburg', country: 'Russia', lng: 30.3351, lat: 59.9343, type: 'died', note: loc('Died of pulmonary emphysema, aged 59; 40,000 mourners attended his funeral', 'Mort d\'un emphysème pulmonaire, à 59 ans ; 40 000 personnes assistèrent à ses funérailles', '因肺气肿逝世，享年59岁，四万人出席葬礼') },
    ],
  },
  {
    id: 'marguerite-duras',
    nameKey: 'Marguerite Duras',
    name: 'Marguerite Duras',
    localizedName: loc('Marguerite Duras', undefined, '玛格丽特·杜拉斯'),
    wiki: loc('https://en.wikipedia.org/wiki/Marguerite_Duras', 'https://fr.wikipedia.org/wiki/Marguerite_Duras', 'https://zh.wikipedia.org/wiki/%E7%8E%9B%E6%A0%BC%E4%B8%BD%E7%89%B9%C2%B7%E6%9D%9C%E6%8B%89%E6%96%AF'),
    born: 1914,
    died: 1996,
    nationality: loc('French', 'Française', '法国'),
    blurb: loc(
      'Born in French Indochina, Duras spent her childhood in Saigon and the Mekong Delta before sailing to France at 17. The heat, the poverty, and a teenage affair with a wealthy Chinese man followed her all the way to a Paris apartment — and into The Lover, written sixty years later.',
      'Née en Indochine française, Duras passa son enfance à Saïgon et dans le delta du Mékong avant de partir pour la France à 17 ans. La chaleur, la pauvreté et une liaison adolescente avec un riche Chinois la suivirent jusqu\'à un appartement parisien — et dans L\'Amant, écrit soixante ans plus tard.',
      '杜拉斯生于法属印度支那，在西贡与湄公河三角洲度过童年，17岁时乘船赴法。那片土地的炎热、贫苦，以及与一位富有华人的少女情事，伴随她来到巴黎的公寓——并在六十年后化为《情人》。',
    ),
    bookIds: ['thelover'],
    events: [
      { year: 1914, place: 'Gia Định', country: 'Vietnam', lng: 106.6941, lat: 10.8185, type: 'birth', note: loc('Born near Saigon in French Indochina to two French schoolteachers', 'Née près de Saïgon en Indochine française, de deux instituteurs français', '生于法属印度支那西贡附近，父母均为法国教师') },
      { year: 1918, yearEnd: 1925, place: 'Phnom Penh', country: 'Cambodia', lng: 104.9160, lat: 11.5564, type: 'lived', note: loc('Childhood in Cambodia after her father\'s death; poverty-stricken years following her mother\'s failed land scheme', 'Enfance au Cambodge après la mort de son père ; années de pauvreté après l\'échec du projet foncier de sa mère', '父亲去世后在柬埔寨度过童年，母亲失败的土地计划令家境赤贫') },
      { year: 1925, yearEnd: 1931, place: 'Saigon', country: 'Vietnam', lng: 106.6297, lat: 10.8231, type: 'lived', note: loc('Adolescence in Saigon; the famous ferry crossing of the Mekong where she met her Chinese lover, the episode that became The Lover', 'Adolescence à Saïgon ; la célèbre traversée du Mékong en ferry où elle rencontra son amant chinois, l\'épisode qui devint L\'Amant', '在西贡度过青春期；她在湄公河渡口遭遇华人情人，此后化为《情人》中的核心场景') },
      { year: 1931, yearEnd: 1944, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'lived', note: loc('Arrived in France to study law; joined the Communist Party (1944); her husband Robert Antelme was arrested by the Gestapo', 'Arriva en France pour étudier le droit ; adhéra au Parti communiste (1944) ; son mari Robert Antelme fut arrêté par la Gestapo', '赴法学习法律；加入共产党（1944）；丈夫罗伯特·昂泰尔姆被盖世太保逮捕') },
      { year: 1950, yearEnd: 1984, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'wrote', bookId: 'thelover', note: loc('Rue Saint-Benoît apartment became a literary salon; wrote the novels and screenplays — including Hiroshima mon amour (1959) — that shaped the French New Wave', 'L\'appartement de la rue Saint-Benoît devint un salon littéraire ; écrivit les romans et scénarios — dont Hiroshima mon amour (1959) — qui façonnèrent la Nouvelle Vague française', '圣伯努瓦街公寓成为文学沙龙；创作小说与剧本——包括《广岛之恋》（1959）——深刻影响了法国新浪潮') },
      { year: 1984, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'wrote', bookId: 'thelover', note: loc('Published L\'Amant at 70, winning the Prix Goncourt; her Indochina childhood finally rendered in full', 'Publia L\'Amant à 70 ans, remportant le prix Goncourt ; son enfance indochinoise enfin pleinement rendue', '70岁出版《情人》，荣获龚古尔奖；印度支那的童年往事终于得以完整呈现') },
      { year: 1996, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'died', note: loc('Died of throat cancer, aged 81', 'Morte d\'un cancer de la gorge, à 81 ans', '因喉癌逝世，享年81岁') },
    ],
  },
  {
    id: 'pramoedya-ananta-toer',
    nameKey: 'Pramoedya Ananta Toer',
    name: 'Pramoedya Ananta Toer',
    localizedName: loc('Pramoedya Ananta Toer', undefined, '普拉姆迪亚·阿南达·杜尔'),
    wiki: loc('https://en.wikipedia.org/wiki/Pramoedya_Ananta_Toer', 'https://fr.wikipedia.org/wiki/Pramoedya_Ananta_Toer', 'https://zh.wikipedia.org/wiki/%E6%99%AE%E6%8B%89%E5%A7%86%E8%BF%AA%E4%BA%9A%C2%B7%E9%98%BF%E5%8D%97%E8%BE%BE%C2%B7%E6%9D%9C%E5%B0%94'),
    born: 1925,
    died: 2006,
    nationality: loc('Indonesian', 'Indonésien', '印度尼西亚'),
    blurb: loc(
      'Imprisoned first by the Dutch, then for fourteen years by Suharto on Buru Island, Pramoedya composed the Buru Quartet aloud to fellow prisoners — forbidden to write, he dictated each chapter from memory. His books were banned in Indonesia for most of his lifetime.',
      'Emprisonné d\'abord par les Néerlandais, puis pendant quatorze ans par Suharto sur l\'île de Buru, Pramoedya composa le Quatuor de Buru à voix haute pour ses codétenus — interdit d\'écrire, il dictait chaque chapitre de mémoire. Ses livres furent interdits en Indonésie pendant la plus grande partie de sa vie.',
      '普拉姆迪亚先后遭荷兰人与苏哈托关押，在布鲁岛服刑十四年。由于被禁止书写，他向狱友口授《布鲁四部曲》中的每一章，全凭记忆。他的书在印度尼西亚几乎被禁了一生。',
    ),
    bookIds: ['earthofmankind'],
    events: [
      { year: 1925, place: 'Blora', country: 'Indonesia', lng: 111.4152, lat: -6.9696, type: 'birth', note: loc('Born in Blora, Central Java, to a schoolteacher father active in the nationalist movement', 'Né à Blora, Java central, d\'un père instituteur engagé dans le mouvement nationaliste', '生于中爪哇布洛拉，父亲是活跃于民族主义运动的教师') },
      { year: 1945, yearEnd: 1947, place: 'Jakarta', country: 'Indonesia', lng: 106.8456, lat: -6.2088, type: 'lived', note: loc('Joined the Indonesian independence struggle; worked as a typographer and radio announcer; began writing fiction', 'Participa à la lutte pour l\'indépendance indonésienne ; travailla comme typographe et présentateur radio ; commença à écrire de la fiction', '投身印尼独立运动，担任排字工人与广播员，开始创作小说') },
      { year: 1947, yearEnd: 1949, place: 'Jakarta', country: 'Indonesia', lng: 106.8456, lat: -6.2088, type: 'lived', note: loc('Imprisoned by Dutch colonial authorities; wrote his first novels in Bukitduri Prison, Jakarta', 'Emprisonné par les autorités coloniales néerlandaises ; écrivit ses premiers romans à la prison de Bukitduri, Jakarta', '被荷兰殖民当局关押，在雅加达布吉都里监狱中完成最初几部小说') },
      { year: 1965, place: 'Jakarta', country: 'Indonesia', lng: 106.8456, lat: -6.2088, type: 'lived', note: loc('Arrested by Suharto\'s army following the September 30 coup; all his books burned or confiscated', 'Arrêté par l\'armée de Suharto après le coup du 30 septembre ; tous ses livres brûlés ou confisqués', '因九三〇政变遭苏哈托军队逮捕，所有书籍被焚毁或没收') },
      { year: 1965, yearEnd: 1979, place: 'Buru Island', country: 'Indonesia', lng: 126.5000, lat: -3.4167, type: 'wrote', bookId: 'earthofmankind', note: loc('Fourteen years on Buru Island penal colony, Maluku; forbidden to write, he dictated the Buru Quartet — including This Earth of Mankind — to fellow prisoners', 'Quatorze ans au bagne de l\'île de Buru, Moluques ; interdit d\'écrire, il dicta le Quatuor de Buru — dont Cette Terre de l\'Humanité — à ses codétenus', '在马鲁古布鲁岛囚禁地度过十四年；被禁止书写，他向狱友口授《布鲁四部曲》——包括《人世间》') },
      { year: 1979, yearEnd: 2006, place: 'Jakarta', country: 'Indonesia', lng: 106.8456, lat: -6.2088, type: 'died', note: loc('Released but placed under city arrest; the Buru Quartet finally published abroad (1980); continued writing under surveillance until his death at 81', 'Libéré mais assigné à résidence en ville ; le Quatuor de Buru finalement publié à l\'étranger (1980) ; continua d\'écrire sous surveillance jusqu\'à sa mort à 81 ans', '获释但遭城市软禁；《布鲁四部曲》终在海外出版（1980）；在监控下继续写作，直至81岁辞世') },
    ],
  },
  {
    id: 'paul-bowles',
    nameKey: 'Paul Bowles',
    name: 'Paul Bowles',
    localizedName: loc('Paul Bowles', undefined, '保罗·鲍尔斯'),
    wiki: loc('https://en.wikipedia.org/wiki/Paul_Bowles', 'https://fr.wikipedia.org/wiki/Paul_Bowles', 'https://zh.wikipedia.org/wiki/%E4%BF%9D%E7%BD%97%C2%B7%E9%B2%8D%E5%B0%94%E6%96%AF'),
    born: 1910,
    died: 1999,
    nationality: loc('American', 'Américain', '美国'),
    blurb: loc(
      'Bowles arrived in Tangier at 37 and never left. For 52 years he lived in the same Moroccan port — composing music, translating oral Moroccan storytellers into English, and writing the novels that made existential dread feel like the smell of the desert at dusk.',
      'Bowles arriva à Tanger à 37 ans et ne repartit jamais. Pendant 52 ans il vécut dans ce même port marocain — composant de la musique, traduisant des conteurs marocains oraux en anglais, et écrivant les romans qui donnèrent à l\'angoisse existentielle le parfum du désert au crépuscule.',
      '鲍尔斯37岁抵达丹吉尔，此后再未离开。他在这座摩洛哥港口住了52年——创作音乐，将摩洛哥口头故事者的作品译成英文，并写下那些让存在主义恐惧散发出黄昏沙漠气息的小说。',
    ),
    bookIds: ['shelteringsky'],
    events: [
      { year: 1910, place: 'Jamaica, Queens', country: 'USA', lng: -73.7989, lat: 40.7006, type: 'birth', note: loc('Born in Queens, New York, to a musically gifted but cold family; began composing music as a child', 'Né dans le Queens, New York, dans une famille douée musicalement mais froide ; commença à composer de la musique enfant', '生于纽约皇后区，家境富有音乐天赋却情感冷漠；幼时已开始创作音乐') },
      { year: 1929, yearEnd: 1931, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'lived', note: loc('Arrived in Paris at 19; met Gertrude Stein, who advised him to go to Morocco; studied composition with Aaron Copland', 'Arriva à Paris à 19 ans ; rencontra Gertrude Stein, qui lui conseilla d\'aller au Maroc ; étudia la composition avec Aaron Copland', '19岁抵达巴黎；结识格特鲁德·斯坦因，后者建议他前往摩洛哥；随阿龙·科普兰学习作曲') },
      { year: 1931, place: 'Tangier', country: 'Morocco', lng: -5.8100, lat: 35.7673, type: 'traveled', note: loc('First visit to Tangier on Gertrude Stein\'s advice; immediately captivated by the city', 'Premier séjour à Tanger sur les conseils de Gertrude Stein ; immédiatement captivé par la ville', '遵照斯坦因的建议初访丹吉尔，即刻被这座城市深深吸引') },
      { year: 1938, yearEnd: 1947, place: 'New York', country: 'USA', lng: -73.9857, lat: 40.7484, type: 'lived', note: loc('Composed ballet scores and Broadway incidental music; married writer Jane Auer; grew restless with America', 'Composa des partitions de ballet et des musiques de scène pour Broadway ; épousa la romancière Jane Auer ; se sentit à l\'étroit aux États-Unis', '为芭蕾和百老汇创作音乐；与作家简·奥尔成婚；对美国生活日感窒闷') },
      { year: 1947, yearEnd: 1999, place: 'Tangier', country: 'Morocco', lng: -5.8100, lat: 35.7673, type: 'wrote', bookId: 'shelteringsky', note: loc('Settled permanently in Tangier; wrote The Sheltering Sky (1949) and Let It Come Down; translated dozens of Moroccan oral storytellers; died in the Italian Hospital, aged 88', 'S\'installa définitivement à Tanger ; écrivit Un thé au Sahara (1949) et Après toi le déluge ; traduisit des dizaines de conteurs oraux marocains ; mourut à l\'hôpital italien, à 88 ans', '永久定居丹吉尔；写下《遮蔽的天空》（1949）与《让它降临》；翻译数十位摩洛哥口头故事家的作品；88岁在意大利医院辞世') },
    ],
  },
  {
    id: 'mario-vargas-llosa',
    nameKey: 'Mario Vargas Llosa',
    name: 'Mario Vargas Llosa',
    localizedName: loc('Mario Vargas Llosa', undefined, '马里奥·巴尔加斯·略萨'),
    wiki: loc('https://en.wikipedia.org/wiki/Mario_Vargas_Llosa', 'https://fr.wikipedia.org/wiki/Mario_Vargas_Llosa', 'https://zh.wikipedia.org/wiki/%E9%A9%AC%E9%87%8C%E5%A5%A5%C2%B7%E5%B7%B4%E5%B0%94%E5%8A%A0%E6%96%AF%C2%B7%E7%95%A5%E8%90%A8'),
    born: 1936,
    died: 2024,
    nationality: loc('Peruvian-Spanish', 'Péruvien-Espagnol', '秘鲁裔西班牙'),
    blurb: loc(
      'Vargas Llosa wrote his first great novels in a cold Paris garret while working the graveyard shift at a radio station, before shuttling between London, Barcelona, and Lima — and, improbably, running for president of Peru. He received the Nobel Prize in 2010.',
      'Vargas Llosa écrivit ses premiers grands romans dans un grenier glacial à Paris tout en travaillant de nuit dans une station de radio, avant de naviguer entre Londres, Barcelone et Lima — et, de façon inattendue, de briguer la présidence du Pérou. Il reçut le prix Nobel en 2010.',
      '巴尔加斯·略萨在巴黎冰冷的阁楼上写下最初几部重要小说，同时在广播电台上夜班，此后辗转于伦敦、巴塞罗那与利马之间，还出人意料地参选秘鲁总统。2010年荣获诺贝尔奖。',
    ),
    bookIds: ['auntjulia'],
    events: [
      { year: 1936, place: 'Arequipa', country: 'Peru', lng: -71.5375, lat: -16.4090, type: 'birth', note: loc('Born in Arequipa; parents separated at birth; raised largely by his maternal grandfather', 'Né à Arequipa ; parents séparés à la naissance ; élevé principalement par son grand-père maternel', '生于阿雷基帕；父母在其出生前分离；主要由外祖父抚养') },
      { year: 1945, yearEnd: 1958, place: 'Lima', country: 'Peru', lng: -77.0428, lat: -12.0464, type: 'lived', note: loc('Educated in Lima military school; entered San Marcos University aged 16; worked as a journalist; published early stories', 'Scolarisé dans une école militaire de Lima ; entra à l\'université San Marcos à 16 ans ; travailla comme journaliste ; publia ses premières nouvelles', '就读利马军校；16岁考入圣马科斯大学；担任记者，发表早期短篇小说') },
      { year: 1959, yearEnd: 1966, place: 'Paris', country: 'France', lng: 2.3522, lat: 48.8566, type: 'wrote', bookId: 'auntjulia', note: loc('Won a scholarship to Madrid then settled in Paris; worked night shifts at Agence France-Presse; wrote The Time of the Hero (1963) and The Green House (1966)', 'Obtint une bourse pour Madrid puis s\'installa à Paris ; travailla de nuit à l\'Agence France-Presse ; écrivit La Ville et les chiens (1963) et La Maison verte (1966)', '获奖学金赴马德里后定居巴黎；在法新社上夜班；写下《城市与狗》（1963）与《绿房子》（1966）') },
      { year: 1966, yearEnd: 1974, place: 'London', country: 'UK', lng: -0.1278, lat: 51.5074, type: 'lived', note: loc('Lived in London and Barcelona; taught at Queen Mary College; friendship with García Márquez ended famously with a fistfight in 1976', 'Vécut à Londres et Barcelone ; enseigna au Queen Mary College ; l\'amitié avec García Márquez se termina célèbrement par un coup de poing en 1976', '旅居伦敦与巴塞罗那；在玛丽皇后学院任教；与马尔克斯的友谊因1976年的一场拳击告终') },
      { year: 1974, yearEnd: 1993, place: 'Lima', country: 'Peru', lng: -77.0428, lat: -12.0464, type: 'lived', note: loc('Returned to Lima; ran for president in 1990, losing to Alberto Fujimori; left Peru following the defeat', 'Rentra à Lima ; se présenta à la présidence en 1990, perdant face à Alberto Fujimori ; quitta le Pérou après la défaite', '返回利马；1990年参选总统，败于阿尔贝托·藤森；落败后离开秘鲁') },
      { year: 1993, yearEnd: 2024, place: 'Madrid', country: 'Spain', lng: -3.7038, lat: 40.4168, type: 'died', note: loc('Settled in Madrid; received Spanish citizenship and the Nobel Prize for Literature (2010); died aged 88', 'S\'installa à Madrid ; obtint la nationalité espagnole et le prix Nobel de littérature (2010) ; mort à 88 ans', '定居马德里；取得西班牙国籍，荣获诺贝尔文学奖（2010）；88岁辞世') },
    ],
  },
  {
    id: 'ocean-vuong',
    nameKey: 'Ocean Vuong',
    name: 'Ocean Vuong',
    localizedName: loc('Ocean Vuong', undefined, '王鸥行'),
    wiki: loc('https://en.wikipedia.org/wiki/Ocean_Vuong', 'https://fr.wikipedia.org/wiki/Ocean_Vuong', 'https://zh.wikipedia.org/wiki/%E7%8E%8B%E9%B8%A5%E8%A1%8C'),
    born: 1988,
    nationality: loc('Vietnamese-American', 'Américain d\'origine vietnamienne', '越裔美国'),
    blurb: loc(
      'Ocean Vuong was born in Ho Chi Minh City and arrived in Hartford, Connecticut as a refugee at two years old. He did not learn to read until he was eleven. His debut novel On Earth We\'re Briefly Gorgeous is a letter from a son to a mother who cannot read it.',
      'Ocean Vuong est né à Hô Chi Minh-Ville et arriva à Hartford, Connecticut, comme réfugié à l\'âge de deux ans. Il n\'apprit à lire qu\'à onze ans. Son premier roman Sur Terre nous sommes brièvement magnifiques est une lettre d\'un fils à une mère qui ne peut pas la lire.',
      '王鸥行生于胡志明市，两岁时作为难民抵达康涅狄格州哈特福德。他直到11岁才学会阅读。其处女作长篇小说《此生，你我皆短暂灿烂》是一封儿子写给不识字母亲的信。',
    ),
    bookIds: ['brieflygorgeous'],
    events: [
      { year: 1988, place: 'Ho Chi Minh City', country: 'Vietnam', lng: 106.6297, lat: 10.8231, type: 'birth', note: loc('Born Vũ Đức Long in Ho Chi Minh City into a rice-farming family', 'Né Vũ Đức Long à Hô Chi Minh-Ville dans une famille de riziculteurs', '生于胡志明市，本名Vũ Đức Long，家族以种植水稻为生') },
      { year: 1990, place: 'Manila', country: 'Philippines', lng: 120.9842, lat: 14.5995, type: 'traveled', note: loc('Spent several months in a refugee camp in the Philippines before resettlement', 'Passa plusieurs mois dans un camp de réfugiés aux Philippines avant la réinstallation', '在菲律宾难民营生活数月后等待安置') },
      { year: 1990, yearEnd: 2007, place: 'Hartford', country: 'USA', lng: -72.6851, lat: 41.7637, type: 'lived', note: loc('Arrived as a refugee in Hartford, Connecticut; grew up speaking no English; did not learn to read until age 11; raised by his mother and grandmother', 'Arriva comme réfugié à Hartford, Connecticut ; grandit sans parler l\'anglais ; n\'apprit à lire qu\'à 11 ans ; élevé par sa mère et sa grand-mère', '以难民身份抵达康涅狄格州哈特福德，成长于不会英语的环境；11岁方学会阅读；由母亲与祖母抚养') },
      { year: 2008, yearEnd: 2012, place: 'New York', country: 'USA', lng: -73.9857, lat: 40.7484, type: 'lived', note: loc('Studied at Brooklyn\'s Pace University; immersed himself in poetry; moved to New York\'s literary circles', 'Étudia à Pace University à Brooklyn ; s\'immerge dans la poésie ; s\'intégra aux cercles littéraires new-yorkais', '就读布鲁克林佩斯大学，沉浸于诗歌创作，融入纽约文学圈') },
      { year: 2012, place: 'Northampton', country: 'USA', lng: -72.6312, lat: 42.3251, type: 'wrote', bookId: 'brieflygorgeous', note: loc('MFA at the University of Massachusetts Amherst; wrote the poems of Night Sky with Exit Wounds and began On Earth We\'re Briefly Gorgeous', 'Master en création littéraire à l\'université du Massachusetts Amherst ; écrivit les poèmes de Ciel de nuit avec des sorties de secours et commença Sur Terre nous sommes brièvement magnifiques', '在马萨诸塞大学阿默斯特分校攻读创意写作硕士；写下《以退出的伤口为星空》中的诗歌，并开始创作《此生，你我皆短暂灿烂》') },
    ],
  },
  {
    id: 'haruki-murakami',
    nameKey: 'Haruki Murakami',
    name: 'Haruki Murakami',
    localizedName: loc('Haruki Murakami', undefined, '村上春树'),
    wiki: loc('https://en.wikipedia.org/wiki/Haruki_Murakami', 'https://fr.wikipedia.org/wiki/Haruki_Murakami', 'https://zh.wikipedia.org/wiki/%E6%9D%91%E4%B8%8A%E6%98%A5%E6%A0%91'),
    born: 1949,
    nationality: loc('Japanese', 'Japonais', '日本'),
    blurb: loc(
      'Murakami ran a jazz bar in Tokyo for seven years before writing his first novel on a whim. He spent much of his forties in Europe and the United States, translating American fiction by day and writing the books that made him Japan\'s most exported literary voice.',
      'Murakami géra un bar de jazz à Tokyo pendant sept ans avant d\'écrire son premier roman sur un coup de tête. Il passa une bonne partie de sa quarantaine en Europe et aux États-Unis, traduisant la fiction américaine le jour et écrivant les livres qui firent de lui la voix littéraire la plus exportée du Japon.',
      '村上春树在东京经营爵士酒吧七年，然后突发奇想写下第一部小说。他四十多岁时大部分时间旅居欧美，白天翻译美国文学，夜晚写作，最终成为日本最受国际欢迎的文学声音。',
    ),
    bookIds: ['windupbird'],
    events: [
      { year: 1949, place: 'Kyoto', country: 'Japan', lng: 135.7681, lat: 35.0116, type: 'birth', note: loc('Born in Kyoto; raised in Kobe by a father who taught classical Japanese literature', 'Né à Kyoto ; élevé à Kobe par un père qui enseignait la littérature japonaise classique', '生于京都，在神户由教授古典日本文学的父亲抚养成人') },
      { year: 1968, yearEnd: 1974, place: 'Tokyo', country: 'Japan', lng: 139.6917, lat: 35.6895, type: 'lived', note: loc('Enrolled at Waseda University; participated in student protests; met his future wife Yoko', 'S\'inscrivit à l\'université Waseda ; participa aux manifestations étudiantes ; rencontra sa future femme Yoko', '就读早稻田大学，参与学生运动，结识日后的妻子阳子') },
      { year: 1974, yearEnd: 1981, place: 'Tokyo', country: 'Japan', lng: 139.6917, lat: 35.6895, type: 'lived', note: loc('Ran the Peter Cat jazz bar in Kokubunji; wrote his first novel Hear the Wind Sing (1979) on a whim at a baseball game', 'Géra le bar de jazz Peter Cat à Kokubunji ; écrivit son premier roman Écoute le chant du vent (1979) sur un coup de tête lors d\'un match de baseball', '在国分寺经营彼得猫爵士酒吧；1979年在棒球场突发灵感，写下处女作《且听风吟》') },
      { year: 1986, yearEnd: 1991, place: 'Athens', country: 'Greece', lng: 23.7275, lat: 37.9838, type: 'lived', note: loc('Left Japan for Europe — Athens then Rome — escaping the distraction of celebrity and seeking space to write', 'Quitta le Japon pour l\'Europe — Athènes puis Rome — pour fuir la distraction de la célébrité et chercher un espace pour écrire', '离开日本赴欧洲——先在雅典，后在罗马——逃离名人光环的喧嚣，寻找写作的静谧空间') },
      { year: 1991, yearEnd: 1995, place: 'Cambridge', country: 'USA', lng: -71.1097, lat: 42.3736, type: 'wrote', bookId: 'windupbird', note: loc('Visiting scholar at Tufts and Harvard; wrote The Wind-Up Bird Chronicle, his most ambitious novel', 'Chercheur invité à Tufts et Harvard ; écrivit Chroniques de l\'oiseau à ressort, son roman le plus ambitieux', '任塔夫茨大学与哈佛大学访问学者；写下最具雄心的小说《发条鸟年代记》') },
      { year: 1995, place: 'Tokyo', country: 'Japan', lng: 139.6917, lat: 35.6895, type: 'lived', note: loc('Returned to Japan after the Kobe earthquake and Tokyo subway sarin attack; began writing non-fiction about national trauma', 'Rentra au Japon après le séisme de Kobe et l\'attentat au sarin dans le métro de Tokyo ; commença à écrire des non-fictions sur le traumatisme national', '在神户大地震与东京地铁沙林毒气事件后回国，开始创作有关民族创伤的非虚构作品') },
    ],
  },
  {
    id: 'chinua-achebe',
    nameKey: 'Chinua Achebe',
    name: 'Chinua Achebe',
    localizedName: loc('Chinua Achebe', undefined, '钦努阿·阿契贝'),
    wiki: loc('https://en.wikipedia.org/wiki/Chinua_Achebe', 'https://fr.wikipedia.org/wiki/Chinua_Achebe', 'https://zh.wikipedia.org/wiki/%E9%92%A6%E5%8A%AA%E9%98%BF%C2%B7%E9%98%BF%E5%A5%91%E8%B4%9D'),
    born: 1930,
    died: 2013,
    nationality: loc('Nigerian', 'Nigérian', '尼日利亚'),
    blurb: loc(
      'Achebe wrote Things Fall Apart to answer the Africa of Conrad and Cary — "a dirty Europe." He went on to live through the Nigerian Civil War, survive a car crash that paralyzed him at 59, and spend his final decades teaching in New York while the country he had mapped in fiction fell into and out of crisis.',
      'Achebe écrivit Le Monde s\'effondre pour répondre à l\'Afrique de Conrad et de Cary — « une Europe souillée ». Il vécut ensuite la guerre civile nigériane, survécut à un accident de voiture qui le paralysa à 59 ans, et passa ses dernières décennies à enseigner à New York tandis que le pays qu\'il avait cartographié en fiction traversait des crises successives.',
      '阿契贝写下《瓦解》，是为了回应康拉德与卡里笔下那个"肮脏的欧洲"式的非洲。此后，他经历了尼日利亚内战，59岁时在车祸中瘫痪，最后数十年在纽约执教，而他以小说勾勒的那片土地则在动荡中沉浮。',
    ),
    bookIds: ['thingsfallapart'],
    events: [
      { year: 1930, place: 'Ogidi', country: 'Nigeria', lng: 6.7500, lat: 6.1167, type: 'birth', note: loc('Born Albert Chinualumogu Achebe in Ogidi, a large village in Igboland near Onitsha', 'Né Albert Chinualumogu Achebe à Ogidi, un grand village du pays Igbo près d\'Onitsha', '生于奥尼查附近伊格博地区大村庄奥吉迪，本名阿尔伯特·齐努阿卢莫古·阿契贝') },
      { year: 1948, yearEnd: 1953, place: 'Ibadan', country: 'Nigeria', lng: 3.9470, lat: 7.3776, type: 'lived', note: loc('Studied at University College Ibadan (then affiliated with the University of London); switched from medicine to literature', 'Étudia à l\'University College d\'Ibadan (affilié à l\'époque à l\'université de Londres) ; passa de la médecine à la littérature', '就读伊巴丹大学学院（时隶属伦敦大学）；从医学转修文学') },
      { year: 1958, yearEnd: 1966, place: 'Lagos', country: 'Nigeria', lng: 3.3792, lat: 6.5244, type: 'wrote', bookId: 'thingsfallapart', note: loc('Published Things Fall Apart (1958); worked at Nigerian Broadcasting Service in Lagos; wrote Arrow of God and No Longer at Ease', 'Publia Le Monde s\'effondre (1958) ; travailla au Nigerian Broadcasting Service à Lagos ; écrivit La Flèche de Dieu et Le Malaise', '出版《瓦解》（1958）；在拉各斯任职尼日利亚广播公司；写下《上帝之箭》与《动荡》') },
      { year: 1967, yearEnd: 1970, place: 'Enugu', country: 'Nigeria', lng: 7.4951, lat: 6.4484, type: 'lived', note: loc('Sided with Biafra during the Nigerian Civil War; served as cultural ambassador; the experience haunted his later writing', 'Prit parti pour le Biafra pendant la guerre civile nigériane ; servit comme ambassadeur culturel ; l\'expérience hanta son écriture ultérieure', '在尼日利亚内战中支持比亚法拉，担任文化大使；这段经历萦绕其后期创作') },
      { year: 1972, yearEnd: 1976, place: 'Amherst', country: 'USA', lng: -72.5199, lat: 42.3732, type: 'lived', note: loc('First stint in the United States, teaching at the University of Massachusetts Amherst', 'Premier séjour aux États-Unis, enseignant à l\'université du Massachusetts à Amherst', '首次旅居美国，在马萨诸塞大学阿默斯特分校任教') },
      { year: 1990, yearEnd: 2013, place: 'Annandale-on-Hudson', country: 'USA', lng: -73.9072, lat: 42.0257, type: 'died', note: loc('A car accident in Lagos left him paralyzed from the waist down; relocated to Bard College, New York; died in Boston during a hospital visit, aged 82', 'Un accident de voiture à Lagos le laissa paralysé des membres inférieurs ; s\'installa au Bard College, New York ; mourut à Boston lors d\'une visite à l\'hôpital, à 82 ans', '拉各斯车祸致其下身瘫痪；迁居纽约巴德学院；82岁在波士顿就医期间辞世') },
    ],
  },
  {
    id: 'virginia-woolf',
    nameKey: 'Virginia Woolf',
    name: 'Virginia Woolf',
    localizedName: loc('Virginia Woolf', undefined, '弗吉尼亚·伍尔夫'),
    wiki: loc('https://en.wikipedia.org/wiki/Virginia_Woolf', 'https://fr.wikipedia.org/wiki/Virginia_Woolf', 'https://zh.wikipedia.org/wiki/%E5%BC%97%E5%90%89%E5%B0%BC%E4%BA%9A%C2%B7%E4%BC%8D%E5%B0%94%E5%A4%AB'),
    born: 1882,
    died: 1941,
    nationality: loc('British', 'Britannique', '英国'),
    blurb: loc(
      'Woolf grew up in a Victorian Kensington household full of books and trauma, and spent her adult life remaking the English novel from a Bloomsbury drawing room and a Sussex garden. She reinvented interior time, dissolved the boundaries of consciousness on the page, and walked into the River Ouse at 59.',
      'Woolf grandit dans un foyer victorien de Kensington plein de livres et de traumatismes, et passa sa vie d\'adulte à refondre le roman anglais depuis un salon de Bloomsbury et un jardin du Sussex. Elle réinventa le temps intérieur, fit fondre les frontières de la conscience sur la page, et s\'avança dans la rivière Ouse à 59 ans.',
      '伍尔夫成长于维多利亚时代肯辛顿一个书卷与创伤并存的家庭，成年后在布卢姆斯伯里的客厅与萨塞克斯的花园中重塑英国小说。她重新发明了内心时间，在纸页上消融意识的边界，59岁时走入乌斯河。',
    ),
    bookIds: ['mrsdalloway', 'tothelighthouse'],
    events: [
      { year: 1882, place: 'Kensington', country: 'UK', lng: -0.1909, lat: 51.4994, type: 'birth', note: loc('Born Adeline Virginia Stephen in Kensington; father Leslie Stephen was a critic and mountaineer; mother Julia died when Virginia was 13', 'Née Adeline Virginia Stephen à Kensington ; son père Leslie Stephen était critique et alpiniste ; sa mère Julia mourut quand Virginia avait 13 ans', '生于肯辛顿，本名阿德琳·弗吉尼亚·史蒂芬；父亲莱斯利·史蒂芬是评论家兼登山家；母亲朱莉娅在她13岁时去世') },
      { year: 1904, yearEnd: 1912, place: 'Bloomsbury', country: 'UK', lng: -0.1190, lat: 51.5226, type: 'lived', note: loc('Moved to Gordon Square with siblings after father\'s death; the Bloomsbury Group formed around her drawing room — Keynes, Forster, Strachey, Bell', 'S\'installa à Gordon Square avec ses frères et sœurs après la mort de son père ; le groupe de Bloomsbury se forma autour de son salon — Keynes, Forster, Strachey, Bell', '父亲去世后与兄弟姐妹迁入戈登广场；布卢姆斯伯里团体在她的客厅中成形——凯恩斯、福斯特、斯特雷奇、贝尔') },
      { year: 1915, yearEnd: 1940, place: 'Rodmell', country: 'UK', lng: 0.0210, lat: 50.8686, type: 'wrote', bookId: 'mrsdalloway', note: loc('Monk\'s House in Rodmell, Sussex — her retreat and the Hogarth Press base; wrote Mrs Dalloway (1925), To the Lighthouse (1927), Orlando, and The Waves here', 'Monk\'s House à Rodmell, Sussex — sa retraite et la base de la Hogarth Press ; écrivit Mrs Dalloway (1925), La Promenade au phare (1927), Orlando et Les Vagues ici', '萨塞克斯罗德米尔的修士之屋——她的避世之所与霍加斯出版社基地；在此写下《达洛维夫人》（1925）、《到灯塔去》（1927）、《奥兰多》与《海浪》') },
      { year: 1941, place: 'Rodmell', country: 'UK', lng: 0.0210, lat: 50.8686, type: 'died', note: loc('Filled her coat pockets with stones and walked into the River Ouse; her body was found three weeks later. She was 59.', 'Remplit ses poches de manteau de pierres et s\'avança dans la rivière Ouse ; son corps fut retrouvé trois semaines plus tard. Elle avait 59 ans.', '她将口袋装满石块，走入乌斯河；三周后遗体被发现。享年59岁。') },
    ],
  },
  {
    id: 'mikhail-bulgakov',
    nameKey: 'Mikhail Bulgakov',
    name: 'Mikhail Bulgakov',
    localizedName: loc('Mikhail Bulgakov', 'Mikhaïl Boulgakov', '米哈伊尔·布尔加科夫'),
    wiki: loc('https://en.wikipedia.org/wiki/Mikhail_Bulgakov', 'https://fr.wikipedia.org/wiki/Mikha%C3%AFl_Boulgakov', 'https://zh.wikipedia.org/wiki/%E7%B1%B3%E5%93%88%E4%BC%8A%E5%B0%94%C2%B7%E5%B8%83%E5%B0%94%E5%8A%A0%E7%A7%91%E5%A4%AB'),
    born: 1891,
    died: 1940,
    nationality: loc('Soviet (Ukrainian-born)', 'Soviétique (né en Ukraine)', '苏联（生于乌克兰）'),
    blurb: loc(
      'Bulgakov\'s plays were banned, his manuscripts confiscated, and his applications to emigrate refused. He wrote to Stalin directly in 1930; Stalin called him back personally — and still wouldn\'t let him leave. The Master and Margarita, written in secret over twelve years, was published 26 years after his death.',
      'Les pièces de Boulgakov furent interdites, ses manuscrits confisqués, ses demandes d\'émigration refusées. Il écrivit directement à Staline en 1930 ; Staline lui téléphona personnellement — et refusa quand même de le laisser partir. Le Maître et Marguerite, écrit en secret pendant douze ans, fut publié 26 ans après sa mort.',
      '布尔加科夫的戏剧被禁演，手稿被没收，移居申请屡遭拒绝。1930年他亲笔致信斯大林；斯大林亲自回电——却依然不准他离开。秘密写作了十二年的《大师与玛格丽塔》，在他死后26年才得以出版。',
    ),
    bookIds: ['mastermargarita'],
    events: [
      { year: 1891, place: 'Kyiv', country: 'Ukraine', lng: 30.5238, lat: 50.4501, type: 'birth', note: loc('Born in Kyiv, then part of the Russian Empire, the eldest of seven children of a theology professor', 'Né à Kiev, alors dans l\'Empire russe, aîné de sept enfants d\'un professeur de théologie', '生于当时隶属俄罗斯帝国的基辅，是神学教授家中七个孩子中的长子') },
      { year: 1909, yearEnd: 1916, place: 'Kyiv', country: 'Ukraine', lng: 30.5238, lat: 50.4501, type: 'lived', note: loc('Studied medicine at Kyiv Imperial University; graduated as a doctor; served briefly as a field doctor in World War I', 'Étudia la médecine à l\'université impériale de Kiev ; obtint son diplôme de médecin ; servit brièvement comme médecin de campagne pendant la Première Guerre mondiale', '就读基辅皇家大学医学院；取得医师资格；短暂担任一战野战军医') },
      { year: 1916, yearEnd: 1920, place: 'Smolensk Oblast', country: 'Russia', lng: 33.0000, lat: 55.0000, type: 'lived', note: loc('Rural doctor in the Smolensk countryside; the isolated postings became the basis for A Country Doctor\'s Notebook', 'Médecin rural dans la campagne de Smolensk ; les postes isolés devinrent la base du Journal d\'un jeune médecin de campagne', '在斯摩棱斯克乡村担任乡村医生；这段孤寂的从医经历成为《乡村医生手记》的素材') },
      { year: 1921, yearEnd: 1940, place: 'Moscow', country: 'Russia', lng: 37.6173, lat: 55.7558, type: 'wrote', bookId: 'mastermargarita', note: loc('Settled in Moscow; his plays staged and then banned; wrote The Master and Margarita in secret 1928–1940; burned and rewrote the manuscript multiple times; died of kidney failure, aged 48', 'S\'installa à Moscou ; ses pièces montées puis interdites ; écrivit Le Maître et Marguerite en secret de 1928 à 1940 ; brûla et réécrivit plusieurs fois le manuscrit ; mort d\'une insuffisance rénale, à 48 ans', '定居莫斯科；戏剧几经上演旋遭禁演；1928—1940年间秘密创作《大师与玛格丽塔》，数度焚稿重写；48岁因肾衰竭辞世') },
    ],
  },
  {
    id: 'franz-kafka',
    nameKey: 'Franz Kafka',
    name: 'Franz Kafka',
    localizedName: loc('Franz Kafka', undefined, '弗兰兹·卡夫卡'),
    wiki: loc('https://en.wikipedia.org/wiki/Franz_Kafka', 'https://fr.wikipedia.org/wiki/Franz_Kafka', 'https://zh.wikipedia.org/wiki/%E5%BC%97%E5%85%B0%E5%85%B9%C2%B7%E5%8D%A1%E5%A4%AB%E5%8D%A1'),
    born: 1883,
    died: 1924,
    nationality: loc('Bohemian (Austro-Hungarian)', 'Bohémien (Autriche-Hongrie)', '波西米亚（奥匈帝国）'),
    blurb: loc(
      'Kafka spent almost his entire life within a few city blocks of his birthplace in Prague, working insurance by day and writing by night. He instructed his friend Max Brod to burn all his manuscripts after his death. Brod published them instead.',
      'Kafka passa presque toute sa vie dans quelques pâtés de maisons de son lieu de naissance à Prague, travaillant dans les assurances le jour et écrivant la nuit. Il demanda à son ami Max Brod de brûler tous ses manuscrits après sa mort. Brod les publia à la place.',
      '卡夫卡几乎一生都在布拉格出生地附近方圆几条街内度过，白天做保险工作，夜间写作。他嘱咐好友马克斯·布罗德在他身后烧掉所有手稿。布罗德却将它们出版了。',
    ),
    bookIds: ['trial'],
    events: [
      { year: 1883, place: 'Prague', country: 'Czech Republic', lng: 14.4213, lat: 50.0880, type: 'birth', note: loc('Born into a German-speaking Jewish merchant family in the Old Town of Prague, Austro-Hungarian Empire', 'Né dans une famille de marchands juifs de langue allemande dans la vieille ville de Prague, Empire austro-hongrois', '生于奥匈帝国布拉格老城区的德语犹太商人家庭') },
      { year: 1901, yearEnd: 1906, place: 'Prague', country: 'Czech Republic', lng: 14.4213, lat: 50.0880, type: 'lived', note: loc('Studied law at the German Karl-Ferdinand University in Prague; doctorate in law 1906', 'Étudia le droit à l\'université allemande Karl-Ferdinand de Prague ; doctorat en droit en 1906', '在布拉格德国卡尔-斐迪南大学攻读法律；1906年获法学博士') },
      { year: 1907, yearEnd: 1922, place: 'Prague', country: 'Czech Republic', lng: 14.4378, lat: 50.0755, type: 'wrote', bookId: 'trial', note: loc('Worked at the Workers\' Accident Insurance Institute by day; wrote The Metamorphosis (1915), The Trial (1914–15, unpublished), and The Castle at night — almost all in Prague', 'Travailla à l\'Institut d\'assurance contre les accidents du travail le jour ; écrivit La Métamorphose (1915), Le Procès (1914–15, inédit) et Le Château la nuit — presque tout à Prague', '白天在工伤事故保险局任职，夜间写下《变形记》（1915）、《审判》（1914—15，未刊）与《城堡》——几乎全在布拉格完成') },
      { year: 1913, place: 'Berlin', country: 'Germany', lng: 13.4050, lat: 52.5200, type: 'traveled', note: loc('Met his fiancée Felice Bauer in Berlin — engaged and broken off twice; their correspondence spanned five years and thousands of letters', 'Rencontra sa fiancée Felice Bauer à Berlin — fiançailles rompues deux fois ; leur correspondance s\'étala sur cinq ans et des milliers de lettres', '在柏林结识未婚妻菲莉斯·鲍尔——两次订婚两次解除；两人通信长达五年，书信数以千计') },
      { year: 1924, place: 'Kierling', country: 'Austria', lng: 16.2980, lat: 48.3363, type: 'died', note: loc('Died of tuberculosis at the Kierling Sanatorium near Vienna, aged 40; asked Brod to burn all manuscripts; Brod published The Trial, The Castle, and Amerika instead', 'Mort de la tuberculose au sanatorium de Kierling près de Vienne, à 40 ans ; demanda à Brod de brûler tous ses manuscrits ; Brod publia Le Procès, Le Château et Amerika à la place', '因肺结核在维也纳附近基尔灵疗养院辞世，享年40岁；嘱托布罗德焚毁所有手稿；布罗德却将《审判》《城堡》与《美国》悉数出版') },
    ],
  },
];

/** Set of nameKeys for quick lookup in BookCard */
export const AUTHOR_NAME_KEYS = new Set(AUTHORS.map(a => a.nameKey));

/** Find an author by their URL slug */
export function findAuthorById(id: string): Author | undefined {
  return AUTHORS.find(a => a.id === id);
}

/** Find an author by their book.author nameKey */
export function findAuthorByNameKey(nameKey: string): Author | undefined {
  return AUTHORS.find(a => a.nameKey === nameKey);
}
