import type { Book } from './types';

export const BOOKS: Book[] = [
  // ============================================================
  // Multi-language books (available under more than one filter)
  // ============================================================
  {
    id: 'kiterunner',
    author: 'Khaled Hosseini',
    year: 2003,
    place: 'Kabul',
    country: 'Afghanistan',
    lng: 69.05, lat: 34.50,
    tier: 1,
    relation: 'set',
    genre: 'Historical Fiction',
    rating: 4.36, pages: 372,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'The Kite Runner',
      Chinese: '追风筝的人',
    },
    blurbs: {
      English: 'A boy in Kabul betrays his closest friend and spends a lifetime trying to atone.',
      Chinese: '喀布尔的少年背叛了挚友，多年后远赴故乡寻求救赎。',
    },
  },
  {
    id: 'thousandsuns',
    author: 'Khaled Hosseini',
    year: 2007,
    place: 'Kabul',
    country: 'Afghanistan',
    lng: 69.35, lat: 34.62,
    tier: 1,
    relation: 'set',
    genre: 'Historical Fiction',
    rating: 4.41, pages: 372,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'A Thousand Splendid Suns',
      Chinese: '灿烂千阳',
    },
    blurbs: {
      English: 'Two Afghan women bound together through decades of war and Taliban rule.',
      Chinese: '两位阿富汗女性在战争与塔利班统治下命运交织的故事。',
    },
  },
  {
    id: 'istanbul3',
    author: 'Bettany Hughes',
    year: 2017,
    place: 'Istanbul',
    country: 'Türkiye',
    lng: 28.9784, lat: 41.0082,
    tier: 1,
    relation: 'about',
    genre: 'History',
    rating: 4.03, pages: 480,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'Istanbul: A Tale of Three Cities',
      Chinese: '伊斯坦布尔三城记',
    },
    blurbs: {
      English: 'A sweeping history of Istanbul through its incarnations as Byzantium, Constantinople, and Istanbul.',
      Chinese: '从拜占庭、君士坦丁堡到伊斯坦布尔，一座城市跨越三个文明的恢宏史诗。',
    },
  },
  {
    id: 'crusoe',
    author: 'Daniel Defoe',
    year: 1719,
    place: 'Castaway Island',
    country: 'Caribbean (near Trinidad)',
    lng: -62.0, lat: 10.5,
    tier: 1,
    relation: 'set',
    genre: 'Adventure Fiction',
    rating: 3.69, pages: 320,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'Robinson Crusoe',
      Chinese: '鲁滨逊漂流记',
    },
    blurbs: {
      English: 'A shipwrecked sailor survives twenty-eight years alone on a remote Caribbean island.',
      Chinese: '一名遭遇海难的水手在加勒比海荒岛上独自生存二十八年。',
    },
  },
  {
    id: 'leagues20k',
    author: 'Jules Verne',
    year: 1870,
    place: 'Pacific Ocean',
    country: 'the high seas',
    lng: -160.0, lat: 0.0,
    tier: 1,
    relation: 'set',
    genre: 'Science Fiction',
    rating: 3.90, pages: 380,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'Twenty Thousand Leagues Under the Sea',
      Chinese: '海底两万里',
    },
    blurbs: {
      English: 'Aboard the mysterious submarine Nautilus, a voyage across the world\'s oceans with Captain Nemo.',
      Chinese: '搭乘神秘的鹦鹉螺号潜艇，与尼摩船长一同穿越世界各大洋的深海冒险。',
    },
  },

  {
    id: 'cityofgod',
    author: 'Paulo Lins',
    year: 1997,
    place: 'Cidade de Deus, Rio de Janeiro',
    country: 'Brazil',
    lng: -43.37, lat: -22.94,
    tier: 2,
    relation: 'set',
    genre: 'Literary Fiction',
    rating: 3.94, pages: 550,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'City of God',
      Chinese: '上帝之城',
    },
    blurbs: {
      English: 'Two decades of drug lords, gangs, and survival in a Rio de Janeiro housing project.',
      Chinese: '里约热内卢贫民窟二十年间毒枭、帮派与生存的残酷史诗。',
    },
  },
  {
    id: 'orientexpress',
    author: 'Agatha Christie',
    year: 1934,
    place: 'Orient Express, Yugoslavia',
    country: 'Serbia',
    lng: 20.46, lat: 44.82,
    tier: 1,
    relation: 'set',
    genre: 'Mystery',
    rating: 4.15, pages: 256,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'Murder on the Orient Express',
      Chinese: '东方列车杀人案',
    },
    blurbs: {
      English: 'Hercule Poirot investigates a murder aboard a snowbound luxury train crossing Yugoslavia.',
      Chinese: '波洛在被大雪困住的东方列车上，侦破一桩错综复杂的密室谋杀案。',
    },
  },
  {
    id: 'andthentherewerenone',
    author: 'Agatha Christie',
    year: 1939,
    place: 'Soldier Island, Devon',
    country: 'United Kingdom',
    lng: -3.97, lat: 50.31,
    tier: 1,
    relation: 'set',
    genre: 'Mystery',
    rating: 4.27, pages: 300,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'And Then There Were None',
      Chinese: '无人生还',
    },
    blurbs: {
      English: 'Ten strangers lured to a remote island begin dying one by one, with no killer in sight.',
      Chinese: '十位素不相识的人受邀来到孤岛，却一个接一个离奇死去，凶手竟无处可寻。',
    },
  },
  {
    id: 'likewater',
    author: 'Laura Esquivel',
    year: 1989,
    place: 'Coahuila, northern Mexico',
    country: 'Mexico',
    lng: -100.52, lat: 28.70,
    tier: 1,
    relation: 'set',
    genre: 'Magical Realism',
    rating: 3.87, pages: 245,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'Like Water for Chocolate',
      Chinese: '恰似水之于巧克力',
    },
    blurbs: {
      English: 'A Mexican woman forbidden to marry pours her longing into her cooking, which magically affects all who eat it.',
      Chinese: '一个被禁止出嫁的墨西哥女孩，将毕生情感倾注于烹饪，令食者感同身受。',
    },
  },
  {
    id: 'hundredyears',
    author: 'Gabriel García Márquez',
    year: 1967,
    place: 'Macondo (Aracataca)',
    country: 'Colombia',
    lng: -74.19, lat: 10.59,
    tier: 1,
    relation: 'set',
    genre: 'Magical Realism',
    rating: 4.04, pages: 417,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'One Hundred Years of Solitude',
      Chinese: '百年孤独',
    },
    blurbs: {
      English: 'Seven generations of the Buendía family in the magical, doomed town of Macondo.',
      Chinese: '布恩迪亚家族七代人的兴衰，与那座充满奇幻与宿命的小镇马孔多。',
    },
  },
  {
    id: 'cholera',
    author: 'Gabriel García Márquez',
    year: 1985,
    place: 'Cartagena',
    country: 'Colombia',
    lng: -75.51, lat: 10.40,
    tier: 1,
    relation: 'set',
    genre: 'Literary Fiction',
    rating: 3.90, pages: 348,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'Love in the Time of Cholera',
      Chinese: '霍乱时期的爱情',
    },
    blurbs: {
      English: 'A man waits fifty-one years, nine months, and four days for the woman he loves.',
      Chinese: '一个男人痴痴等待了五十一年九个月零四天，只为与挚爱重续前缘。',
    },
  },
  {
    id: 'gatsby',
    author: 'F. Scott Fitzgerald',
    year: 1925,
    place: 'West Egg, Long Island',
    country: 'USA',
    lng: -73.70, lat: 40.80,
    tier: 1,
    relation: 'set',
    genre: 'Literary Fiction',
    rating: 3.93, pages: 180,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'The Great Gatsby',
      Chinese: '了不起的盖茨比',
    },
    blurbs: {
      English: 'A mysterious millionaire\'s obsession with a married woman across the bay in Jazz Age Long Island.',
      Chinese: '爵士时代的长岛，一个神秘百万富翁对湾对岸那个已婚女人无法自拔的痴迷。',
    },
  },
  {
    id: 'empiresun',
    author: 'J.G. Ballard',
    year: 1984,
    place: 'Shanghai (Lunghua Camp)',
    country: 'China',
    lng: 121.48, lat: 31.15,
    tier: 1,
    relation: 'set',
    genre: 'Historical Fiction',
    rating: 4.06, pages: 279,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'Empire of the Sun',
      Chinese: '太阳帝国',
    },
    blurbs: {
      English: 'An English boy survives the Japanese occupation of Shanghai alone, interned in a WWII camp.',
      Chinese: '二战期间，一个英国男孩在日军占领的上海独自求生，被关押在龙华集中营中。',
    },
  },

  {
    id: 'gardenevening',
    author: 'Tan Twan Eng',
    year: 2012,
    place: 'Cameron Highlands',
    country: 'Malaysia',
    lng: 101.3747, lat: 4.4726,
    tier: 2,
    relation: 'set',
    genre: 'Historical Fiction',
    rating: 4.03, pages: 321,
    languages: ['English', 'Chinese', 'French'],
    titles: {
      English: 'The Garden of Evening Mists',
      Chinese: '晚雾花园',
      French: 'Le Jardin des brumes du soir',
    },
    blurbs: {
      English: 'A Malayan war crimes judge retreats to a misty highland tea garden, where memories of wartime imprisonment and a Japanese master gardener slowly unravel.',
      Chinese: '一位马来亚战争罪行法官隐居于云雾缭绕的高地茶园，战时囚禁与日本园艺师的记忆在此缓缓浮现。',
      French: 'Une juge malaisienne se retire dans un jardin de thé brumeux des hauts plateaux, où remontent des souvenirs de captivité et d\'un maître jardinier japonais.',
    },
  },
  {
    id: 'ficciones',
    author: 'Jorge Luis Borges',
    year: 1944,
    place: 'Buenos Aires',
    country: 'Argentina',
    lng: -58.3816, lat: -34.6037,
    tier: 1,
    relation: 'about',
    genre: 'Short Stories',
    rating: 4.37, pages: 174,
    languages: ['English', 'Chinese', 'French'],
    titles: {
      English: 'Ficciones',
      Chinese: '虚构集',
      French: 'Fictions',
    },
    blurbs: {
      English: 'Labyrinths, infinite libraries, and secret societies — Borges reinvents the short story as pure philosophical puzzle.',
      Chinese: '迷宫、无尽的图书馆与秘密社会——博尔赫斯将短篇小说重塑为纯粹的哲学谜题。',
      French: 'Labyrinthes, bibliothèques infinies et sociétés secrètes — Borges réinvente la nouvelle comme énigme philosophique pure.',
    },
  },
  {
    id: 'butterflies',
    author: 'Julia Alvarez',
    year: 1994,
    place: 'Santiago de los Caballeros',
    country: 'Dominican Republic',
    lng: -70.6926, lat: 19.4517,
    tier: 2,
    relation: 'set',
    genre: 'Historical Fiction',
    rating: 4.31, pages: 325,
    languages: ['English', 'Chinese', 'French'],
    titles: {
      English: 'In the Time of the Butterflies',
      Chinese: '蝴蝶时代',
      French: 'Au temps des papillons',
    },
    blurbs: {
      English: 'The four Mirabal sisters resist the Trujillo dictatorship in 1950s Dominican Republic — three of them dying for it.',
      Chinese: '四位米拉贝尔姐妹在1950年代多米尼加共和国抵抗特鲁希略独裁政权，其中三人为此献出生命。',
      French: 'Les quatre sœurs Mirabal résistent à la dictature Trujillo dans la République dominicaine des années 1950, trois d\'entre elles y laissant leur vie.',
    },
  },

  {
    id: 'trial',
    author: 'Franz Kafka',
    year: 1925,
    place: 'Prague',
    country: 'Czech Republic',
    lng: 14.4378, lat: 50.0755,
    tier: 1,
    relation: 'set',
    genre: 'Philosophical Fiction',
    rating: 4.04, pages: 176,
    languages: ['English', 'Chinese', 'French'],
    titles: { English: 'The Trial', Chinese: '审判', French: 'Le Procès' },
    blurbs: {
      English: 'Josef K. is arrested one morning without explanation and subjected to a shadowy, incomprehensible justice system.',
      Chinese: '银行职员约瑟夫·K莫名被捕，陷入一场荒诞而无解的法律迷宫，永远无从知晓自己的罪名。',
      French: 'Josef K. est arrêté un matin sans explication et soumis à un système judiciaire opaque dont il ne comprendra jamais la logique.',
    },
  },
  {
    id: 'lightnessbeing',
    author: 'Milan Kundera',
    year: 1984,
    place: 'Prague',
    country: 'Czech Republic',
    lng: 14.4020, lat: 50.0880,
    tier: 1,
    relation: 'set',
    genre: 'Philosophical Fiction',
    rating: 4.19, pages: 314,
    languages: ['English', 'Chinese', 'French'],
    titles: {
      English: 'The Unbearable Lightness of Being',
      Chinese: '不能承受的生命之轻',
      French: 'L\'Insoutenable légèreté de l\'être',
    },
    blurbs: {
      English: 'Four lives entangled in love and politics during the Prague Spring and its Soviet suppression.',
      Chinese: '布拉格之春的政治动荡中，四个人的爱情与命运交织，轻与重的哲学命题贯穿其间。',
      French: 'Quatre vies entrelacées dans l\'amour et la politique au moment du Printemps de Prague et de son écrasement soviétique.',
    },
  },
  {
    id: 'tindrum',
    author: 'Günter Grass',
    year: 1959,
    place: 'Danzig (Gdańsk)',
    country: 'Poland',
    lng: 18.6466, lat: 54.3520,
    tier: 2,
    relation: 'set',
    genre: 'Historical Fiction',
    rating: 3.98, pages: 600,
    languages: ['English', 'French'],
    titles: { English: 'The Tin Drum', French: 'Le Tambour' },
    blurbs: {
      English: 'A boy born in Danzig decides at age three to stop growing and witnesses the rise of Nazism through the beat of his tin drum.',
      French: 'Un enfant né à Dantzig décide à trois ans de ne plus grandir et témoigne de la montée du nazisme par les battements de son tambour.',
    },
  },
  {
    id: 'fatelessness',
    author: 'Imre Kertész',
    year: 1975,
    place: 'Budapest',
    country: 'Hungary',
    lng: 19.0402, lat: 47.4979,
    tier: 2,
    relation: 'set',
    genre: 'Historical Fiction',
    rating: 4.22, pages: 262,
    languages: ['English', 'French'],
    titles: { English: 'Fatelessness', French: 'Être sans destin' },
    blurbs: {
      English: 'A Budapest teenager is deported to Auschwitz and Buchenwald, recounting the Holocaust with devastating matter-of-factness.',
      French: 'Un adolescent de Budapest déporté à Auschwitz et Buchenwald raconte la Shoah avec une impassibilité bouleversante.',
    },
  },
  {
    id: 'bridgedrina',
    author: 'Ivo Andrić',
    year: 1945,
    place: 'Višegrad',
    country: 'Bosnia and Herzegovina',
    lng: 19.2947, lat: 43.7822,
    tier: 2,
    relation: 'set',
    genre: 'Historical Fiction',
    rating: 4.23, pages: 352,
    languages: ['English', 'French'],
    titles: { English: 'The Bridge on the Drina', French: 'Le Pont sur la Drina' },
    blurbs: {
      English: 'Four centuries of Bosnian life unfold around a sixteenth-century Ottoman bridge spanning the Drina river.',
      French: 'Quatre siècles de vie bosniaque se déroulent autour d\'un pont ottoman du XVIe siècle enjambant la Drina.',
    },
  },

  {
    id: 'auntjulia',
    author: 'Mario Vargas Llosa',
    year: 1977,
    place: 'Lima',
    country: 'Peru',
    lng: -77.0428, lat: -12.0464,
    tier: 2,
    relation: 'set',
    genre: 'Literary Fiction',
    rating: 4.05, pages: 374,
    languages: ['English', 'French'],
    titles: { English: 'Aunt Julia and the Scriptwriter', French: 'La Tante Julia et le scribouillard' },
    blurbs: {
      English: 'A young law student in Lima falls for his aunt by marriage while a flamboyant soap opera writer takes the city\'s airwaves by storm.',
      French: 'Un jeune étudiant en droit à Lima tombe amoureux de sa tante par alliance tandis qu\'un scénariste flamboyant conquiert les ondes de la ville.',
    },
  },
  {
    id: 'gabriela',
    author: 'Jorge Amado',
    year: 1958,
    place: 'Ilhéus, Bahia',
    country: 'Brazil',
    lng: -39.0394, lat: -14.7896,
    tier: 2,
    relation: 'set',
    genre: 'Literary Fiction',
    rating: 4.00, pages: 425,
    languages: ['English', 'French'],
    titles: { English: 'Gabriela, Clove and Cinnamon', French: 'Gabriela, girofle et cannelle' },
    blurbs: {
      English: 'A dark-skinned migrant woman becomes the beloved of a bar owner in a 1920s cacao boom town in coastal Bahia.',
      French: 'Une migrante métisse devient la bien-aimée d\'un propriétaire de bar dans une ville côtière brésilienne en plein boom du cacao.',
    },
  },
  {
    id: 'generallabyrinth',
    author: 'Gabriel García Márquez',
    year: 1989,
    place: 'Magdalena River',
    country: 'Colombia',
    lng: -74.8600, lat: 9.2400,
    tier: 2,
    relation: 'set',
    genre: 'Historical Fiction',
    rating: 3.89, pages: 285,
    languages: ['English', 'French', 'Chinese'],
    titles: {
      English: 'The General in His Labyrinth',
      French: 'Le Général dans son labyrinthe',
      Chinese: '迷宫中的将军',
    },
    blurbs: {
      English: 'Simón Bolívar\'s final journey down the Magdalena River — a feverish meditation on glory, decline, and the illusions of power.',
      French: 'Le dernier voyage de Simón Bolívar sur le Magdalena — une méditation fiévreuse sur la gloire, le déclin et les illusions du pouvoir.',
      Chinese: '西蒙·玻利瓦尔生命最后的马格达莱纳河之旅，一首关于荣耀、衰落与权力幻觉的热烈挽歌。',
    },
  },
  {
    id: 'shelteringsky',
    author: 'Paul Bowles',
    year: 1949,
    place: 'Tangier',
    country: 'Morocco',
    lng: -5.8133, lat: 35.7595,
    tier: 1,
    relation: 'set',
    genre: 'Literary Fiction',
    rating: 3.92, pages: 335,
    languages: ['English', 'French'],
    titles: { English: 'The Sheltering Sky', French: 'Un thé au Sahara' },
    blurbs: {
      English: 'An American couple drifts through Morocco and deep into the Sahara, each step further from civilization and from each other.',
      French: 'Un couple américain dérive à travers le Maroc et au cœur du Sahara, s\'éloignant à chaque étape de la civilisation et l\'un de l\'autre.',
    },
  },

  {
    id: 'alchemist',
    author: 'Paulo Coelho',
    year: 1988,
    place: 'Giza (Egyptian Pyramids)',
    country: 'Egypt',
    lng: 31.1342, lat: 29.9792,
    tier: 1,
    relation: 'set',
    genre: 'Philosophical Fiction',
    rating: 3.87, pages: 163,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'The Alchemist',
      Chinese: '牧羊少年奇幻之旅',
    },
    blurbs: {
      English: 'A young Andalusian shepherd follows omens across the Sahara to Egypt in pursuit of his personal legend.',
      Chinese: '安达卢西亚少年牧羊人聆听心灵之声，穿越撒哈拉，追寻藏于金字塔旁的宝藏与人生传奇。',
    },
  },
  {
    id: 'thingsfallapart',
    author: 'Chinua Achebe',
    year: 1958,
    place: 'Umuofia (Igboland)',
    country: 'Nigeria',
    lng: 6.8833, lat: 6.1167,
    tier: 1,
    relation: 'set',
    genre: 'Literary Fiction',
    rating: 3.96, pages: 209,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'Things Fall Apart',
      Chinese: '瓦解',
    },
    blurbs: {
      English: 'The proud Igbo warrior Okonkwo struggles to hold his world together as British colonialism dismantles everything he values.',
      Chinese: '骄傲的伊博族勇士奥孔克沃，眼睁睁看着英国殖民浪潮将他所珍视的一切土崩瓦解。',
    },
  },

  // ============================================================
  // English (19) — Kite Runner is in the multi-language section
  // ============================================================
  // Tier 1
  { id:'shogun', author:'James Clavell', year:1975, place:'Osaka (feudal)', country:'Japan', lng:135.47, lat:34.65, tier:1, relation:'set', genre:'Historical Fiction', rating:4.40, pages:1210,
    languages:['English'], titles:{English:'Shōgun'}, blurbs:{English:'An English navigator shipwrecked in feudal Japan becomes embroiled in a warlord\'s bid for power.'} },
  { id:'balzac', author:'Dai Sijie', year:2000, place:'Phoenix Mountain, Sichuan', country:'China', lng:104.50, lat:29.00, tier:2, relation:'set', genre:'Literary Fiction', rating:3.74, pages:197,
    languages:['English'], titles:{English:'Balzac and the Little Chinese Seamstress'}, blurbs:{English:'Two city boys sent to a remote mountain for re-education discover a suitcase of forbidden Western novels.'} },
  { id:'mockingbird', author:'Harper Lee', year:1960, place:'Monroeville, AL', country:'USA', lng:-87.3247, lat:31.5269, tier:1, relation:'set', genre:'Literary Fiction', rating:4.27, pages:281,
    languages:['English', 'Chinese'], titles:{English:'To Kill a Mockingbird', Chinese:'杀死一只知更鸟'}, blurbs:{English:'Childhood and injustice in a small Alabama town.', Chinese:'阿拉巴马小镇的童年岁月，与一场关于种族与正义的审判。'} },
  { id:'nineteen84', author:'George Orwell', year:1949, place:'London', country:'UK', lng:-0.1276, lat:51.5074, tier:1, relation:'set', genre:'Dystopian Fiction', rating:4.19, pages:328,
    languages:['English'], titles:{English:'1984'}, blurbs:{English:'A man crushed under a total surveillance state.'} },
  { id:'eden', author:'John Steinbeck', year:1952, place:'Salinas, CA', country:'USA', lng:-121.6555, lat:36.6777, tier:1, relation:'set', genre:'Literary Fiction', rating:4.39, pages:601,
    languages:['English'], titles:{English:'East of Eden'}, blurbs:{English:'Two families and the Cain-and-Abel saga in the Salinas Valley.'} },
  { id:'beloved', author:'Toni Morrison', year:1987, place:'Cincinnati, OH', country:'USA', lng:-84.5120, lat:39.1031, tier:1, relation:'set', genre:'Historical Fiction', rating:4.01, pages:275,
    languages:['English'], titles:{English:'Beloved'}, blurbs:{English:'The haunting of slavery\'s aftermath at 124 Bluestone Road.'} },
  { id:'remainsday', author:'Kazuo Ishiguro', year:1989, place:'Oxfordshire', country:'UK', lng:-1.2577, lat:51.7520, tier:2, relation:'set', genre:'Literary Fiction', rating:4.13, pages:258,
    languages:['English'], titles:{English:'The Remains of the Day'}, blurbs:{English:'A butler\'s quiet reckoning with the years he served.'} },
  { id:'smallthings', author:'Arundhati Roy', year:1997, place:'Kochi (Kerala)', country:'India', lng:76.2673, lat:9.9312, tier:1, relation:'set', genre:'Literary Fiction', rating:4.05, pages:321,
    languages:['English'], titles:{English:'The God of Small Things'}, blurbs:{English:'Twins and a forbidden love in the Kerala backwaters.'} },
  { id:'crybcountry', author:'Alan Paton', year:1948, place:'Johannesburg', country:'South Africa', lng:28.0473, lat:-26.2041, tier:1, relation:'set', genre:'Literary Fiction', rating:4.19, pages:312,
    languages:['English'], titles:{English:'Cry, the Beloved Country'}, blurbs:{English:'A Zulu pastor travels from a rural valley to Johannesburg to find his lost son, and discovers a broken land.'} },
  { id:'greengables', author:'L.M. Montgomery', year:1908, place:'Prince Edward Island', country:'Canada', lng:-63.39, lat:46.50, tier:1, relation:'set', genre:'Coming-of-Age', rating:4.19, pages:320,
    languages:['English'], titles:{English:'Anne of Green Gables'}, blurbs:{English:'A spirited orphan girl finds a home and herself on a red-earthed island farm in rural Canada.'} },
  { id:'cloudstreet', author:'Tim Winton', year:1991, place:'Perth', country:'Australia', lng:115.86, lat:-31.95, tier:1, relation:'set', genre:'Literary Fiction', rating:4.28, pages:424,
    languages:['English'], titles:{English:'Cloudstreet'}, blurbs:{English:'Two working-class families thrown together under one roof in postwar Perth across twenty years of makeshift life.'} },
  // Tier 2
  { id:'littlelife', author:'Hanya Yanagihara', year:2015, place:'New York', country:'USA', lng:-73.9857, lat:40.7484, tier:2, relation:'set', genre:'Literary Fiction', rating:4.32, pages:720,
    languages:['English'], titles:{English:'A Little Life'}, blurbs:{English:'Four friends in Manhattan over decades of love and damage.'} },
  { id:'lonesomedove', author:'Larry McMurtry', year:1985, place:'Lonesome Dove, TX', country:'USA', lng:-99.00, lat:26.40, tier:2, relation:'set', genre:'Western', rating:4.55, pages:945,
    languages:['English'], titles:{English:'Lonesome Dove'}, blurbs:{English:'Aging Texas Rangers drive cattle from the Rio Grande to Montana.'} },
  { id:'prideprej', author:'Jane Austen', year:1813, place:'Meryton (Hertfordshire)', country:'UK', lng:-0.0850, lat:51.7889, tier:2, relation:'set', genre:'Romance', rating:4.29, pages:432,
    languages:['English'], titles:{English:'Pride and Prejudice'}, blurbs:{English:'The Bennets, a country estate, and Mr Darcy.'} },
  { id:'gentleman', author:'Amor Towles', year:2016, place:'Moscow', country:'Russia', lng:37.6173, lat:55.7558, tier:2, relation:'set', genre:'Historical Fiction', rating:4.35, pages:462,
    languages:['English'], titles:{English:'A Gentleman in Moscow'}, blurbs:{English:'An exiled count lives out a lifetime inside the Metropol Hotel.'} },
  { id:'pachinko', author:'Min Jin Lee', year:2017, place:'Osaka', country:'Japan', lng:135.5023, lat:34.6937, tier:2, relation:'set', genre:'Historical Fiction', rating:4.34, pages:560,
    languages:['English'], titles:{English:'Pachinko'}, blurbs:{English:'A Korean family across generations of exile in Japan.'} },
  { id:'allthelight', author:'Anthony Doerr', year:2014, place:'Saint-Malo', country:'France', lng:-2.0257, lat:48.6493, tier:2, relation:'set', genre:'Historical Fiction', rating:4.34, pages:530,
    languages:['English'], titles:{English:'All the Light We Cannot See'}, blurbs:{English:'A blind girl and a German soldier converge during WWII.'} },
  { id:'finebalance', author:'Rohinton Mistry', year:1995, place:'Mumbai', country:'India', lng:72.8777, lat:19.0760, tier:2, relation:'set', genre:'Literary Fiction', rating:4.39, pages:603,
    languages:['English'], titles:{English:'A Fine Balance'}, blurbs:{English:'Four lives entangled during Indira Gandhi\'s Emergency.'} },
  { id:'disgrace', author:'J.M. Coetzee', year:1999, place:'Cape Town', country:'South Africa', lng:18.4241, lat:-33.9249, tier:2, relation:'set', genre:'Literary Fiction', rating:3.89, pages:220,
    languages:['English'], titles:{English:'Disgrace'}, blurbs:{English:'A Cape Town professor\'s fall from grace and its violent aftermath on his daughter\'s Eastern Cape farm.'} },
  { id:'aliasgrace', author:'Margaret Atwood', year:1996, place:'Kingston, Ontario', country:'Canada', lng:-76.4860, lat:44.2312, tier:2, relation:'set', genre:'Historical Fiction', rating:4.05, pages:468,
    languages:['English'], titles:{English:'Alias Grace'}, blurbs:{English:'A nineteenth-century servant convicted of murder tells her story to a young psychiatrist.'} },
  { id:'picnic', author:'Joan Lindsay', year:1967, place:'Hanging Rock, Victoria', country:'Australia', lng:144.5817, lat:-37.3826, tier:2, relation:'set', genre:'Mystery', rating:3.87, pages:175,
    languages:['English'], titles:{English:'Picnic at Hanging Rock'}, blurbs:{English:'Three schoolgirls vanish without trace on a Valentine\'s Day outing to a volcanic rock formation in Victoria.'} },
  { id:'thornbirds', author:'Colleen McCullough', year:1977, place:'New South Wales', country:'Australia', lng:148.50, lat:-31.50, tier:1, relation:'set', genre:'Literary Fiction', rating:4.22, pages:533,
    languages:['English', 'Chinese'],
    titles:{ English:'The Thorn Birds', Chinese:'荆棘鸟' },
    blurbs:{
      English:'A forbidden love between a Catholic priest and a woman spans four decades on a vast sheep station in the Australian Outback.',
      Chinese:'一位天主教神父与一名女子之间横跨四十年的禁忌之恋，在澳大利亚内陆的广袤牧场上缓缓展开。',
    } },
  // Tier 3
  { id:'thehelp', author:'Kathryn Stockett', year:2009, place:'Jackson, MS', country:'USA', lng:-90.1848, lat:32.2988, tier:3, relation:'set', genre:'Historical Fiction', rating:4.46, pages:444,
    languages:['English'], titles:{English:'The Help'}, blurbs:{English:'Black maids speak out in 1960s Mississippi.'} },
  { id:'crawdads', author:'Delia Owens', year:2018, place:'Barkley Cove (NC coast)', country:'USA', lng:-75.6824, lat:35.7796, tier:3, relation:'set', genre:'Mystery', rating:4.40, pages:368,
    languages:['English'], titles:{English:'Where the Crawdads Sing'}, blurbs:{English:'A "marsh girl" suspected of murder in coastal Carolina.'} },
  { id:'bookthief', author:'Markus Zusak', year:2005, place:'Molching (near Munich)', country:'Germany', lng:11.5820, lat:48.1351, tier:3, relation:'set', genre:'Historical Fiction', rating:4.40, pages:552,
    languages:['English'], titles:{English:'The Book Thief'}, blurbs:{English:'A girl steals books in Nazi Germany, narrated by Death.'} },
  { id:'treegrows', author:'Betty Smith', year:1943, place:'Brooklyn, NY', country:'USA', lng:-73.9442, lat:40.6782, tier:3, relation:'set', genre:'Coming-of-Age', rating:4.29, pages:493,
    languages:['English'], titles:{English:'A Tree Grows in Brooklyn'}, blurbs:{English:'A poor immigrant girl\'s coming of age in pre-WWI Brooklyn.'} },
  { id:'cuttingstone', author:'Abraham Verghese', year:2009, place:'Addis Ababa', country:'Ethiopia', lng:38.7525, lat:9.0192, tier:3, relation:'set', genre:'Literary Fiction', rating:4.31, pages:541,
    languages:['English'], titles:{English:'Cutting for Stone'}, blurbs:{English:'Twin brothers born in a mission hospital in Ethiopia.'} },
  { id:'doriangray', author:'Oscar Wilde', year:1890, place:'London', country:'UK', lng:-0.1500, lat:51.5142, tier:3, relation:'set', genre:'Gothic Fiction', rating:4.13, pages:254,
    languages:['English'], titles:{English:'The Picture of Dorian Gray'}, blurbs:{English:'A portrait ages while its subject keeps his beauty.'} },
  { id:'paintedbird', author:'Jerzy Kosiński', year:1965, place:'Rural Poland', country:'Poland', lng:20.9806, lat:50.0647, tier:3, relation:'set', genre:'Historical Fiction', rating:3.80, pages:234,
    languages:['English'], titles:{English:'The Painted Bird'}, blurbs:{English:'A dark-haired boy wanders alone through Eastern European villages during WWII, surviving unimaginable brutality at every turn.'} },

  // Portrait masterpieces
  { id:'istanbulmemoir', author:'Orhan Pamuk', year:2003, place:'Istanbul', country:'Türkiye', lng:28.9784, lat:41.0082, tier:1, relation:'about', genre:'Memoir', rating:4.06, pages:384,
    languages:['English','French','Chinese'],
    titles:{English:'Istanbul: Memories and the City', French:'Istanbul: Souvenirs d\'une ville', Chinese:'伊斯坦布尔：一座城市的记忆'},
    blurbs:{
      English:'Orhan Pamuk\'s memoir of growing up amid Istanbul\'s ruins — tracing the city\'s hüzün, its particular melancholy, through crumbling mansions, fogbound Bosphorus mornings, and the ghost of a lost empire.',
      French:'Le mémoire d\'Orhan Pamuk sur son enfance parmi les ruines d\'Istanbul — retraçant le hüzün de la ville à travers des manoirs décrépits, des matins brumeux sur le Bosphore et le fantôme d\'un empire disparu.',
      Chinese:'帕慕克追忆在伊斯坦布尔废墟之间成长的岁月，以"呼愁"（hüzün）命名这座城市特有的忧郁——颓败的豪宅、雾气中的博斯普鲁斯清晨，以及一个逝去帝国的幽灵。'
    } },
  { id:'hereisnewyork', author:'E.B. White', year:1949, place:'New York', country:'USA', lng:-73.9857, lat:40.7484, tier:1, relation:'about', genre:'Memoir', rating:4.13, pages:54,
    languages:['English','French','Chinese'],
    titles:{English:'Here Is New York', French:'Voici New York', Chinese:'这就是纽约'},
    blurbs:{
      English:'A 54-page essay written in a single summer of 1948 — capturing New York\'s impossible, anonymous energy and prophesying, with uncanny precision, the city\'s vulnerability.',
      French:'Un essai de 54 pages écrit en un seul été de 1948 — capturant l\'énergie impossible et anonyme de New York et prophétisant, avec une troublante précision, la vulnérabilité de la ville.',
      Chinese:'1948年夏天一挥而就的五十四页小品——捕捉了纽约那种难以言说的匿名能量，并以惊人的预见力道出了这座城市的脆弱。'
    } },
  { id:'goodbyeberlin', author:'Christopher Isherwood', year:1939, place:'Berlin', country:'Germany', lng:13.4050, lat:52.5200, tier:1, relation:'about', genre:'Literary Fiction', rating:4.00, pages:240,
    languages:['English','French','Chinese'],
    titles:{English:'Goodbye to Berlin', French:'Adieu à Berlin', Chinese:'再见柏林'},
    blurbs:{
      English:'Six interlinked portraits of Weimar Berlin on the eve of the Nazi rise — cabaret singers, Jewish families, landladies — told through Isherwood\'s cool, cinematic eye. "I am a camera."',
      French:'Six portraits entrelacés du Berlin de Weimar à la veille de la montée du nazisme — chanteuses de cabaret, familles juives, propriétaires — vus par l\'œil froid et cinématographique d\'Isherwood. « Je suis un appareil photo. »',
      Chinese:'纳粹崛起前夕，魏玛柏林六幅众生相——歌舞厅歌手、犹太家庭、房东太太——经由石沃德那双冷静的摄影机之眼呈现。"我是一台相机。"'
    } },
  { id:'homagetocatalonia', author:'George Orwell', year:1938, place:'Barcelona', country:'Spain', lng:2.1734, lat:41.3851, tier:1, relation:'about', genre:'Memoir', rating:4.11, pages:232,
    languages:['English','French','Chinese'],
    titles:{English:'Homage to Catalonia', French:'Hommage à la Catalogne', Chinese:'向加泰罗尼亚致敬'},
    blurbs:{
      English:'Orwell\'s memoir of fighting for the Republic in the Spanish Civil War — the mud of the Aragon trenches, the euphoria of revolutionary Barcelona, and the bitter disillusionment that followed.',
      French:'Le récit d\'Orwell sur ses combats pour la République pendant la guerre civile espagnole — la boue des tranchées d\'Aragon, l\'euphorie de Barcelone révolutionnaire et la désillusion amère qui s\'ensuivit.',
      Chinese:'奥威尔记述在西班牙内战中为共和国而战的亲身经历——阿拉贡战壕的泥泞、革命巴塞罗那的狂喜，以及随之而来的彻底幻灭。'
    } },
  { id:'narrowroad', author:'Matsuo Bashō', year:1689, place:'Matsushima', country:'Japan', lng:141.0674, lat:38.3694, tier:1, relation:'about', genre:'Memoir', rating:4.12, pages:96,
    languages:['English','French','Chinese'],
    titles:{English:'The Narrow Road to the Deep North', French:'La Sente étroite du Bout-du-Monde', Chinese:'奥之细道'},
    blurbs:{
      English:'Matsuo Bashō\'s 1689 pilgrimage through northern Japan — haiku crystallising entire landscapes into seventeen syllables, and a wandering poet\'s meditation on impermanence and time.',
      French:'Le pèlerinage de Matsuo Bashō en 1689 à travers le Japon septentrional — des haïkus cristallisant des paysages entiers en dix-sept syllabes, et la méditation d\'un poète errant sur l\'impermanence.',
      Chinese:'松尾芭蕉1689年的北日本朝圣之旅——以俳句将整片风景凝于十七个音节，一位行脚诗人对无常与时间的冥想。'
    } },
  { id:'maximumcity', author:'Suketu Mehta', year:2004, place:'Mumbai', country:'India', lng:72.8777, lat:19.0760, tier:2, relation:'about', genre:'Memoir', rating:4.10, pages:542,
    languages:['English','French','Chinese'],
    titles:{English:'Maximum City: Bombay Lost and Found', French:'Maximum City: Bombay la cité des excès', Chinese:'孟买：失落与重寻之城'},
    blurbs:{
      English:'Suketu Mehta returns to Bombay after 21 years in New York and immerses himself in its gangsters, bar dancers, Bollywood directors, and slum dwellers — the city in its full, chaotic magnificence.',
      French:'Suketu Mehta retourne à Bombay après 21 ans à New York et s\'immerge dans ses gangsters, danseuses de bar, réalisateurs de Bollywood et habitants des bidonvilles — la ville dans toute sa magnificence chaotique.',
      Chinese:'苏克图·梅塔离开孟买二十一年后重返故地，深入其中的黑帮、舞厅女郎、宝莱坞导演与贫民窟居民——这座城市全部的混乱与壮阔。'
    } },
  { id:'yearinprovence', author:'Peter Mayle', year:1989, place:'Provence', country:'France', lng:5.3650, lat:43.8567, tier:2, relation:'about', genre:'Memoir', rating:3.82, pages:211,
    languages:['English','French','Chinese'],
    titles:{English:'A Year in Provence', French:'Une année en Provence', Chinese:'普罗旺斯的一年'},
    blurbs:{
      English:'A British couple move to the Luberon and discover the rhythms of Provençal life — truffle hunters, wine harvests, boisterous lunches, and the stoic cheerfulness of their neighbours.',
      French:'Un couple britannique s\'installe dans le Luberon et découvre les rythmes de la vie provençale — chasseurs de truffes, vendanges, déjeuners animés et la sérénité stoïque de leurs voisins.',
      Chinese:'一对英国夫妇迁居吕贝隆，发现了普罗旺斯生活的节奏——松露猎人、葡萄收获、喧嚣的午宴，以及邻居们那坦然的乐天。'
    } },
  { id:'danube', author:'Claudio Magris', year:1986, place:'Vienna', country:'Austria', lng:16.3738, lat:48.2082, tier:2, relation:'about', genre:'Memoir', rating:3.96, pages:462,
    languages:['English','French','Chinese'],
    titles:{English:'Danube', French:'Danube', Chinese:'多瑙河'},
    blurbs:{
      English:'Claudio Magris follows the Danube from its Black Forest source to the Black Sea, reading the river as a biography of Central European civilisation — Habsburg, Jewish, and irretrievably lost.',
      French:'Claudio Magris suit le Danube depuis sa source dans la Forêt-Noire jusqu\'à la mer Noire, lisant le fleuve comme la biographie de la civilisation centre-européenne — habsbourgeoise, juive et irrémédiablement perdue.',
      Chinese:'马格里斯沿多瑙河从黑森林源头追溯至黑海，以这条河流为传记，书写中欧文明——哈布斯堡的、犹太的，以及那些已无可挽回地消逝的。'
    } },

  // ============================================================
  // Chinese (20)
  // ============================================================
  { id:'fusang', author:'严歌苓 Geling Yan', year:1998, place:'San Francisco Chinatown', country:'USA', lng:-122.4065, lat:37.7955, tier:2, relation:'set', genre:'Historical Fiction', rating:4.05, ratingSource:'Douban', pages:245,
    languages:['Chinese'], titles:{Chinese:'扶桑'}, blurbs:{Chinese:'十九世纪旧金山唐人街，一个中国女子扶桑在异乡的苦难与救赎。'} },
  { id:'newyorkers', author:'白先勇 Bai Xianyong', year:1974, place:'New York', country:'USA', lng:-73.98, lat:40.75, tier:2, relation:'set', genre:'Literary Fiction', rating:4.35, ratingSource:'Douban', pages:276,
    languages:['Chinese'], titles:{Chinese:'纽约客'}, blurbs:{Chinese:'漂泊纽约的华人群像，在异国都市中寻找认同与归属的故事。'} },
  // Tier 1
  { id:'redchamber', author:'曹雪芹 Cao Xueqin', year:1791, place:'北京 Beijing (恭王府)', country:'China', lng:116.3856, lat:39.9320, tier:1, relation:'set', genre:'Classic Fiction', rating:4.13, pages:1000,
    languages:['Chinese'], titles:{Chinese:'红楼梦'}, blurbs:{Chinese:'清代豪门大宅中贵族家族的衰落与少年情爱。'} },
  { id:'threek', author:'罗贯中 Luo Guanzhong', year:1400, place:'洛阳 Luoyang', country:'China', lng:112.4540, lat:34.6196, tier:1, relation:'set', genre:'Historical Epic', rating:4.06, pages:800,
    languages:['Chinese'], titles:{Chinese:'三国演义'}, blurbs:{Chinese:'魏蜀吴三国争霸，定义中国战略思维的史诗巨作。'} },
  { id:'journeywest', author:'吴承恩 Wu Cheng\'en', year:1592, place:'西安 (长安) Xi\'an', country:'China', lng:108.9398, lat:34.3416, tier:1, relation:'set', genre:'Fantasy', rating:4.10, pages:800,
    languages:['Chinese'], titles:{Chinese:'西游记'}, blurbs:{Chinese:'孙悟空护送唐僧西天取经，一路降妖伏魔的奇幻冒险。'} },
  { id:'fortress', author:'钱锺书 Qian Zhongshu', year:1947, place:'上海 Shanghai', country:'China', lng:121.43, lat:31.24, tier:1, relation:'set', genre:'Satire', rating:4.06, pages:330,
    languages:['Chinese'], titles:{Chinese:'围城'}, blurbs:{Chinese:'留学归国的方鸿渐在战时上海与人生的婚姻围城。'} },
  { id:'tolive', author:'余华 Yu Hua', year:1993, place:'rural Sichuan', country:'China', lng:104.0668, lat:30.5728, tier:1, relation:'set', genre:'Literary Fiction', rating:4.30, pages:180,
    languages:['Chinese'], titles:{Chinese:'活着'}, blurbs:{Chinese:'一个普通中国农民在二十世纪的浩劫中失去一切，仍然活着。'} },
  { id:'ahq', author:'鲁迅 Lu Xun', year:1921, place:'绍兴 Shaoxing', country:'China', lng:120.5810, lat:30.0023, tier:1, relation:'set', genre:'Satire', rating:4.15, pages:90,
    languages:['Chinese'], titles:{Chinese:'阿Q正传'}, blurbs:{Chinese:'晚清乡村中一个穷苦村民的精神胜利与悲剧人生。'} },
  { id:'callarms', author:'鲁迅 Lu Xun', year:1923, place:'北京 Beijing (Lu Xun Museum)', country:'China', lng:116.3500, lat:39.9290, tier:1, relation:'set', genre:'Short Stories', rating:4.27, pages:200,
    languages:['Chinese'], titles:{Chinese:'呐喊'}, blurbs:{Chinese:'开启中国现代文学的短篇集，呐喊出沉睡国民的觉醒。'} },
  { id:'madman', author:'鲁迅 Lu Xun', year:1918, place:'绍兴 Shaoxing (鲁镇)', country:'China', lng:120.4900, lat:29.9900, tier:1, relation:'set', genre:'Literary Fiction', rating:4.10, pages:30,
    languages:['Chinese'], titles:{Chinese:'狂人日记'}, blurbs:{Chinese:'中国第一篇现代白话小说，借"狂人"之眼揭露吃人的礼教。'} },
  { id:'panghuang', author:'鲁迅 Lu Xun', year:1926, place:'北京 Beijing', country:'China', lng:116.4100, lat:39.9100, tier:1, relation:'set', genre:'Short Stories', rating:4.20, pages:250,
    languages:['Chinese'], titles:{Chinese:'彷徨'}, blurbs:{Chinese:'继《呐喊》之后的短篇集，写尽新旧交替中知识分子的苦闷与彷徨。'} },
  { id:'wildgrass', author:'鲁迅 Lu Xun', year:1927, place:'北京 Beijing', country:'China', lng:116.3800, lat:39.9400, tier:1, relation:'set', genre:'Literary Fiction', rating:4.30, pages:100,
    languages:['Chinese'], titles:{Chinese:'野草'}, blurbs:{Chinese:'一部充满象征与哲思的散文诗集，于黑暗中寻觅希望的微光。'} },
  { id:'dawnblossoms', author:'鲁迅 Lu Xun', year:1928, place:'绍兴 Shaoxing', country:'China', lng:120.6000, lat:30.0100, tier:1, relation:'about', genre:'Memoir', rating:4.40, pages:150,
    languages:['Chinese'], titles:{Chinese:'朝花夕拾'}, blurbs:{Chinese:'回忆童年与青年往事的散文集，于温情中藏着锋利的笔。'} },
  { id:'oldtales', author:'鲁迅 Lu Xun', year:1936, place:'上海 Shanghai', country:'China', lng:121.4700, lat:31.2200, tier:1, relation:'set', genre:'Satire', rating:4.00, pages:180,
    languages:['Chinese'], titles:{Chinese:'故事新编'}, blurbs:{Chinese:'取材神话传说的短篇集，以戏谑笔法重述古老故事。'} },
  { id:'hulanriver', author:'萧红 Xiao Hong', year:1942, place:'呼兰 Hulan', country:'China', lng:126.9600, lat:45.8900, tier:1, relation:'about', genre:'Memoir', rating:4.45, pages:192,
    languages:['Chinese','English'],
    titles:{Chinese:'呼兰河传', English:'Tales of Hulan River'},
    blurbs:{
      Chinese:'童年记忆中的北国小城，以轻盈笔触写就的挽歌——菜园、火烧云、跳大神，以及那些被生活悄悄淹没的人们。',
      English:'Xiao Hong\'s elegy for a Manchurian town of her childhood — a kitchen garden, blazing northern skies, shamanist rituals, and the quiet, unwitnessed lives lived within its walls.'
    } },
  { id:'xiangjournals', author:'沈从文 Shen Congwen', year:1936, place:'湘西 Xiangxi', country:'China', lng:109.7370, lat:28.3113, tier:1, relation:'about', genre:'Memoir', rating:4.38, pages:172,
    languages:['Chinese','English'],
    titles:{Chinese:'湘行散记', English:'A Record of Journey to Hunan'},
    blurbs:{
      Chinese:'沈从文返乡途中写给妻子的信与随笔，以湘西的山水和船工侧写出一个行将消逝的边地世界。',
      English:'Letters and sketches written to his wife as Shen Congwen travelled up the Xiang River — a portrait of a border world of boatmen, mountains, and unhurried time.'
    } },
  // Tier 2
  { id:'threebody', author:'刘慈欣 Liu Cixin', year:2006, place:'北京 Beijing (Tsinghua)', country:'China', lng:116.3265, lat:39.9994, tier:2, relation:'set', genre:'Science Fiction', rating:4.08, pages:400,
    languages:['Chinese'], titles:{Chinese:'三体'}, blurbs:{Chinese:'文化大革命中一个绝望的决定，引来三体文明的入侵。'} },
  { id:'fallencity', author:'张爱玲 Eileen Chang', year:1943, place:'香港 Hong Kong', country:'China', lng:114.1694, lat:22.3193, tier:2, relation:'set', genre:'Literary Fiction', rating:4.16, pages:200,
    languages:['Chinese'], titles:{Chinese:'倾城之恋'}, blurbs:{Chinese:'一座城市的陷落，成全了一对乱世男女的婚姻。'} },
  { id:'sorrow', author:'王安忆 Wang Anyi', year:1995, place:'上海 Shanghai', country:'China', lng:121.52, lat:31.23, tier:2, relation:'set', genre:'Literary Fiction', rating:4.04, pages:394,
    languages:['Chinese'], titles:{Chinese:'长恨歌'}, blurbs:{Chinese:'上海弄堂里走出的"上海小姐"王琦瑶，四十年风雨人生。'} },
  { id:'bordertown', author:'沈从文 Shen Congwen', year:1934, place:'茶峒 Chadong (Hunan)', country:'China', lng:109.60, lat:28.00, tier:2, relation:'set', genre:'Literary Fiction', rating:4.16, pages:110,
    languages:['Chinese'], titles:{Chinese:'边城'}, blurbs:{Chinese:'湘西边境一位摆渡老人的孙女与两兄弟的纯净爱情。'} },
  { id:'rickshaw', author:'老舍 Lao She', year:1937, place:'北京 Beijing (Qianmen)', country:'China', lng:116.3789, lat:39.8898, tier:2, relation:'set', genre:'Literary Fiction', rating:4.07, pages:285,
    languages:['Chinese'], titles:{Chinese:'骆驼祥子'}, blurbs:{Chinese:'老北京一个人力车夫的梦想被时代一点点碾碎。'} },
  { id:'ordinaryworld', author:'路遥 Lu Yao', year:1986, place:'陕北 northern Shaanxi', country:'China', lng:109.4900, lat:36.5853, tier:2, relation:'set', genre:'Literary Fiction', rating:4.50, pages:1200,
    languages:['Chinese'], titles:{Chinese:'平凡的世界'}, blurbs:{Chinese:'改革开放年代两兄弟在陕北黄土地上的奋斗与爱情。'} },
  { id:'whitedeerplain', author:'陈忠实 Chen Zhongshi', year:1993, place:'西安 Xi\'an (Shaanxi)', country:'China', lng:108.9600, lat:34.3500, tier:2, relation:'set', genre:'Historical Fiction', rating:4.21, pages:540,
    languages:['Chinese'], titles:{Chinese:'白鹿原'}, blurbs:{Chinese:'白、鹿两家在陕西关中平原上半个世纪的兴衰恩怨。'} },
  // Tier 3
  { id:'bloodmerchant', author:'余华 Yu Hua', year:1995, place:'small-town China', country:'China', lng:120.16, lat:30.27, tier:3, relation:'set', genre:'Literary Fiction', rating:4.27, pages:246,
    languages:['Chinese'], titles:{Chinese:'许三观卖血记'}, blurbs:{Chinese:'许三观靠卖血度过一次次家庭与时代的危机。'} },
  { id:'teahouse', author:'老舍 Lao She', year:1957, place:'北京 Beijing (Wangfujing)', country:'China', lng:116.4131, lat:39.9059, tier:3, relation:'set', genre:'Drama', rating:4.31, pages:100,
    languages:['Chinese'], titles:{Chinese:'茶馆'}, blurbs:{Chinese:'一家北京老茶馆见证三个中国时代的兴亡更替。'} },
  { id:'brothers', author:'余华 Yu Hua', year:2005, place:'small-town China', country:'China', lng:120.18, lat:30.28, tier:3, relation:'set', genre:'Literary Fiction', rating:4.05, pages:640,
    languages:['Chinese'], titles:{Chinese:'兄弟'}, blurbs:{Chinese:'一对继兄弟在文革与改革开放中迥异的命运。'} },
  { id:'family', author:'巴金 Ba Jin', year:1933, place:'成都 Chengdu', country:'China', lng:104.0668, lat:30.5828, tier:3, relation:'set', genre:'Literary Fiction', rating:4.07, pages:300,
    languages:['Chinese'], titles:{Chinese:'家'}, blurbs:{Chinese:'激流三部曲第一部：成都一个旧式大家族中年轻一代对封建礼教的反抗。'} },
  { id:'chun', author:'巴金 Ba Jin', year:1938, place:'成都 Chengdu', country:'China', lng:104.0668, lat:30.5828, tier:3, relation:'set', genre:'Literary Fiction', rating:4.02, pages:280,
    languages:['Chinese'], titles:{Chinese:'春'}, blurbs:{Chinese:'激流三部曲第二部：淑英在觉慧出走后寻找属于自己的出路。'} },
  { id:'qiu', author:'巴金 Ba Jin', year:1940, place:'成都 Chengdu', country:'China', lng:104.0668, lat:30.5828, tier:3, relation:'set', genre:'Literary Fiction', rating:4.10, pages:295,
    languages:['Chinese'], titles:{Chinese:'秋'}, blurbs:{Chinese:'激流三部曲终章：高家在革命浪潮中走向最终的瓦解与离散。'} },
  { id:'coldnight', author:'巴金 Ba Jin', year:1947, place:'重庆 Chongqing', country:'China', lng:106.5516, lat:29.5630, tier:2, relation:'set', genre:'Literary Fiction', rating:4.25, pages:265,
    languages:['Chinese'], titles:{Chinese:'寒夜'}, blurbs:{Chinese:'抗战末期重庆，一对知识分子夫妻在贫病与战时压抑中一步步走向绝望。'} },
  { id:'midnight', author:'茅盾 Mao Dun', year:1933, place:'上海 Shanghai', country:'China', lng:121.47, lat:31.31, tier:3, relation:'set', genre:'Social Realism', rating:4.16, pages:565,
    languages:['Chinese'], titles:{Chinese:'子夜'}, blurbs:{Chinese:'1930年代上海资本家吴荪甫在金融风暴中的覆灭。'} },
  { id:'thunderstorm', author:'曹禺 Cao Yu', year:1934, place:'北京 Beijing (Yongdingmen)', country:'China', lng:116.4140, lat:39.8650, tier:3, relation:'set', genre:'Drama', rating:4.20, pages:100,
    languages:['Chinese'], titles:{Chinese:'雷雨'}, blurbs:{Chinese:'一个旧式大家族在一个雷雨之夜被秘密与命运彻底击碎。'} },

  // ============================================================
  // French (20)
  // ============================================================
  // Tier 1
  { id:'lesmis', author:'Victor Hugo', year:1862, place:'Paris', country:'France', lng:2.370, lat:48.864, tier:1, relation:'set', genre:'Historical Fiction', rating:4.21, pages:1463,
    languages:['French', 'Chinese'],
    titles:{ French:'Les Misérables', Chinese:'悲惨世界' },
    blurbs:{ French:'Barricades, rédemption et bas-fonds du Paris du XIXᵉ siècle.', Chinese:'冉·阿让从苦役犯到圣人的救赎之路，在十九世纪巴黎的街垒与阴影中展开。' } },
  { id:'proust', author:'Marcel Proust', year:1913, place:'Illiers-Combray', country:'France', lng:1.2469, lat:48.2997, tier:1, relation:'set', genre:'Literary Fiction', rating:4.06, pages:3000,
    languages:['French'], titles:{French:'À la recherche du temps perdu'}, blurbs:{French:'La mémoire dévidée par le goût d\'une seule madeleine.'} },
  { id:'stranger', author:'Albert Camus', year:1942, place:'Alger', country:'Algeria', lng:3.0588, lat:36.7538, tier:1, relation:'set', genre:'Philosophical Fiction', rating:4.02, pages:123,
    languages:['French'], titles:{French:'L\'Étranger'}, blurbs:{French:'L\'indifférence d\'un employé sous le soleil aveuglant de l\'Algérie.'} },
  { id:'plague', author:'Albert Camus', year:1947, place:'Oran', country:'Algeria', lng:-0.6349, lat:35.6987, tier:1, relation:'set', genre:'Philosophical Fiction', rating:4.04, pages:308,
    languages:['French'], titles:{French:'La Peste'}, blurbs:{French:'Une ville côtière fermée par une épidémie de peste.'} },
  { id:'montecristo', author:'Alexandre Dumas', year:1844, place:'Marseille', country:'France', lng:5.3698, lat:43.2965, tier:1, relation:'set', genre:'Adventure Fiction', rating:4.30, pages:1276,
    languages:['French'], titles:{French:'Le Comte de Monte-Cristo'}, blurbs:{French:'Un marin injustement emprisonné revient pour ruiner ses traîtres.'} },
  { id:'mousquetaires', author:'Alexandre Dumas', year:1844, place:'Paris', country:'France', lng:2.334, lat:48.864, tier:1, relation:'set', genre:'Historical Fiction', rating:4.10, pages:700,
    languages:['French'], titles:{French:'Les Trois Mousquetaires'}, blurbs:{French:'Intrigues et cape et épée sous le règne de Louis XIII.'} },
  { id:'petitprince', author:'Antoine de Saint-Exupéry', year:1943, place:'Sahara', country:'Sahara desert', lng:11.8389, lat:23.4162, tier:1, relation:'set', genre:'Fable', rating:4.32, pages:96,
    languages:['French'], titles:{French:'Le Petit Prince'}, blurbs:{French:'Un pilote rencontre un petit prince au milieu des dunes du Sahara.'} },
  // Tier 2
  { id:'voyagenuit', author:'Louis-Ferdinand Céline', year:1932, place:'Paris', country:'France', lng:2.345, lat:48.887, tier:2, relation:'set', genre:'Literary Fiction', rating:4.05, pages:504,
    languages:['French'], titles:{French:'Voyage au bout de la nuit'}, blurbs:{French:'Une traversée bilieuse de la guerre, des colonies et des banlieues.'} },
  { id:'germinal', author:'Émile Zola', year:1885, place:'Lille (Nord)', country:'France', lng:3.0573, lat:50.6292, tier:2, relation:'set', genre:'Social Realism', rating:4.13, pages:531,
    languages:['French'], titles:{French:'Germinal'}, blurbs:{French:'Des mineurs de charbon se révoltent contre les patrons et la faim.'} },
  { id:'belami', author:'Guy de Maupassant', year:1885, place:'Paris', country:'France', lng:2.330, lat:48.873, tier:2, relation:'set', genre:'Literary Fiction', rating:4.04, pages:352,
    languages:['French'], titles:{French:'Bel-Ami'}, blurbs:{French:'Un bel opportuniste grimpe les échelons de la société parisienne.'} },
  { id:'belledusg', author:'Albert Cohen', year:1968, place:'Geneva', country:'Switzerland', lng:6.1432, lat:46.2044, tier:2, relation:'set', genre:'Literary Fiction', rating:4.36, pages:1100,
    languages:['French'], titles:{French:'Belle du Seigneur'}, blurbs:{French:'La passion obsessionnelle d\'un diplomate pour la femme d\'un collègue.'} },
  { id:'suitefr', author:'Irène Némirovsky', year:2004, place:'Issy-l\'Évêque (Burgundy)', country:'France', lng:4.0833, lat:46.7167, tier:2, relation:'set', genre:'Historical Fiction', rating:4.13, pages:416,
    languages:['French'], titles:{French:'Suite française'}, blurbs:{French:'Des vies à travers la France pendant l\'invasion allemande de 1940.'} },
  { id:'chagrinec', author:'Daniel Pennac', year:2007, place:'Paris', country:'France', lng:2.346, lat:48.846, tier:2, relation:'about', genre:'Memoir', rating:4.07, pages:304,
    languages:['French'], titles:{French:'Chagrin d\'école'}, blurbs:{French:'Un romancier se retourne sur sa vie d\'élève cancre.'} },
  { id:'hadrien', author:'Marguerite Yourcenar', year:1951, place:'Rome', country:'Italy', lng:12.4964, lat:41.9028, tier:2, relation:'set', genre:'Historical Fiction', rating:4.18, pages:293,
    languages:['French'], titles:{French:'Mémoires d\'Hadrien'}, blurbs:{French:'L\'empereur mourant médite sur sa vie et son règne.'} },
  // Tier 3
  { id:'oeuvrenoir', author:'Marguerite Yourcenar', year:1968, place:'Bruges', country:'Belgium', lng:3.2247, lat:51.2093, tier:3, relation:'set', genre:'Historical Fiction', rating:4.16, pages:382,
    languages:['French'], titles:{French:'L\'Œuvre au noir'}, blurbs:{French:'Un alchimiste de la Renaissance entre hérésie et raison.'} },
  { id:'promesseaube', author:'Romain Gary', year:1960, place:'Nice', country:'France', lng:7.2620, lat:43.7102, tier:3, relation:'about', genre:'Memoir', rating:4.36, pages:320,
    languages:['French'], titles:{French:'La Promesse de l\'aube'}, blurbs:{French:'Le mémoire d\'un fils sur sa mère farouche et impossible.'} },
  { id:'viedevant', author:'Romain Gary (Émile Ajar)', year:1975, place:'Paris (Belleville)', country:'France', lng:2.3800, lat:48.8800, tier:3, relation:'set', genre:'Literary Fiction', rating:4.27, pages:243,
    languages:['French'], titles:{French:'La Vie devant soi'}, blurbs:{French:'Un garçon arabe élevé par une vieille femme juive à Belleville.'} },
  { id:'lelion', author:'Joseph Kessel', year:1958, place:'Amboseli', country:'Kenya', lng:37.2606, lat:-2.6532, tier:3, relation:'set', genre:'Adventure Fiction', rating:4.21, pages:216,
    languages:['French'], titles:{French:'Le Lion'}, blurbs:{French:'Une fillette, un lion et un guerrier masaï dans l\'Afrique coloniale.'} },
  { id:'longdimanche', author:'Sébastien Japrisot', year:1991, place:'Brittany', country:'France', lng:-2.9326, lat:48.2020, tier:3, relation:'set', genre:'Mystery', rating:4.13, pages:287,
    languages:['French'], titles:{French:'Un long dimanche de fiançailles'}, blurbs:{French:'Une femme cherche son fiancé déclaré mort dans les tranchées.'} },
  { id:'hussardtoit', author:'Jean Giono', year:1951, place:'Manosque (Provence)', country:'France', lng:5.7855, lat:43.8284, tier:3, relation:'set', genre:'Historical Fiction', rating:4.05, pages:376,
    languages:['French'], titles:{French:'Le Hussard sur le toit'}, blurbs:{French:'Un jeune hussard italien fuit le choléra par les toits de Provence.'} },
  { id:'bonheurocc', author:'Gabrielle Roy', year:1945, place:'Montréal (Saint-Henri)', country:'Canada', lng:-73.5929, lat:45.4720, tier:1, relation:'set', genre:'Literary Fiction', rating:4.10, pages:380,
    languages:['French', 'English'],
    titles: { French: 'Bonheur d\'occasion', English: 'The Tin Flute' },
    blurbs: {
      French: 'Une famille ouvrière de Saint-Henri à Montréal lutte contre la misère pendant la Seconde Guerre mondiale.',
      English: 'A poor working-class family in Montréal\'s Saint-Henri neighbourhood struggles through the Great Depression into wartime.',
    } },

  // Placed last so it renders on top of the French Paris cluster and is directly clickable
  {
    id: 'notredame',
    author: 'Victor Hugo',
    year: 1831,
    place: 'Paris (Notre-Dame)',
    country: 'France',
    lng: 2.3499, lat: 48.8531,
    tier: 1,
    relation: 'set',
    genre: 'Historical Fiction',
    rating: 4.01, pages: 940,
    languages: ['English', 'Chinese', 'French'],
    titles: {
      English: 'The Hunchback of Notre-Dame',
      Chinese: '巴黎圣母院',
      French: 'Notre-Dame de Paris',
    },
    blurbs: {
      English: 'A hunchback bell-ringer, a gypsy dancer, and a corrupted archdeacon in medieval Paris.',
      Chinese: '中世纪巴黎，驼背敲钟人卡西莫多守护吉卜赛女郎爱斯梅拉达，与副主教的欲望交织成悲剧。',
      French: 'Le sonneur de cloches bossu, la danseuse gitane et l\'archidiacre corrompu dans le Paris médiéval.',
    },
  },
];
