import type { Book } from './types';

export const BOOKS: Book[] = [
  // ============================================================
  // Multi-language books (available under more than one filter)
  // ============================================================
  {
    id: 'kiterunner',
    author: 'Khaled Hosseini',
    year: 2003,
    place: 'Kabul',
    country: 'Afghanistan',
    lng: 69.05, lat: 34.50,
    tier: 1,
    relation: 'set',
    rating: 4.36, pages: 372,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'The Kite Runner',
      Chinese: '追风筝的人',
    },
    blurbs: {
      English: 'A boy in Kabul betrays his closest friend and spends a lifetime trying to atone.',
      Chinese: '喀布尔的少年背叛了挚友，多年后远赴故乡寻求救赎。',
    },
  },
  {
    id: 'thousandsuns',
    author: 'Khaled Hosseini',
    year: 2007,
    place: 'Kabul',
    country: 'Afghanistan',
    lng: 69.35, lat: 34.62,
    tier: 1,
    relation: 'set',
    rating: 4.41, pages: 372,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'A Thousand Splendid Suns',
      Chinese: '灿烂千阳',
    },
    blurbs: {
      English: 'Two Afghan women bound together through decades of war and Taliban rule.',
      Chinese: '两位阿富汗女性在战争与塔利班统治下命运交织的故事。',
    },
  },
  {
    id: 'istanbul3',
    author: 'Bettany Hughes',
    year: 2017,
    place: 'Istanbul',
    country: 'Türkiye',
    lng: 28.9784, lat: 41.0082,
    tier: 1,
    relation: 'about',
    rating: 4.03, pages: 480,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'Istanbul: A Tale of Three Cities',
      Chinese: '伊斯坦布尔三城记',
    },
    blurbs: {
      English: 'A sweeping history of Istanbul through its incarnations as Byzantium, Constantinople, and Istanbul.',
      Chinese: '从拜占庭、君士坦丁堡到伊斯坦布尔，一座城市跨越三个文明的恢宏史诗。',
    },
  },
  {
    id: 'crusoe',
    author: 'Daniel Defoe',
    year: 1719,
    place: 'Castaway Island',
    country: 'Caribbean (near Trinidad)',
    lng: -62.0, lat: 10.5,
    tier: 1,
    relation: 'set',
    rating: 3.69, pages: 320,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'Robinson Crusoe',
      Chinese: '鲁滨逊漂流记',
    },
    blurbs: {
      English: 'A shipwrecked sailor survives twenty-eight years alone on a remote Caribbean island.',
      Chinese: '一名遭遇海难的水手在加勒比海荒岛上独自生存二十八年。',
    },
  },
  {
    id: 'leagues20k',
    author: 'Jules Verne',
    year: 1870,
    place: 'Pacific Ocean',
    country: 'the high seas',
    lng: -160.0, lat: 0.0,
    tier: 1,
    relation: 'set',
    rating: 3.90, pages: 380,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'Twenty Thousand Leagues Under the Sea',
      Chinese: '海底两万里',
    },
    blurbs: {
      English: 'Aboard the mysterious submarine Nautilus, a voyage across the world\'s oceans with Captain Nemo.',
      Chinese: '搭乘神秘的鹦鹉螺号潜艇，与尼摩船长一同穿越世界各大洋的深海冒险。',
    },
  },

  {
    id: 'likewater',
    author: 'Laura Esquivel',
    year: 1989,
    place: 'Coahuila, northern Mexico',
    country: 'Mexico',
    lng: -100.52, lat: 28.70,
    tier: 1,
    relation: 'set',
    rating: 3.87, pages: 245,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'Like Water for Chocolate',
      Chinese: '恰似水之于巧克力',
    },
    blurbs: {
      English: 'A Mexican woman forbidden to marry pours her longing into her cooking, which magically affects all who eat it.',
      Chinese: '一个被禁止出嫁的墨西哥女孩，将毕生情感倾注于烹饪，令食者感同身受。',
    },
  },
  {
    id: 'hundredyears',
    author: 'Gabriel García Márquez',
    year: 1967,
    place: 'Macondo (Aracataca)',
    country: 'Colombia',
    lng: -74.19, lat: 10.59,
    tier: 1,
    relation: 'set',
    rating: 4.04, pages: 417,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'One Hundred Years of Solitude',
      Chinese: '百年孤独',
    },
    blurbs: {
      English: 'Seven generations of the Buendía family in the magical, doomed town of Macondo.',
      Chinese: '布恩迪亚家族七代人的兴衰，与那座充满奇幻与宿命的小镇马孔多。',
    },
  },
  {
    id: 'cholera',
    author: 'Gabriel García Márquez',
    year: 1985,
    place: 'Cartagena',
    country: 'Colombia',
    lng: -75.51, lat: 10.40,
    tier: 1,
    relation: 'set',
    rating: 3.90, pages: 348,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'Love in the Time of Cholera',
      Chinese: '霍乱时期的爱情',
    },
    blurbs: {
      English: 'A man waits fifty-one years, nine months, and four days for the woman he loves.',
      Chinese: '一个男人痴痴等待了五十一年九个月零四天，只为与挚爱重续前缘。',
    },
  },
  {
    id: 'notredame',
    author: 'Victor Hugo',
    year: 1831,
    place: 'Paris (Notre-Dame)',
    country: 'France',
    lng: 2.3499, lat: 48.8531,
    tier: 1,
    relation: 'set',
    rating: 4.01, pages: 940,
    languages: ['English', 'Chinese', 'French'],
    titles: {
      English: 'The Hunchback of Notre-Dame',
      Chinese: '巴黎圣母院',
      French: 'Notre-Dame de Paris',
    },
    blurbs: {
      English: 'A hunchback bell-ringer, a gypsy dancer, and a corrupted archdeacon in medieval Paris.',
      Chinese: '中世纪巴黎，驼背敲钟人卡西莫多守护吉卜赛女郎爱斯梅拉达，与副主教的欲望交织成悲剧。',
      French: 'Le sonneur de cloches bossu, la danseuse gitane et l\'archidiacre corrompu dans le Paris médiéval.',
    },
  },

  {
    id: 'gatsby',
    author: 'F. Scott Fitzgerald',
    year: 1925,
    place: 'West Egg, Long Island',
    country: 'USA',
    lng: -73.70, lat: 40.80,
    tier: 1,
    relation: 'set',
    rating: 3.93, pages: 180,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'The Great Gatsby',
      Chinese: '了不起的盖茨比',
    },
    blurbs: {
      English: 'A mysterious millionaire\'s obsession with a married woman across the bay in Jazz Age Long Island.',
      Chinese: '爵士时代的长岛，一个神秘百万富翁对湾对岸那个已婚女人无法自拔的痴迷。',
    },
  },
  {
    id: 'empiresun',
    author: 'J.G. Ballard',
    year: 1984,
    place: 'Shanghai (Lunghua Camp)',
    country: 'China',
    lng: 121.48, lat: 31.15,
    tier: 1,
    relation: 'set',
    rating: 4.06, pages: 279,
    languages: ['English', 'Chinese'],
    titles: {
      English: 'Empire of the Sun',
      Chinese: '太阳帝国',
    },
    blurbs: {
      English: 'An English boy survives the Japanese occupation of Shanghai alone, interned in a WWII camp.',
      Chinese: '二战期间，一个英国男孩在日军占领的上海独自求生，被关押在龙华集中营中。',
    },
  },

  // ============================================================
  // English (19) — Kite Runner is in the multi-language section
  // ============================================================
  // Tier 1
  { id:'shogun', author:'James Clavell', year:1975, place:'Osaka (feudal)', country:'Japan', lng:135.47, lat:34.65, tier:1, relation:'set', rating:4.40, pages:1210,
    languages:['English'], titles:{English:'Shōgun'}, blurbs:{English:'An English navigator shipwrecked in feudal Japan becomes embroiled in a warlord\'s bid for power.'} },
  { id:'balzac', author:'Dai Sijie', year:2000, place:'Phoenix Mountain, Sichuan', country:'China', lng:104.50, lat:29.00, tier:2, relation:'set', rating:3.74, pages:197,
    languages:['English'], titles:{English:'Balzac and the Little Chinese Seamstress'}, blurbs:{English:'Two city boys sent to a remote mountain for re-education discover a suitcase of forbidden Western novels.'} },
  { id:'mockingbird', author:'Harper Lee', year:1960, place:'Monroeville, AL', country:'USA', lng:-87.3247, lat:31.5269, tier:1, relation:'set', rating:4.27, pages:281,
    languages:['English', 'Chinese'], titles:{English:'To Kill a Mockingbird', Chinese:'杀死一只知更鸟'}, blurbs:{English:'Childhood and injustice in a small Alabama town.', Chinese:'阿拉巴马小镇的童年岁月，与一场关于种族与正义的审判。'} },
  { id:'nineteen84', author:'George Orwell', year:1949, place:'London', country:'UK', lng:-0.1276, lat:51.5074, tier:1, relation:'set', rating:4.19, pages:328,
    languages:['English'], titles:{English:'1984'}, blurbs:{English:'A man crushed under a total surveillance state.'} },
  { id:'eden', author:'John Steinbeck', year:1952, place:'Salinas, CA', country:'USA', lng:-121.6555, lat:36.6777, tier:1, relation:'set', rating:4.39, pages:601,
    languages:['English'], titles:{English:'East of Eden'}, blurbs:{English:'Two families and the Cain-and-Abel saga in the Salinas Valley.'} },
  { id:'beloved', author:'Toni Morrison', year:1987, place:'Cincinnati, OH', country:'USA', lng:-84.5120, lat:39.1031, tier:1, relation:'set', rating:4.01, pages:275,
    languages:['English'], titles:{English:'Beloved'}, blurbs:{English:'The haunting of slavery\'s aftermath at 124 Bluestone Road.'} },
  { id:'remainsday', author:'Kazuo Ishiguro', year:1989, place:'Oxfordshire', country:'UK', lng:-1.2577, lat:51.7520, tier:1, relation:'set', rating:4.13, pages:258,
    languages:['English'], titles:{English:'The Remains of the Day'}, blurbs:{English:'A butler\'s quiet reckoning with the years he served.'} },
  { id:'smallthings', author:'Arundhati Roy', year:1997, place:'Kochi (Kerala)', country:'India', lng:76.2673, lat:9.9312, tier:1, relation:'set', rating:4.05, pages:321,
    languages:['English'], titles:{English:'The God of Small Things'}, blurbs:{English:'Twins and a forbidden love in the Kerala backwaters.'} },
  // Tier 2
  { id:'littlelife', author:'Hanya Yanagihara', year:2015, place:'New York', country:'USA', lng:-73.9857, lat:40.7484, tier:2, relation:'set', rating:4.32, pages:720,
    languages:['English'], titles:{English:'A Little Life'}, blurbs:{English:'Four friends in Manhattan over decades of love and damage.'} },
  { id:'lonesomedove', author:'Larry McMurtry', year:1985, place:'Lonesome Dove, TX', country:'USA', lng:-99.00, lat:26.40, tier:2, relation:'set', rating:4.55, pages:945,
    languages:['English'], titles:{English:'Lonesome Dove'}, blurbs:{English:'Aging Texas Rangers drive cattle from the Rio Grande to Montana.'} },
  { id:'prideprej', author:'Jane Austen', year:1813, place:'Meryton (Hertfordshire)', country:'UK', lng:-0.0850, lat:51.7889, tier:2, relation:'set', rating:4.29, pages:432,
    languages:['English'], titles:{English:'Pride and Prejudice'}, blurbs:{English:'The Bennets, a country estate, and Mr Darcy.'} },
  { id:'gentleman', author:'Amor Towles', year:2016, place:'Moscow', country:'Russia', lng:37.6173, lat:55.7558, tier:2, relation:'set', rating:4.35, pages:462,
    languages:['English'], titles:{English:'A Gentleman in Moscow'}, blurbs:{English:'An exiled count lives out a lifetime inside the Metropol Hotel.'} },
  { id:'pachinko', author:'Min Jin Lee', year:2017, place:'Osaka', country:'Japan', lng:135.5023, lat:34.6937, tier:2, relation:'set', rating:4.34, pages:560,
    languages:['English'], titles:{English:'Pachinko'}, blurbs:{English:'A Korean family across generations of exile in Japan.'} },
  { id:'allthelight', author:'Anthony Doerr', year:2014, place:'Saint-Malo', country:'France', lng:-2.0257, lat:48.6493, tier:2, relation:'set', rating:4.34, pages:530,
    languages:['English'], titles:{English:'All the Light We Cannot See'}, blurbs:{English:'A blind girl and a German soldier converge during WWII.'} },
  { id:'finebalance', author:'Rohinton Mistry', year:1995, place:'Mumbai', country:'India', lng:72.8777, lat:19.0760, tier:2, relation:'set', rating:4.39, pages:603,
    languages:['English'], titles:{English:'A Fine Balance'}, blurbs:{English:'Four lives entangled during Indira Gandhi\'s Emergency.'} },
  // Tier 3
  { id:'thehelp', author:'Kathryn Stockett', year:2009, place:'Jackson, MS', country:'USA', lng:-90.1848, lat:32.2988, tier:3, relation:'set', rating:4.46, pages:444,
    languages:['English'], titles:{English:'The Help'}, blurbs:{English:'Black maids speak out in 1960s Mississippi.'} },
  { id:'crawdads', author:'Delia Owens', year:2018, place:'Barkley Cove (NC coast)', country:'USA', lng:-75.6824, lat:35.7796, tier:3, relation:'set', rating:4.40, pages:368,
    languages:['English'], titles:{English:'Where the Crawdads Sing'}, blurbs:{English:'A "marsh girl" suspected of murder in coastal Carolina.'} },
  { id:'bookthief', author:'Markus Zusak', year:2005, place:'Molching (near Munich)', country:'Germany', lng:11.5820, lat:48.1351, tier:3, relation:'set', rating:4.40, pages:552,
    languages:['English'], titles:{English:'The Book Thief'}, blurbs:{English:'A girl steals books in Nazi Germany, narrated by Death.'} },
  { id:'treegrows', author:'Betty Smith', year:1943, place:'Brooklyn, NY', country:'USA', lng:-73.9442, lat:40.6782, tier:3, relation:'set', rating:4.29, pages:493,
    languages:['English'], titles:{English:'A Tree Grows in Brooklyn'}, blurbs:{English:'A poor immigrant girl\'s coming of age in pre-WWI Brooklyn.'} },
  { id:'cuttingstone', author:'Abraham Verghese', year:2009, place:'Addis Ababa', country:'Ethiopia', lng:38.7525, lat:9.0192, tier:3, relation:'set', rating:4.31, pages:541,
    languages:['English'], titles:{English:'Cutting for Stone'}, blurbs:{English:'Twin brothers born in a mission hospital in Ethiopia.'} },
  { id:'doriangray', author:'Oscar Wilde', year:1890, place:'London', country:'UK', lng:-0.1500, lat:51.5142, tier:3, relation:'set', rating:4.13, pages:254,
    languages:['English'], titles:{English:'The Picture of Dorian Gray'}, blurbs:{English:'A portrait ages while its subject keeps his beauty.'} },

  // ============================================================
  // Chinese (20)
  // ============================================================
  { id:'fusang', author:'严歌苓 Geling Yan', year:1998, place:'San Francisco Chinatown', country:'USA', lng:-122.4065, lat:37.7955, tier:2, relation:'set', rating:4.05, ratingSource:'Douban', pages:245,
    languages:['Chinese'], titles:{Chinese:'扶桑'}, blurbs:{Chinese:'十九世纪旧金山唐人街，一个中国女子扶桑在异乡的苦难与救赎。'} },
  { id:'newyorkers', author:'白先勇 Bai Xianyong', year:1974, place:'New York', country:'USA', lng:-73.98, lat:40.75, tier:2, relation:'set', rating:4.35, ratingSource:'Douban', pages:276,
    languages:['Chinese'], titles:{Chinese:'纽约客'}, blurbs:{Chinese:'漂泊纽约的华人群像，在异国都市中寻找认同与归属的故事。'} },
  // Tier 1
  { id:'redchamber', author:'曹雪芹 Cao Xueqin', year:1791, place:'北京 Beijing (恭王府)', country:'China', lng:116.3856, lat:39.9320, tier:1, relation:'set', rating:4.13, pages:1000,
    languages:['Chinese'], titles:{Chinese:'红楼梦'}, blurbs:{Chinese:'清代豪门大宅中贵族家族的衰落与少年情爱。'} },
  { id:'threek', author:'罗贯中 Luo Guanzhong', year:1400, place:'洛阳 Luoyang', country:'China', lng:112.4540, lat:34.6196, tier:1, relation:'set', rating:4.06, pages:800,
    languages:['Chinese'], titles:{Chinese:'三国演义'}, blurbs:{Chinese:'魏蜀吴三国争霸，定义中国战略思维的史诗巨作。'} },
  { id:'journeywest', author:'吴承恩 Wu Cheng\'en', year:1592, place:'西安 (长安) Xi\'an', country:'China', lng:108.9398, lat:34.3416, tier:1, relation:'set', rating:4.10, pages:800,
    languages:['Chinese'], titles:{Chinese:'西游记'}, blurbs:{Chinese:'孙悟空护送唐僧西天取经，一路降妖伏魔的奇幻冒险。'} },
  { id:'fortress', author:'钱锺书 Qian Zhongshu', year:1947, place:'上海 Shanghai', country:'China', lng:121.43, lat:31.24, tier:1, relation:'set', rating:4.06, pages:330,
    languages:['Chinese'], titles:{Chinese:'围城'}, blurbs:{Chinese:'留学归国的方鸿渐在战时上海与人生的婚姻围城。'} },
  { id:'tolive', author:'余华 Yu Hua', year:1993, place:'rural Sichuan', country:'China', lng:104.0668, lat:30.5728, tier:1, relation:'set', rating:4.30, pages:180,
    languages:['Chinese'], titles:{Chinese:'活着'}, blurbs:{Chinese:'一个普通中国农民在二十世纪的浩劫中失去一切，仍然活着。'} },
  { id:'ahq', author:'鲁迅 Lu Xun', year:1921, place:'绍兴 Shaoxing', country:'China', lng:120.5810, lat:30.0023, tier:1, relation:'set', rating:4.15, pages:90,
    languages:['Chinese'], titles:{Chinese:'阿Q正传'}, blurbs:{Chinese:'晚清乡村中一个穷苦村民的精神胜利与悲剧人生。'} },
  { id:'callarms', author:'鲁迅 Lu Xun', year:1923, place:'北京 Beijing (Lu Xun Museum)', country:'China', lng:116.3500, lat:39.9290, tier:1, relation:'set', rating:4.27, pages:200,
    languages:['Chinese'], titles:{Chinese:'呐喊'}, blurbs:{Chinese:'开启中国现代文学的短篇集，呐喊出沉睡国民的觉醒。'} },
  // Tier 2
  { id:'threebody', author:'刘慈欣 Liu Cixin', year:2006, place:'北京 Beijing (Tsinghua)', country:'China', lng:116.3265, lat:39.9994, tier:2, relation:'set', rating:4.08, pages:400,
    languages:['Chinese'], titles:{Chinese:'三体'}, blurbs:{Chinese:'文化大革命中一个绝望的决定，引来三体文明的入侵。'} },
  { id:'fallencity', author:'张爱玲 Eileen Chang', year:1943, place:'香港 Hong Kong', country:'China', lng:114.1694, lat:22.3193, tier:2, relation:'set', rating:4.16, pages:200,
    languages:['Chinese'], titles:{Chinese:'倾城之恋'}, blurbs:{Chinese:'一座城市的陷落，成全了一对乱世男女的婚姻。'} },
  { id:'sorrow', author:'王安忆 Wang Anyi', year:1995, place:'上海 Shanghai', country:'China', lng:121.52, lat:31.23, tier:2, relation:'set', rating:4.04, pages:394,
    languages:['Chinese'], titles:{Chinese:'长恨歌'}, blurbs:{Chinese:'上海弄堂里走出的"上海小姐"王琦瑶，四十年风雨人生。'} },
  { id:'bordertown', author:'沈从文 Shen Congwen', year:1934, place:'茶峒 Chadong (Hunan)', country:'China', lng:109.60, lat:28.00, tier:2, relation:'set', rating:4.16, pages:110,
    languages:['Chinese'], titles:{Chinese:'边城'}, blurbs:{Chinese:'湘西边境一位摆渡老人的孙女与两兄弟的纯净爱情。'} },
  { id:'rickshaw', author:'老舍 Lao She', year:1937, place:'北京 Beijing (Qianmen)', country:'China', lng:116.3789, lat:39.8898, tier:2, relation:'set', rating:4.07, pages:285,
    languages:['Chinese'], titles:{Chinese:'骆驼祥子'}, blurbs:{Chinese:'老北京一个人力车夫的梦想被时代一点点碾碎。'} },
  { id:'ordinaryworld', author:'路遥 Lu Yao', year:1986, place:'陕北 northern Shaanxi', country:'China', lng:109.4900, lat:36.5853, tier:2, relation:'set', rating:4.50, pages:1200,
    languages:['Chinese'], titles:{Chinese:'平凡的世界'}, blurbs:{Chinese:'改革开放年代两兄弟在陕北黄土地上的奋斗与爱情。'} },
  { id:'whitedeerplain', author:'陈忠实 Chen Zhongshi', year:1993, place:'西安 Xi\'an (Shaanxi)', country:'China', lng:108.9600, lat:34.3500, tier:2, relation:'set', rating:4.21, pages:540,
    languages:['Chinese'], titles:{Chinese:'白鹿原'}, blurbs:{Chinese:'白、鹿两家在陕西关中平原上半个世纪的兴衰恩怨。'} },
  // Tier 3
  { id:'bloodmerchant', author:'余华 Yu Hua', year:1995, place:'small-town China', country:'China', lng:120.16, lat:30.27, tier:3, relation:'set', rating:4.27, pages:246,
    languages:['Chinese'], titles:{Chinese:'许三观卖血记'}, blurbs:{Chinese:'许三观靠卖血度过一次次家庭与时代的危机。'} },
  { id:'teahouse', author:'老舍 Lao She', year:1957, place:'北京 Beijing (Wangfujing)', country:'China', lng:116.4131, lat:39.9059, tier:3, relation:'set', rating:4.31, pages:100,
    languages:['Chinese'], titles:{Chinese:'茶馆'}, blurbs:{Chinese:'一家北京老茶馆见证三个中国时代的兴亡更替。'} },
  { id:'brothers', author:'余华 Yu Hua', year:2005, place:'small-town China', country:'China', lng:120.18, lat:30.28, tier:3, relation:'set', rating:4.05, pages:640,
    languages:['Chinese'], titles:{Chinese:'兄弟'}, blurbs:{Chinese:'一对继兄弟在文革与改革开放中迥异的命运。'} },
  { id:'family', author:'巴金 Ba Jin', year:1933, place:'成都 Chengdu', country:'China', lng:104.0668, lat:30.5828, tier:3, relation:'set', rating:4.07, pages:300,
    languages:['Chinese'], titles:{Chinese:'家'}, blurbs:{Chinese:'成都一个旧式大家族中年轻一代对封建礼教的反抗。'} },
  { id:'midnight', author:'茅盾 Mao Dun', year:1933, place:'上海 Shanghai', country:'China', lng:121.47, lat:31.31, tier:3, relation:'set', rating:4.16, pages:565,
    languages:['Chinese'], titles:{Chinese:'子夜'}, blurbs:{Chinese:'1930年代上海资本家吴荪甫在金融风暴中的覆灭。'} },
  { id:'thunderstorm', author:'曹禺 Cao Yu', year:1934, place:'北京 Beijing (Yongdingmen)', country:'China', lng:116.4140, lat:39.8650, tier:3, relation:'set', rating:4.20, pages:100,
    languages:['Chinese'], titles:{Chinese:'雷雨'}, blurbs:{Chinese:'一个旧式大家族在一个雷雨之夜被秘密与命运彻底击碎。'} },

  // ============================================================
  // French (20)
  // ============================================================
  // Tier 1
  { id:'lesmis', author:'Victor Hugo', year:1862, place:'Paris', country:'France', lng:2.370, lat:48.864, tier:1, relation:'set', rating:4.21, pages:1463,
    languages:['French'], titles:{French:'Les Misérables'}, blurbs:{French:'Barricades, rédemption et bas-fonds du Paris du XIXᵉ siècle.'} },
  { id:'proust', author:'Marcel Proust', year:1913, place:'Illiers-Combray', country:'France', lng:1.2469, lat:48.2997, tier:1, relation:'set', rating:4.06, pages:3000,
    languages:['French'], titles:{French:'À la recherche du temps perdu'}, blurbs:{French:'La mémoire dévidée par le goût d\'une seule madeleine.'} },
  { id:'stranger', author:'Albert Camus', year:1942, place:'Alger', country:'Algeria', lng:3.0588, lat:36.7538, tier:1, relation:'set', rating:4.02, pages:123,
    languages:['French'], titles:{French:'L\'Étranger'}, blurbs:{French:'L\'indifférence d\'un employé sous le soleil aveuglant de l\'Algérie.'} },
  { id:'plague', author:'Albert Camus', year:1947, place:'Oran', country:'Algeria', lng:-0.6349, lat:35.6987, tier:1, relation:'set', rating:4.04, pages:308,
    languages:['French'], titles:{French:'La Peste'}, blurbs:{French:'Une ville côtière fermée par une épidémie de peste.'} },
  { id:'montecristo', author:'Alexandre Dumas', year:1844, place:'Marseille', country:'France', lng:5.3698, lat:43.2965, tier:1, relation:'set', rating:4.30, pages:1276,
    languages:['French'], titles:{French:'Le Comte de Monte-Cristo'}, blurbs:{French:'Un marin injustement emprisonné revient pour ruiner ses traîtres.'} },
  { id:'mousquetaires', author:'Alexandre Dumas', year:1844, place:'Paris', country:'France', lng:2.334, lat:48.864, tier:1, relation:'set', rating:4.10, pages:700,
    languages:['French'], titles:{French:'Les Trois Mousquetaires'}, blurbs:{French:'Intrigues et cape et épée sous le règne de Louis XIII.'} },
  { id:'petitprince', author:'Antoine de Saint-Exupéry', year:1943, place:'Sahara', country:'Sahara desert', lng:11.8389, lat:23.4162, tier:1, relation:'set', rating:4.32, pages:96,
    languages:['French'], titles:{French:'Le Petit Prince'}, blurbs:{French:'Un pilote rencontre un petit prince au milieu des dunes du Sahara.'} },
  // Tier 2
  { id:'voyagenuit', author:'Louis-Ferdinand Céline', year:1932, place:'Paris', country:'France', lng:2.345, lat:48.887, tier:2, relation:'set', rating:4.05, pages:504,
    languages:['French'], titles:{French:'Voyage au bout de la nuit'}, blurbs:{French:'Une traversée bilieuse de la guerre, des colonies et des banlieues.'} },
  { id:'germinal', author:'Émile Zola', year:1885, place:'Lille (Nord)', country:'France', lng:3.0573, lat:50.6292, tier:2, relation:'set', rating:4.13, pages:531,
    languages:['French'], titles:{French:'Germinal'}, blurbs:{French:'Des mineurs de charbon se révoltent contre les patrons et la faim.'} },
  { id:'belami', author:'Guy de Maupassant', year:1885, place:'Paris', country:'France', lng:2.330, lat:48.873, tier:2, relation:'set', rating:4.04, pages:352,
    languages:['French'], titles:{French:'Bel-Ami'}, blurbs:{French:'Un bel opportuniste grimpe les échelons de la société parisienne.'} },
  { id:'belledusg', author:'Albert Cohen', year:1968, place:'Geneva', country:'Switzerland', lng:6.1432, lat:46.2044, tier:2, relation:'set', rating:4.36, pages:1100,
    languages:['French'], titles:{French:'Belle du Seigneur'}, blurbs:{French:'La passion obsessionnelle d\'un diplomate pour la femme d\'un collègue.'} },
  { id:'suitefr', author:'Irène Némirovsky', year:2004, place:'Issy-l\'Évêque (Burgundy)', country:'France', lng:4.0833, lat:46.7167, tier:2, relation:'set', rating:4.13, pages:416,
    languages:['French'], titles:{French:'Suite française'}, blurbs:{French:'Des vies à travers la France pendant l\'invasion allemande de 1940.'} },
  { id:'chagrinec', author:'Daniel Pennac', year:2007, place:'Paris', country:'France', lng:2.346, lat:48.846, tier:2, relation:'about', rating:4.07, pages:304,
    languages:['French'], titles:{French:'Chagrin d\'école'}, blurbs:{French:'Un romancier se retourne sur sa vie d\'élève cancre.'} },
  { id:'hadrien', author:'Marguerite Yourcenar', year:1951, place:'Rome', country:'Italy', lng:12.4964, lat:41.9028, tier:2, relation:'set', rating:4.18, pages:293,
    languages:['French'], titles:{French:'Mémoires d\'Hadrien'}, blurbs:{French:'L\'empereur mourant médite sur sa vie et son règne.'} },
  // Tier 3
  { id:'oeuvrenoir', author:'Marguerite Yourcenar', year:1968, place:'Bruges', country:'Belgium', lng:3.2247, lat:51.2093, tier:3, relation:'set', rating:4.16, pages:382,
    languages:['French'], titles:{French:'L\'Œuvre au noir'}, blurbs:{French:'Un alchimiste de la Renaissance entre hérésie et raison.'} },
  { id:'promesseaube', author:'Romain Gary', year:1960, place:'Nice', country:'France', lng:7.2620, lat:43.7102, tier:3, relation:'about', rating:4.36, pages:320,
    languages:['French'], titles:{French:'La Promesse de l\'aube'}, blurbs:{French:'Le mémoire d\'un fils sur sa mère farouche et impossible.'} },
  { id:'viedevant', author:'Romain Gary (Émile Ajar)', year:1975, place:'Paris (Belleville)', country:'France', lng:2.3800, lat:48.8800, tier:3, relation:'set', rating:4.27, pages:243,
    languages:['French'], titles:{French:'La Vie devant soi'}, blurbs:{French:'Un garçon arabe élevé par une vieille femme juive à Belleville.'} },
  { id:'lelion', author:'Joseph Kessel', year:1958, place:'Amboseli', country:'Kenya', lng:37.2606, lat:-2.6532, tier:3, relation:'set', rating:4.21, pages:216,
    languages:['French'], titles:{French:'Le Lion'}, blurbs:{French:'Une fillette, un lion et un guerrier masaï dans l\'Afrique coloniale.'} },
  { id:'longdimanche', author:'Sébastien Japrisot', year:1991, place:'Brittany', country:'France', lng:-2.9326, lat:48.2020, tier:3, relation:'set', rating:4.13, pages:287,
    languages:['French'], titles:{French:'Un long dimanche de fiançailles'}, blurbs:{French:'Une femme cherche son fiancé déclaré mort dans les tranchées.'} },
  { id:'hussardtoit', author:'Jean Giono', year:1951, place:'Manosque (Provence)', country:'France', lng:5.7855, lat:43.8284, tier:3, relation:'set', rating:4.05, pages:376,
    languages:['French'], titles:{French:'Le Hussard sur le toit'}, blurbs:{French:'Un jeune hussard italien fuit le choléra par les toits de Provence.'} },
];
