export interface City {
  name: string;
  country: string;
  lng: number;
  lat: number;
  /** 'capital' = capital of a UN member state · 'major' = significant non-capital city. */
  type: 'capital' | 'major';
}

/**
 * World cities. Capitals of UN member states + a curated set of major non-capital
 * cities, selected by population, economic weight (regional/global hub), and
 * historical/cultural significance. Rendered as muted dots+labels that fade in
 * only at high zoom (k≈80→100), so they act as navigation context — never
 * visual noise at low zoom.
 */
export const CITIES: City[] = [
  // ============ CAPITALS — Europe ============
  { name: 'Tirana', country: 'Albania', lng: 19.82, lat: 41.33, type: 'capital' },
  { name: 'Andorra la Vella', country: 'Andorra', lng: 1.52, lat: 42.51, type: 'capital' },
  { name: 'Vienna', country: 'Austria', lng: 16.37, lat: 48.21, type: 'capital' },
  { name: 'Minsk', country: 'Belarus', lng: 27.57, lat: 53.90, type: 'capital' },
  { name: 'Brussels', country: 'Belgium', lng: 4.35, lat: 50.85, type: 'capital' },
  { name: 'Sarajevo', country: 'Bosnia and Herzegovina', lng: 18.41, lat: 43.85, type: 'capital' },
  { name: 'Sofia', country: 'Bulgaria', lng: 23.32, lat: 42.70, type: 'capital' },
  { name: 'Zagreb', country: 'Croatia', lng: 15.98, lat: 45.81, type: 'capital' },
  { name: 'Nicosia', country: 'Cyprus', lng: 33.38, lat: 35.17, type: 'capital' },
  { name: 'Prague', country: 'Czech Republic', lng: 14.42, lat: 50.08, type: 'capital' },
  { name: 'Copenhagen', country: 'Denmark', lng: 12.57, lat: 55.68, type: 'capital' },
  { name: 'Tallinn', country: 'Estonia', lng: 24.75, lat: 59.44, type: 'capital' },
  { name: 'Helsinki', country: 'Finland', lng: 24.94, lat: 60.17, type: 'capital' },
  { name: 'Paris', country: 'France', lng: 2.35, lat: 48.86, type: 'capital' },
  { name: 'Berlin', country: 'Germany', lng: 13.40, lat: 52.52, type: 'capital' },
  { name: 'Athens', country: 'Greece', lng: 23.73, lat: 37.98, type: 'capital' },
  { name: 'Budapest', country: 'Hungary', lng: 19.04, lat: 47.50, type: 'capital' },
  { name: 'Reykjavík', country: 'Iceland', lng: -21.94, lat: 64.15, type: 'capital' },
  { name: 'Dublin', country: 'Ireland', lng: -6.26, lat: 53.35, type: 'capital' },
  { name: 'Rome', country: 'Italy', lng: 12.50, lat: 41.90, type: 'capital' },
  { name: 'Pristina', country: 'Kosovo', lng: 21.16, lat: 42.66, type: 'capital' },
  { name: 'Riga', country: 'Latvia', lng: 24.11, lat: 56.95, type: 'capital' },
  { name: 'Vaduz', country: 'Liechtenstein', lng: 9.52, lat: 47.14, type: 'capital' },
  { name: 'Vilnius', country: 'Lithuania', lng: 25.28, lat: 54.69, type: 'capital' },
  { name: 'Luxembourg', country: 'Luxembourg', lng: 6.13, lat: 49.61, type: 'capital' },
  { name: 'Valletta', country: 'Malta', lng: 14.51, lat: 35.90, type: 'capital' },
  { name: 'Chișinău', country: 'Moldova', lng: 28.86, lat: 47.01, type: 'capital' },
  { name: 'Monaco', country: 'Monaco', lng: 7.42, lat: 43.74, type: 'capital' },
  { name: 'Podgorica', country: 'Montenegro', lng: 19.26, lat: 42.44, type: 'capital' },
  { name: 'Amsterdam', country: 'Netherlands', lng: 4.90, lat: 52.37, type: 'capital' },
  { name: 'Skopje', country: 'North Macedonia', lng: 21.43, lat: 41.99, type: 'capital' },
  { name: 'Oslo', country: 'Norway', lng: 10.75, lat: 59.91, type: 'capital' },
  { name: 'Warsaw', country: 'Poland', lng: 21.01, lat: 52.23, type: 'capital' },
  { name: 'Lisbon', country: 'Portugal', lng: -9.14, lat: 38.72, type: 'capital' },
  { name: 'Bucharest', country: 'Romania', lng: 26.10, lat: 44.43, type: 'capital' },
  { name: 'Moscow', country: 'Russia', lng: 37.62, lat: 55.76, type: 'capital' },
  { name: 'San Marino', country: 'San Marino', lng: 12.45, lat: 43.94, type: 'capital' },
  { name: 'Belgrade', country: 'Serbia', lng: 20.46, lat: 44.79, type: 'capital' },
  { name: 'Bratislava', country: 'Slovakia', lng: 17.11, lat: 48.15, type: 'capital' },
  { name: 'Ljubljana', country: 'Slovenia', lng: 14.51, lat: 46.06, type: 'capital' },
  { name: 'Madrid', country: 'Spain', lng: -3.70, lat: 40.42, type: 'capital' },
  { name: 'Stockholm', country: 'Sweden', lng: 18.07, lat: 59.33, type: 'capital' },
  { name: 'Bern', country: 'Switzerland', lng: 7.45, lat: 46.95, type: 'capital' },
  { name: 'Kyiv', country: 'Ukraine', lng: 30.52, lat: 50.45, type: 'capital' },
  { name: 'London', country: 'United Kingdom', lng: -0.13, lat: 51.51, type: 'capital' },
  { name: 'Vatican City', country: 'Vatican City', lng: 12.45, lat: 41.90, type: 'capital' },

  // ============ CAPITALS — Asia ============
  { name: 'Kabul', country: 'Afghanistan', lng: 69.20, lat: 34.55, type: 'capital' },
  { name: 'Yerevan', country: 'Armenia', lng: 44.51, lat: 40.18, type: 'capital' },
  { name: 'Baku', country: 'Azerbaijan', lng: 49.86, lat: 40.41, type: 'capital' },
  { name: 'Manama', country: 'Bahrain', lng: 50.59, lat: 26.22, type: 'capital' },
  { name: 'Dhaka', country: 'Bangladesh', lng: 90.41, lat: 23.81, type: 'capital' },
  { name: 'Thimphu', country: 'Bhutan', lng: 89.64, lat: 27.47, type: 'capital' },
  { name: 'Bandar Seri Begawan', country: 'Brunei', lng: 114.94, lat: 4.94, type: 'capital' },
  { name: 'Phnom Penh', country: 'Cambodia', lng: 104.92, lat: 11.56, type: 'capital' },
  { name: 'Beijing', country: 'China', lng: 116.41, lat: 39.90, type: 'capital' },
  { name: 'Tbilisi', country: 'Georgia', lng: 44.79, lat: 41.72, type: 'capital' },
  { name: 'New Delhi', country: 'India', lng: 77.20, lat: 28.61, type: 'capital' },
  { name: 'Jakarta', country: 'Indonesia', lng: 106.84, lat: -6.21, type: 'capital' },
  { name: 'Tehran', country: 'Iran', lng: 51.39, lat: 35.69, type: 'capital' },
  { name: 'Baghdad', country: 'Iraq', lng: 44.36, lat: 33.31, type: 'capital' },
  { name: 'Jerusalem', country: 'Israel', lng: 35.21, lat: 31.77, type: 'capital' },
  { name: 'Tokyo', country: 'Japan', lng: 139.69, lat: 35.69, type: 'capital' },
  { name: 'Amman', country: 'Jordan', lng: 35.93, lat: 31.95, type: 'capital' },
  { name: 'Astana', country: 'Kazakhstan', lng: 71.43, lat: 51.13, type: 'capital' },
  { name: 'Kuwait City', country: 'Kuwait', lng: 47.97, lat: 29.38, type: 'capital' },
  { name: 'Bishkek', country: 'Kyrgyzstan', lng: 74.69, lat: 42.87, type: 'capital' },
  { name: 'Vientiane', country: 'Laos', lng: 102.63, lat: 17.97, type: 'capital' },
  { name: 'Beirut', country: 'Lebanon', lng: 35.50, lat: 33.89, type: 'capital' },
  { name: 'Kuala Lumpur', country: 'Malaysia', lng: 101.69, lat: 3.14, type: 'capital' },
  { name: 'Malé', country: 'Maldives', lng: 73.51, lat: 4.18, type: 'capital' },
  { name: 'Ulaanbaatar', country: 'Mongolia', lng: 106.92, lat: 47.92, type: 'capital' },
  { name: 'Naypyidaw', country: 'Myanmar', lng: 96.07, lat: 19.76, type: 'capital' },
  { name: 'Kathmandu', country: 'Nepal', lng: 85.32, lat: 27.72, type: 'capital' },
  { name: 'Pyongyang', country: 'North Korea', lng: 125.75, lat: 39.02, type: 'capital' },
  { name: 'Muscat', country: 'Oman', lng: 58.59, lat: 23.59, type: 'capital' },
  { name: 'Islamabad', country: 'Pakistan', lng: 73.05, lat: 33.69, type: 'capital' },
  { name: 'Manila', country: 'Philippines', lng: 120.98, lat: 14.60, type: 'capital' },
  { name: 'Doha', country: 'Qatar', lng: 51.53, lat: 25.29, type: 'capital' },
  { name: 'Riyadh', country: 'Saudi Arabia', lng: 46.67, lat: 24.71, type: 'capital' },
  { name: 'Singapore', country: 'Singapore', lng: 103.82, lat: 1.35, type: 'capital' },
  { name: 'Seoul', country: 'South Korea', lng: 126.98, lat: 37.57, type: 'capital' },
  { name: 'Colombo', country: 'Sri Lanka', lng: 79.86, lat: 6.93, type: 'capital' },
  { name: 'Damascus', country: 'Syria', lng: 36.30, lat: 33.51, type: 'capital' },
  { name: 'Taipei', country: 'Taiwan', lng: 121.57, lat: 25.03, type: 'capital' },
  { name: 'Dushanbe', country: 'Tajikistan', lng: 68.78, lat: 38.55, type: 'capital' },
  { name: 'Bangkok', country: 'Thailand', lng: 100.50, lat: 13.76, type: 'capital' },
  { name: 'Dili', country: 'Timor-Leste', lng: 125.58, lat: -8.56, type: 'capital' },
  { name: 'Ankara', country: 'Turkey', lng: 32.85, lat: 39.93, type: 'capital' },
  { name: 'Ashgabat', country: 'Turkmenistan', lng: 58.38, lat: 37.95, type: 'capital' },
  { name: 'Abu Dhabi', country: 'UAE', lng: 54.37, lat: 24.45, type: 'capital' },
  { name: 'Tashkent', country: 'Uzbekistan', lng: 69.24, lat: 41.30, type: 'capital' },
  { name: 'Hanoi', country: 'Vietnam', lng: 105.83, lat: 21.03, type: 'capital' },
  { name: 'Sanaa', country: 'Yemen', lng: 44.21, lat: 15.37, type: 'capital' },

  // ============ CAPITALS — Africa ============
  { name: 'Algiers', country: 'Algeria', lng: 3.04, lat: 36.75, type: 'capital' },
  { name: 'Luanda', country: 'Angola', lng: 13.23, lat: -8.84, type: 'capital' },
  { name: 'Porto-Novo', country: 'Benin', lng: 2.63, lat: 6.50, type: 'capital' },
  { name: 'Gaborone', country: 'Botswana', lng: 25.91, lat: -24.65, type: 'capital' },
  { name: 'Ouagadougou', country: 'Burkina Faso', lng: -1.53, lat: 12.37, type: 'capital' },
  { name: 'Gitega', country: 'Burundi', lng: 29.93, lat: -3.43, type: 'capital' },
  { name: 'Yaoundé', country: 'Cameroon', lng: 11.51, lat: 3.85, type: 'capital' },
  { name: 'Praia', country: 'Cape Verde', lng: -23.51, lat: 14.93, type: 'capital' },
  { name: 'Bangui', country: 'Central African Republic', lng: 18.56, lat: 4.36, type: 'capital' },
  { name: 'N\'Djamena', country: 'Chad', lng: 15.05, lat: 12.13, type: 'capital' },
  { name: 'Moroni', country: 'Comoros', lng: 43.26, lat: -11.71, type: 'capital' },
  { name: 'Kinshasa', country: 'DR Congo', lng: 15.27, lat: -4.33, type: 'capital' },
  { name: 'Brazzaville', country: 'Republic of Congo', lng: 15.28, lat: -4.27, type: 'capital' },
  { name: 'Yamoussoukro', country: 'Côte d\'Ivoire', lng: -5.27, lat: 6.83, type: 'capital' },
  { name: 'Djibouti', country: 'Djibouti', lng: 43.15, lat: 11.59, type: 'capital' },
  { name: 'Cairo', country: 'Egypt', lng: 31.24, lat: 30.04, type: 'capital' },
  { name: 'Malabo', country: 'Equatorial Guinea', lng: 8.78, lat: 3.75, type: 'capital' },
  { name: 'Asmara', country: 'Eritrea', lng: 38.93, lat: 15.33, type: 'capital' },
  { name: 'Mbabane', country: 'Eswatini', lng: 31.13, lat: -26.31, type: 'capital' },
  { name: 'Addis Ababa', country: 'Ethiopia', lng: 38.75, lat: 9.03, type: 'capital' },
  { name: 'Libreville', country: 'Gabon', lng: 9.45, lat: 0.41, type: 'capital' },
  { name: 'Banjul', country: 'Gambia', lng: -16.59, lat: 13.45, type: 'capital' },
  { name: 'Accra', country: 'Ghana', lng: -0.19, lat: 5.60, type: 'capital' },
  { name: 'Conakry', country: 'Guinea', lng: -13.71, lat: 9.51, type: 'capital' },
  { name: 'Bissau', country: 'Guinea-Bissau', lng: -15.60, lat: 11.86, type: 'capital' },
  { name: 'Nairobi', country: 'Kenya', lng: 36.82, lat: -1.29, type: 'capital' },
  { name: 'Maseru', country: 'Lesotho', lng: 27.49, lat: -29.31, type: 'capital' },
  { name: 'Monrovia', country: 'Liberia', lng: -10.80, lat: 6.30, type: 'capital' },
  { name: 'Tripoli', country: 'Libya', lng: 13.19, lat: 32.89, type: 'capital' },
  { name: 'Antananarivo', country: 'Madagascar', lng: 47.52, lat: -18.88, type: 'capital' },
  { name: 'Lilongwe', country: 'Malawi', lng: 33.79, lat: -13.96, type: 'capital' },
  { name: 'Bamako', country: 'Mali', lng: -7.99, lat: 12.65, type: 'capital' },
  { name: 'Nouakchott', country: 'Mauritania', lng: -15.97, lat: 18.07, type: 'capital' },
  { name: 'Port Louis', country: 'Mauritius', lng: 57.50, lat: -20.16, type: 'capital' },
  { name: 'Rabat', country: 'Morocco', lng: -6.84, lat: 34.02, type: 'capital' },
  { name: 'Maputo', country: 'Mozambique', lng: 32.59, lat: -25.97, type: 'capital' },
  { name: 'Windhoek', country: 'Namibia', lng: 17.08, lat: -22.56, type: 'capital' },
  { name: 'Niamey', country: 'Niger', lng: 2.13, lat: 13.51, type: 'capital' },
  { name: 'Abuja', country: 'Nigeria', lng: 7.49, lat: 9.06, type: 'capital' },
  { name: 'Kigali', country: 'Rwanda', lng: 30.06, lat: -1.94, type: 'capital' },
  { name: 'São Tomé', country: 'São Tomé and Príncipe', lng: 6.73, lat: 0.34, type: 'capital' },
  { name: 'Dakar', country: 'Senegal', lng: -17.45, lat: 14.69, type: 'capital' },
  { name: 'Victoria', country: 'Seychelles', lng: 55.45, lat: -4.62, type: 'capital' },
  { name: 'Freetown', country: 'Sierra Leone', lng: -13.23, lat: 8.46, type: 'capital' },
  { name: 'Mogadishu', country: 'Somalia', lng: 45.34, lat: 2.04, type: 'capital' },
  { name: 'Pretoria', country: 'South Africa', lng: 28.19, lat: -25.75, type: 'capital' },
  { name: 'Juba', country: 'South Sudan', lng: 31.58, lat: 4.85, type: 'capital' },
  { name: 'Khartoum', country: 'Sudan', lng: 32.53, lat: 15.50, type: 'capital' },
  { name: 'Dodoma', country: 'Tanzania', lng: 35.74, lat: -6.16, type: 'capital' },
  { name: 'Lomé', country: 'Togo', lng: 1.21, lat: 6.13, type: 'capital' },
  { name: 'Tunis', country: 'Tunisia', lng: 10.18, lat: 36.81, type: 'capital' },
  { name: 'Kampala', country: 'Uganda', lng: 32.58, lat: 0.32, type: 'capital' },
  { name: 'Lusaka', country: 'Zambia', lng: 28.32, lat: -15.39, type: 'capital' },
  { name: 'Harare', country: 'Zimbabwe', lng: 31.05, lat: -17.83, type: 'capital' },

  // ============ CAPITALS — Americas ============
  { name: 'Buenos Aires', country: 'Argentina', lng: -58.38, lat: -34.60, type: 'capital' },
  { name: 'Nassau', country: 'Bahamas', lng: -77.35, lat: 25.05, type: 'capital' },
  { name: 'Bridgetown', country: 'Barbados', lng: -59.61, lat: 13.10, type: 'capital' },
  { name: 'Belmopan', country: 'Belize', lng: -88.77, lat: 17.25, type: 'capital' },
  { name: 'La Paz', country: 'Bolivia', lng: -68.15, lat: -16.50, type: 'capital' },
  { name: 'Brasília', country: 'Brazil', lng: -47.93, lat: -15.79, type: 'capital' },
  { name: 'Ottawa', country: 'Canada', lng: -75.70, lat: 45.42, type: 'capital' },
  { name: 'Santiago', country: 'Chile', lng: -70.65, lat: -33.46, type: 'capital' },
  { name: 'Bogotá', country: 'Colombia', lng: -74.07, lat: 4.71, type: 'capital' },
  { name: 'San José', country: 'Costa Rica', lng: -84.09, lat: 9.93, type: 'capital' },
  { name: 'Havana', country: 'Cuba', lng: -82.37, lat: 23.11, type: 'capital' },
  { name: 'Roseau', country: 'Dominica', lng: -61.39, lat: 15.30, type: 'capital' },
  { name: 'Santo Domingo', country: 'Dominican Republic', lng: -69.93, lat: 18.49, type: 'capital' },
  { name: 'Quito', country: 'Ecuador', lng: -78.47, lat: -0.18, type: 'capital' },
  { name: 'San Salvador', country: 'El Salvador', lng: -89.19, lat: 13.69, type: 'capital' },
  { name: 'St. George\'s', country: 'Grenada', lng: -61.75, lat: 12.06, type: 'capital' },
  { name: 'Guatemala City', country: 'Guatemala', lng: -90.51, lat: 14.63, type: 'capital' },
  { name: 'Georgetown', country: 'Guyana', lng: -58.16, lat: 6.80, type: 'capital' },
  { name: 'Port-au-Prince', country: 'Haiti', lng: -72.34, lat: 18.59, type: 'capital' },
  { name: 'Tegucigalpa', country: 'Honduras', lng: -87.21, lat: 14.10, type: 'capital' },
  { name: 'Kingston', country: 'Jamaica', lng: -76.79, lat: 17.97, type: 'capital' },
  { name: 'Mexico City', country: 'Mexico', lng: -99.13, lat: 19.43, type: 'capital' },
  { name: 'Managua', country: 'Nicaragua', lng: -86.27, lat: 12.13, type: 'capital' },
  { name: 'Panama City', country: 'Panama', lng: -79.52, lat: 8.97, type: 'capital' },
  { name: 'Asunción', country: 'Paraguay', lng: -57.65, lat: -25.30, type: 'capital' },
  { name: 'Lima', country: 'Peru', lng: -77.04, lat: -12.05, type: 'capital' },
  { name: 'Basseterre', country: 'Saint Kitts and Nevis', lng: -62.72, lat: 17.30, type: 'capital' },
  { name: 'Castries', country: 'Saint Lucia', lng: -61.00, lat: 14.01, type: 'capital' },
  { name: 'Kingstown', country: 'Saint Vincent', lng: -61.21, lat: 13.16, type: 'capital' },
  { name: 'Paramaribo', country: 'Suriname', lng: -55.20, lat: 5.85, type: 'capital' },
  { name: 'Port of Spain', country: 'Trinidad and Tobago', lng: -61.51, lat: 10.65, type: 'capital' },
  { name: 'Washington', country: 'United States', lng: -77.03, lat: 38.91, type: 'capital' },
  { name: 'Montevideo', country: 'Uruguay', lng: -56.20, lat: -34.90, type: 'capital' },
  { name: 'Caracas', country: 'Venezuela', lng: -66.91, lat: 10.49, type: 'capital' },

  // ============ CAPITALS — Oceania ============
  { name: 'Canberra', country: 'Australia', lng: 149.13, lat: -35.28, type: 'capital' },
  { name: 'Suva', country: 'Fiji', lng: 178.45, lat: -18.13, type: 'capital' },
  { name: 'Tarawa', country: 'Kiribati', lng: 172.97, lat: 1.33, type: 'capital' },
  { name: 'Majuro', country: 'Marshall Islands', lng: 171.18, lat: 7.10, type: 'capital' },
  { name: 'Palikir', country: 'Micronesia', lng: 158.16, lat: 6.92, type: 'capital' },
  { name: 'Yaren', country: 'Nauru', lng: 166.91, lat: -0.55, type: 'capital' },
  { name: 'Wellington', country: 'New Zealand', lng: 174.78, lat: -41.29, type: 'capital' },
  { name: 'Ngerulmud', country: 'Palau', lng: 134.62, lat: 7.50, type: 'capital' },
  { name: 'Port Moresby', country: 'Papua New Guinea', lng: 147.18, lat: -9.44, type: 'capital' },
  { name: 'Apia', country: 'Samoa', lng: -171.78, lat: -13.83, type: 'capital' },
  { name: 'Honiara', country: 'Solomon Islands', lng: 159.96, lat: -9.43, type: 'capital' },
  { name: 'Nuku\'alofa', country: 'Tonga', lng: -175.20, lat: -21.14, type: 'capital' },
  { name: 'Funafuti', country: 'Tuvalu', lng: 179.20, lat: -8.52, type: 'capital' },
  { name: 'Port Vila', country: 'Vanuatu', lng: 168.32, lat: -17.74, type: 'capital' },

  // ============ MAJOR — North America ============
  { name: 'New York', country: 'United States', lng: -74.01, lat: 40.71, type: 'major' },
  { name: 'Los Angeles', country: 'United States', lng: -118.24, lat: 34.05, type: 'major' },
  { name: 'Chicago', country: 'United States', lng: -87.65, lat: 41.85, type: 'major' },
  { name: 'Houston', country: 'United States', lng: -95.37, lat: 29.76, type: 'major' },
  { name: 'San Francisco', country: 'United States', lng: -122.42, lat: 37.77, type: 'major' },
  { name: 'Boston', country: 'United States', lng: -71.06, lat: 42.36, type: 'major' },
  { name: 'Seattle', country: 'United States', lng: -122.33, lat: 47.61, type: 'major' },
  { name: 'Miami', country: 'United States', lng: -80.19, lat: 25.76, type: 'major' },
  { name: 'Philadelphia', country: 'United States', lng: -75.17, lat: 39.95, type: 'major' },
  { name: 'Atlanta', country: 'United States', lng: -84.39, lat: 33.75, type: 'major' },
  { name: 'Dallas', country: 'United States', lng: -96.80, lat: 32.78, type: 'major' },
  { name: 'Denver', country: 'United States', lng: -104.99, lat: 39.74, type: 'major' },
  { name: 'New Orleans', country: 'United States', lng: -90.07, lat: 29.95, type: 'major' },
  { name: 'Toronto', country: 'Canada', lng: -79.38, lat: 43.65, type: 'major' },
  { name: 'Montreal', country: 'Canada', lng: -73.57, lat: 45.50, type: 'major' },
  { name: 'Vancouver', country: 'Canada', lng: -123.12, lat: 49.28, type: 'major' },
  { name: 'Calgary', country: 'Canada', lng: -114.07, lat: 51.05, type: 'major' },
  { name: 'Quebec City', country: 'Canada', lng: -71.21, lat: 46.81, type: 'major' },
  { name: 'Guadalajara', country: 'Mexico', lng: -103.35, lat: 20.66, type: 'major' },
  { name: 'Monterrey', country: 'Mexico', lng: -100.32, lat: 25.69, type: 'major' },

  // ============ MAJOR — South America ============
  { name: 'São Paulo', country: 'Brazil', lng: -46.63, lat: -23.55, type: 'major' },
  { name: 'Rio de Janeiro', country: 'Brazil', lng: -43.17, lat: -22.91, type: 'major' },
  { name: 'Salvador', country: 'Brazil', lng: -38.51, lat: -12.97, type: 'major' },
  { name: 'Belo Horizonte', country: 'Brazil', lng: -43.94, lat: -19.92, type: 'major' },
  { name: 'Córdoba', country: 'Argentina', lng: -64.18, lat: -31.42, type: 'major' },
  { name: 'Rosario', country: 'Argentina', lng: -60.65, lat: -32.95, type: 'major' },
  { name: 'Medellín', country: 'Colombia', lng: -75.57, lat: 6.25, type: 'major' },
  { name: 'Cali', country: 'Colombia', lng: -76.53, lat: 3.45, type: 'major' },
  { name: 'Cartagena', country: 'Colombia', lng: -75.51, lat: 10.39, type: 'major' },
  { name: 'Arequipa', country: 'Peru', lng: -71.54, lat: -16.41, type: 'major' },
  { name: 'Cusco', country: 'Peru', lng: -71.97, lat: -13.53, type: 'major' },
  { name: 'Valparaíso', country: 'Chile', lng: -71.62, lat: -33.05, type: 'major' },
  { name: 'Guayaquil', country: 'Ecuador', lng: -79.92, lat: -2.17, type: 'major' },

  // ============ MAJOR — Europe ============
  { name: 'Manchester', country: 'United Kingdom', lng: -2.24, lat: 53.48, type: 'major' },
  { name: 'Birmingham', country: 'United Kingdom', lng: -1.90, lat: 52.48, type: 'major' },
  { name: 'Liverpool', country: 'United Kingdom', lng: -2.99, lat: 53.41, type: 'major' },
  { name: 'Glasgow', country: 'United Kingdom', lng: -4.25, lat: 55.86, type: 'major' },
  { name: 'Edinburgh', country: 'United Kingdom', lng: -3.19, lat: 55.95, type: 'major' },
  { name: 'Hamburg', country: 'Germany', lng: 9.99, lat: 53.55, type: 'major' },
  { name: 'Munich', country: 'Germany', lng: 11.58, lat: 48.14, type: 'major' },
  { name: 'Cologne', country: 'Germany', lng: 6.96, lat: 50.94, type: 'major' },
  { name: 'Frankfurt', country: 'Germany', lng: 8.68, lat: 50.11, type: 'major' },
  { name: 'Stuttgart', country: 'Germany', lng: 9.18, lat: 48.78, type: 'major' },
  { name: 'Marseille', country: 'France', lng: 5.37, lat: 43.30, type: 'major' },
  { name: 'Lyon', country: 'France', lng: 4.83, lat: 45.76, type: 'major' },
  { name: 'Toulouse', country: 'France', lng: 1.44, lat: 43.60, type: 'major' },
  { name: 'Nice', country: 'France', lng: 7.27, lat: 43.71, type: 'major' },
  { name: 'Bordeaux', country: 'France', lng: -0.58, lat: 44.84, type: 'major' },
  { name: 'Milan', country: 'Italy', lng: 9.19, lat: 45.46, type: 'major' },
  { name: 'Naples', country: 'Italy', lng: 14.27, lat: 40.85, type: 'major' },
  { name: 'Turin', country: 'Italy', lng: 7.69, lat: 45.07, type: 'major' },
  { name: 'Florence', country: 'Italy', lng: 11.26, lat: 43.77, type: 'major' },
  { name: 'Venice', country: 'Italy', lng: 12.32, lat: 45.44, type: 'major' },
  { name: 'Barcelona', country: 'Spain', lng: 2.17, lat: 41.39, type: 'major' },
  { name: 'Valencia', country: 'Spain', lng: -0.38, lat: 39.47, type: 'major' },
  { name: 'Seville', country: 'Spain', lng: -5.99, lat: 37.39, type: 'major' },
  { name: 'Bilbao', country: 'Spain', lng: -2.93, lat: 43.26, type: 'major' },
  { name: 'Rotterdam', country: 'Netherlands', lng: 4.48, lat: 51.92, type: 'major' },
  { name: 'The Hague', country: 'Netherlands', lng: 4.30, lat: 52.07, type: 'major' },
  { name: 'Antwerp', country: 'Belgium', lng: 4.40, lat: 51.22, type: 'major' },
  { name: 'Ghent', country: 'Belgium', lng: 3.73, lat: 51.05, type: 'major' },
  { name: 'Zurich', country: 'Switzerland', lng: 8.55, lat: 47.37, type: 'major' },
  { name: 'Geneva', country: 'Switzerland', lng: 6.14, lat: 46.20, type: 'major' },
  { name: 'Basel', country: 'Switzerland', lng: 7.59, lat: 47.56, type: 'major' },
  { name: 'Krakow', country: 'Poland', lng: 19.94, lat: 50.06, type: 'major' },
  { name: 'Wrocław', country: 'Poland', lng: 17.04, lat: 51.11, type: 'major' },
  { name: 'Gdańsk', country: 'Poland', lng: 18.65, lat: 54.35, type: 'major' },
  { name: 'St. Petersburg', country: 'Russia', lng: 30.34, lat: 59.93, type: 'major' },
  { name: 'Novosibirsk', country: 'Russia', lng: 82.91, lat: 55.04, type: 'major' },
  { name: 'Yekaterinburg', country: 'Russia', lng: 60.61, lat: 56.84, type: 'major' },
  { name: 'Vladivostok', country: 'Russia', lng: 131.89, lat: 43.12, type: 'major' },
  { name: 'Kharkiv', country: 'Ukraine', lng: 36.23, lat: 49.99, type: 'major' },
  { name: 'Odesa', country: 'Ukraine', lng: 30.74, lat: 46.48, type: 'major' },
  { name: 'Lviv', country: 'Ukraine', lng: 24.03, lat: 49.84, type: 'major' },
  { name: 'Gothenburg', country: 'Sweden', lng: 11.97, lat: 57.71, type: 'major' },
  { name: 'Thessaloniki', country: 'Greece', lng: 22.94, lat: 40.64, type: 'major' },
  { name: 'Porto', country: 'Portugal', lng: -8.61, lat: 41.15, type: 'major' },
  { name: 'Istanbul', country: 'Turkey', lng: 28.98, lat: 41.01, type: 'major' },
  { name: 'Izmir', country: 'Turkey', lng: 27.14, lat: 38.42, type: 'major' },

  // ============ MAJOR — Asia ============
  { name: 'Shanghai', country: 'China', lng: 121.47, lat: 31.23, type: 'major' },
  { name: 'Shenzhen', country: 'China', lng: 114.06, lat: 22.54, type: 'major' },
  { name: 'Guangzhou', country: 'China', lng: 113.27, lat: 23.13, type: 'major' },
  { name: 'Chongqing', country: 'China', lng: 106.55, lat: 29.56, type: 'major' },
  { name: 'Tianjin', country: 'China', lng: 117.20, lat: 39.13, type: 'major' },
  { name: 'Wuhan', country: 'China', lng: 114.30, lat: 30.59, type: 'major' },
  { name: 'Chengdu', country: 'China', lng: 104.07, lat: 30.57, type: 'major' },
  { name: 'Xi\'an', country: 'China', lng: 108.94, lat: 34.34, type: 'major' },
  { name: 'Hangzhou', country: 'China', lng: 120.16, lat: 30.27, type: 'major' },
  { name: 'Nanjing', country: 'China', lng: 118.78, lat: 32.06, type: 'major' },
  { name: 'Qingdao', country: 'China', lng: 120.38, lat: 36.07, type: 'major' },
  { name: 'Hong Kong', country: 'China', lng: 114.17, lat: 22.32, type: 'major' },
  { name: 'Macau', country: 'China', lng: 113.55, lat: 22.20, type: 'major' },
  { name: 'Mumbai', country: 'India', lng: 72.88, lat: 19.08, type: 'major' },
  { name: 'Kolkata', country: 'India', lng: 88.36, lat: 22.57, type: 'major' },
  { name: 'Chennai', country: 'India', lng: 80.27, lat: 13.08, type: 'major' },
  { name: 'Bengaluru', country: 'India', lng: 77.59, lat: 12.97, type: 'major' },
  { name: 'Hyderabad', country: 'India', lng: 78.49, lat: 17.39, type: 'major' },
  { name: 'Ahmedabad', country: 'India', lng: 72.57, lat: 23.02, type: 'major' },
  { name: 'Karachi', country: 'Pakistan', lng: 67.01, lat: 24.86, type: 'major' },
  { name: 'Lahore', country: 'Pakistan', lng: 74.36, lat: 31.55, type: 'major' },
  { name: 'Chittagong', country: 'Bangladesh', lng: 91.78, lat: 22.36, type: 'major' },
  { name: 'Osaka', country: 'Japan', lng: 135.50, lat: 34.69, type: 'major' },
  { name: 'Yokohama', country: 'Japan', lng: 139.64, lat: 35.44, type: 'major' },
  { name: 'Nagoya', country: 'Japan', lng: 136.91, lat: 35.18, type: 'major' },
  { name: 'Kyoto', country: 'Japan', lng: 135.77, lat: 35.01, type: 'major' },
  { name: 'Sapporo', country: 'Japan', lng: 141.35, lat: 43.06, type: 'major' },
  { name: 'Fukuoka', country: 'Japan', lng: 130.40, lat: 33.59, type: 'major' },
  { name: 'Hiroshima', country: 'Japan', lng: 132.46, lat: 34.39, type: 'major' },
  { name: 'Busan', country: 'South Korea', lng: 129.08, lat: 35.18, type: 'major' },
  { name: 'Incheon', country: 'South Korea', lng: 126.71, lat: 37.46, type: 'major' },
  { name: 'Kaohsiung', country: 'Taiwan', lng: 120.31, lat: 22.63, type: 'major' },
  { name: 'Taichung', country: 'Taiwan', lng: 120.68, lat: 24.15, type: 'major' },
  { name: 'Ho Chi Minh City', country: 'Vietnam', lng: 106.66, lat: 10.78, type: 'major' },
  { name: 'Da Nang', country: 'Vietnam', lng: 108.22, lat: 16.05, type: 'major' },
  { name: 'Chiang Mai', country: 'Thailand', lng: 98.99, lat: 18.79, type: 'major' },
  { name: 'Surabaya', country: 'Indonesia', lng: 112.75, lat: -7.26, type: 'major' },
  { name: 'Bandung', country: 'Indonesia', lng: 107.61, lat: -6.91, type: 'major' },
  { name: 'Cebu', country: 'Philippines', lng: 123.89, lat: 10.31, type: 'major' },
  { name: 'Davao', country: 'Philippines', lng: 125.61, lat: 7.07, type: 'major' },
  { name: 'Penang', country: 'Malaysia', lng: 100.33, lat: 5.41, type: 'major' },
  { name: 'Almaty', country: 'Kazakhstan', lng: 76.93, lat: 43.24, type: 'major' },
  { name: 'Samarkand', country: 'Uzbekistan', lng: 66.97, lat: 39.65, type: 'major' },

  // ============ MAJOR — Middle East ============
  { name: 'Dubai', country: 'UAE', lng: 55.27, lat: 25.20, type: 'major' },
  { name: 'Jeddah', country: 'Saudi Arabia', lng: 39.20, lat: 21.49, type: 'major' },
  { name: 'Mecca', country: 'Saudi Arabia', lng: 39.83, lat: 21.42, type: 'major' },
  { name: 'Medina', country: 'Saudi Arabia', lng: 39.61, lat: 24.47, type: 'major' },
  { name: 'Tel Aviv', country: 'Israel', lng: 34.78, lat: 32.08, type: 'major' },
  { name: 'Isfahan', country: 'Iran', lng: 51.67, lat: 32.65, type: 'major' },
  { name: 'Mashhad', country: 'Iran', lng: 59.61, lat: 36.31, type: 'major' },
  { name: 'Basra', country: 'Iraq', lng: 47.78, lat: 30.51, type: 'major' },

  // ============ MAJOR — Africa ============
  { name: 'Casablanca', country: 'Morocco', lng: -7.59, lat: 33.57, type: 'major' },
  { name: 'Marrakesh', country: 'Morocco', lng: -7.98, lat: 31.63, type: 'major' },
  { name: 'Fez', country: 'Morocco', lng: -5.00, lat: 34.04, type: 'major' },
  { name: 'Alexandria', country: 'Egypt', lng: 29.92, lat: 31.20, type: 'major' },
  { name: 'Oran', country: 'Algeria', lng: -0.64, lat: 35.70, type: 'major' },
  { name: 'Lagos', country: 'Nigeria', lng: 3.38, lat: 6.45, type: 'major' },
  { name: 'Cape Town', country: 'South Africa', lng: 18.42, lat: -33.92, type: 'major' },
  { name: 'Johannesburg', country: 'South Africa', lng: 28.05, lat: -26.20, type: 'major' },
  { name: 'Durban', country: 'South Africa', lng: 31.03, lat: -29.86, type: 'major' },
  { name: 'Mombasa', country: 'Kenya', lng: 39.67, lat: -4.04, type: 'major' },
  { name: 'Dar es Salaam', country: 'Tanzania', lng: 39.27, lat: -6.79, type: 'major' },
  { name: 'Abidjan', country: 'Côte d\'Ivoire', lng: -4.02, lat: 5.36, type: 'major' },

  // ============ MAJOR — Oceania ============
  { name: 'Sydney', country: 'Australia', lng: 151.21, lat: -33.87, type: 'major' },
  { name: 'Melbourne', country: 'Australia', lng: 144.96, lat: -37.81, type: 'major' },
  { name: 'Brisbane', country: 'Australia', lng: 153.03, lat: -27.47, type: 'major' },
  { name: 'Perth', country: 'Australia', lng: 115.86, lat: -31.95, type: 'major' },
  { name: 'Auckland', country: 'New Zealand', lng: 174.76, lat: -36.85, type: 'major' },
];
