const COUNTRY_ZH: Record<string, string> = {
  'Afghanistan':              '阿富汗',
  'Algeria':                  '阿尔及利亚',
  'Argentina':                '阿根廷',
  'Australia':                '澳大利亚',
  'Belgium':                  '比利时',
  'Bosnia and Herzegovina':   '波黑',
  'Brazil':                   '巴西',
  'Canada':                   '加拿大',
  'Caribbean (near Trinidad)':'加勒比海',
  'Channel Islands':          '海峡群岛',
  'China':                    '中国',
  'Colombia':                 '哥伦比亚',
  'Czech Republic':           '捷克',
  'Dominican Republic':       '多明尼加',
  'Egypt':                    '埃及',
  'Ethiopia':                 '埃塞俄比亚',
  'France':                   '法国',
  'Germany':                  '德国',
  'Hungary':                  '匈牙利',
  'India':                    '印度',
  'Italy':                    '意大利',
  'Japan':                    '日本',
  'Kenya':                    '肯尼亚',
  'Malaysia':                 '马来西亚',
  'Mexico':                   '墨西哥',
  'Morocco':                  '摩洛哥',
  'Myanmar':                  '缅甸',
  'Nigeria':                  '尼日利亚',
  'Peru':                     '秘鲁',
  'Poland':                   '波兰',
  'Russia':                   '俄罗斯',
  'Spain':                    '西班牙',
  'Venezuela':                '委内瑞拉',
  'Iran':                     '伊朗',
  'Sahara desert':            '撒哈拉沙漠',
  'Serbia':                   '塞尔维亚',
  'South Africa':             '南非',
  'Switzerland':              '瑞士',
  'the high seas':            '公海',
  'Türkiye':                  '土耳其',
  'UK':                       '英国',
  'United Kingdom':           '英国',
  'USA':                      '美国',
};

const PLACE_ZH: Record<string, string> = {
  // Author timeline cities
  'Aracataca':                      '阿拉卡塔卡',
  'Bogotá / Barranquilla':          '波哥大 / 巴兰基亚',
  'Caracas':                        '加拉加斯',
  'Mexico City':                    '墨西哥城',
  'Barcelona':                      '巴塞罗那',
  'Besançon':                       '贝桑松',
  'Brussels':                       '布鲁塞尔',
  'Jersey':                         '泽西岛',
  'Guernsey':                       '根西岛',
  'Motihari':                       '莫蒂哈里',
  'Henley / Eton':                  '亨利 / 伊顿',
  'Mandalay':                       '曼德勒',
  'Marrakech':                      '马拉喀什',
  'Jura':                           '朱拉岛',
  'Shanghai':                       '上海',
  'Lunghua Camp, Shanghai':         '上海·龙华集中营',
  'Cambridge':                      '剑桥',
  'Shepperton':                     '谢珀顿',
  'Tehran':                         '德黑兰',
  'San Jose':                       '圣何塞',
  'Nagasaki':                       '长崎',
  'Guildford':                      '吉尔福德',
  'Edinburgh':                      '爱丁堡',
  'Norwich':                        '诺里奇',
  'Saint Paul, MN':                 '圣保罗（明尼苏达州）',
  'Princeton, NJ':                  '普林斯顿（新泽西州）',
  'Côte d\'Azur':                   '蔚蓝海岸',
  'Hollywood':                      '好莱坞',
  'Addis Ababa':                    '亚的斯亚贝巴',
  'Alger':                          '阿尔及尔',
  'Amboseli':                       '安博塞利',
  'Barkley Cove (NC coast)':        '巴克利湾',
  'Brittany':                       '布列塔尼',
  'Brooklyn, NY':                   '纽约·布鲁克林',
  'Bruges':                         '布鲁日',
  'Budapest':                       '布达佩斯',
  'Buenos Aires':                   '布宜诺斯艾利斯',
  'Cameron Highlands':              '金马伦高原',
  'Cartagena':                      '卡塔赫纳',
  'Castaway Island':                '荒岛',
  'Cincinnati, OH':                 '辛辛那提',
  'Cidade de Deus, Rio de Janeiro': '里约热内卢·上帝之城',
  'Coahuila, northern Mexico':      '科阿韦拉',
  'Danzig (Gdańsk)':                '但泽（格但斯克）',
  'Giza (Egyptian Pyramids)':       '吉萨（埃及金字塔）',
  'Hanging Rock, Victoria':         '悬岩（维多利亚州）',
  'Ilhéus, Bahia':                  '伊列乌斯，巴伊亚',
  'Illiers-Combray':                '伊利耶-孔布雷',
  'Issy-l\'Évêque (Burgundy)':      '伊西勒韦克（勃艮第）',
  'Istanbul':                       '伊斯坦布尔',
  'Jackson, MS':                    '杰克逊（密西西比州）',
  'Johannesburg':                   '约翰内斯堡',
  'Kabul':                          '喀布尔',
  'Kochi (Kerala)':                 '科钦（喀拉拉邦）',
  'Kingston, Ontario':              '金斯顿（安大略省）',
  'Lima':                           '利马',
  'London':                         '伦敦',
  'Lonesome Dove, TX':              '孤鸽镇',
  'Macondo (Aracataca)':            '马孔多',
  'Magdalena River':                '马格达莱纳河',
  'Manosque (Provence)':            '马诺斯克（普罗旺斯）',
  'Marseille':                      '马赛',
  'Meryton (Hertfordshire)':        '默里顿（赫特福德郡）',
  'Molching (near Munich)':         '莫尔欣（慕尼黑附近）',
  'Monroeville, AL':                '门罗维尔',
  'Montréal (Saint-Henri)':         '蒙特利尔（圣亨利区）',
  'Moscow':                         '莫斯科',
  'Mumbai':                         '孟买',
  'New York':                       '纽约',
  'Nice':                           '尼斯',
  'Oran':                           '奥兰',
  'Orient Express, Yugoslavia':     '南斯拉夫·东方快车',
  'Osaka':                          '大阪',
  'Osaka (feudal)':                 '大阪（封建时代）',
  'Oxfordshire':                    '牛津郡',
  'Pacific Ocean':                  '太平洋',
  'Paris (Notre-Dame)':             '巴黎（圣母院）',
  'Paris':                          '巴黎',
  'Perth':                          '珀斯',
  'Prague':                         '布拉格',
  'Prince Edward Island':           '爱德华王子岛',
  'Rome':                           '罗马',
  'Rural Poland':                   '波兰乡村',
  'Sahara':                         '撒哈拉',
  'Saint-Malo':                     '圣马洛',
  'Salinas, CA':                    '萨利纳斯',
  'San Francisco Chinatown':        '旧金山唐人街',
  'Santiago de los Caballeros':     '圣地亚哥·德洛斯·卡瓦利洛斯',
  'Shanghai (Lunghua Camp)':        '上海（龙华集中营）',
  'Soldier Island, Devon':          '德文郡·孤岛',
  'Tangier':                        '丹吉尔',
  'Umuofia (Igboland)':             '乌莫菲亚',
  'Višegrad':                       '维谢格拉德',
  'West Egg, Long Island':          '长岛·西卵',
  'Geneva':                         '日内瓦',
  'Cape Town':                      '开普敦',
  'Paris (Belleville)':             '巴黎（贝尔维尔）',
};

const COUNTRY_FR: Record<string, string> = {
  'Algeria':                  'Algérie',
  'Argentina':                'Argentine',
  'Australia':                'Australie',
  'Belgium':                  'Belgique',
  'Bosnia and Herzegovina':   'Bosnie-Herzégovine',
  'Brazil':                   'Brésil',
  'Caribbean (near Trinidad)':'Caraïbes',
  'Channel Islands':          'Îles Anglo-Normandes',
  'China':                    'Chine',
  'Colombia':                 'Colombie',
  'Czech Republic':           'République tchèque',
  'Dominican Republic':       'République dominicaine',
  'Egypt':                    'Égypte',
  'Ethiopia':                 'Éthiopie',
  'Germany':                  'Allemagne',
  'Hungary':                  'Hongrie',
  'India':                    'Inde',
  'Italy':                    'Italie',
  'Japan':                    'Japon',
  'Malaysia':                 'Malaisie',
  'Mexico':                   'Mexique',
  'Morocco':                  'Maroc',
  'Myanmar':                  'Birmanie',
  'Peru':                     'Pérou',
  'Poland':                   'Pologne',
  'Russia':                   'Russie',
  'Sahara desert':            'désert du Sahara',
  'Serbia':                   'Serbie',
  'Spain':                    'Espagne',
  'South Africa':             'Afrique du Sud',
  'the high seas':            'haute mer',
  'Türkiye':                  'Turquie',
  'UK':                       'Royaume-Uni',
  'United Kingdom':           'Royaume-Uni',
  'USA':                      'États-Unis',
};

const PLACE_FR: Record<string, string> = {
  // Author timeline cities (only those that differ from English)
  'Mexico City':                    'Mexico',
  'Barcelona':                      'Barcelone',
  'Brussels':                       'Bruxelles',
  'Guernsey':                       'Guernesey',
  'Tehran':                         'Téhéran',
  'San Jose':                       'San José',
  'Edinburgh':                      'Édimbourg',
  'Saint Paul, MN':                 'Saint Paul (Minnesota)',
  'Princeton, NJ':                  'Princeton (New Jersey)',
  'Lunghua Camp, Shanghai':         'Camp de Lunghua, Shanghai',
  'London':                         'Londres',
  'Moscow':                         'Moscou',
  'Kabul':                          'Kaboul',
  'Rome':                           'Rome',
  'Sahara':                         'Sahara',
  'Pacific Ocean':                  'Océan Pacifique',
  'Orient Express, Yugoslavia':     'Orient-Express, Yougoslavie',
  'Osaka (feudal)':                 'Osaka (féodal)',
  'Cape Town':                      'Le Cap',
  'New York':                       'New York',
};

export function translatePlace(place: string, lang: string): string {
  if (lang === 'Chinese') return PLACE_ZH[place] ?? place;
  if (lang === 'French')  return PLACE_FR[place] ?? place;
  return place;
}

export function translateCountry(country: string, lang: string): string {
  if (lang === 'Chinese') return COUNTRY_ZH[country] ?? country;
  if (lang === 'French')  return COUNTRY_FR[country] ?? country;
  return country;
}
